configure.ac
Running sed 's/\/lib/\${libdir}/' destroys any ${systemdsystemunitdir}
values that don't start with '/lib' e.g. '/usr/lib64/systemd/system'
becomes '/usr/usr/lib6464/systemd/system'.
If a local installation prefix is needed use appropriately prefixed
--with-systemdsystemunitdir='' parameter instead.
=> Undo ${systemdsystemunitdir} mangling.

data/driver.list.in, docs/man/usbhid-ups.txt, drivers/libhid.c, drivers/libhid.h, drivers/powercom-hid.c, drivers/usbhid-ups.c
Tested with BNT-1000AР (old model). Confirmed values: battery.charge, input.frequency (0 on battery, 50 on AC), input.voltage, output.voltage, ups.load and likely output.frequency (always 50); statuses: online, cal (ups test), dischrg, trim.
Key changes:
* Read exactly 8 bytes on interrupt.
* Get values of input objects. Getting both will be better since there are some feature objects during init.
* Avoid comm_driver->get_report since it often returns corrupt data (0 values).
=> Add support for 0d9f:0001 (USB HID, Powercom)

server/upsd.c
Fix issue #190 - upsd: NSS SSL only working in debug mode
https://github.com/networkupstools/nut/issues/190
This fix trivial.
Has been tested with NSS and OpenSSL with upsd in deamon and non-deamon mode.
=> Initialize SSL after deamonize and downgrade to user.

drivers/hidparser.c, drivers/hidtypes.h, drivers/libhid.c, drivers/libshut.c, drivers/libshut.h, drivers/libusb.c, drivers/usb-common.h, drivers/usbhid-ups.c
All devices use HID descriptor at index 0. However, some newer
Eaton units have a light HID descriptor at index 0, and the full
version is at index 1 (in which case, bcdDevice == 0x0202). This dual
report descriptor approach is due to the fact that the main report
descriptor is now too heavy, and cause some BIOS to hang. A light
version is thus provided at the default index, solving this BIOS issues.
Also, increase the maximum number of HID objects that can be
retrieved, and add some more trace to make it easier to catch similar
issues in the future
=> Add support for Eaton dual HID report descriptor

drivers/tripplite-hid.c, drivers/usbhid-ups.c
See http://thread.gmane.org/gmane.comp.monitoring.nut.devel/6961 for details.
Basically, `FindObject_with_Path()` was returning NULL on events from the interrupt pipe, and `find_hid_info()` was matching the first entry in `tripplite_hid2nut[]` (which was not present on the Tripp Lite UPS in question).
This patch allows the interrupt code to match either `TYPE_INPUT` or `TYPE_FEATURE` items.
=> usbhid-ups input vs feature

drivers/powerware-mib.c
This adds some commands to the Powerware SNMP handler to avoid some power races where the NUT client shuts down, but the Powerware UPS has mains power restored before it shuts down.
=> Additions for the Powerware SNMP driver

clients/nutclient.cpp
Problem: nutclient library sometimes reads socket closed by server. Causes 100% CPU utilization.
Solution: proper ::read() return value evaluation
read returns -1 only if socket option O_NONBLOCK is set. But this option is explicitly avoided in connect method. When there is reading problem 0 is returned.
=> nutclient library socket reading

data/driver.list.in, docs/man/nutdrv_qx.txt, drivers/nutdrv_qx.c
Let's recap:
- some time ago, TS Shara provided us with a patched version of blazer_usb, which added support for their devices,
- we then moved that code (after fixing a couple of minor bugs) to nutdrv_qx,
- over the past year, I kept it updated (meanwhile fixing another couple of small bugs).
Now, I got one user to test it: everything works as expected, but.. the shutdown/restore sequence.
What he described me (the shutdown works, but when mains returns the UPS keeps turning itself off and then on endlessly, unti he unplugs the USB cable) makes me think of a problem in the test procedure (he manually sets the FSD flag -which cannot be cleared unless you restart upsd: he told me the system running upsd is turned off, but maybe it's not really turned off but only suspended to disk - I have …
=> nutdrv_qx: TS Shara

clients/upsrw.c, docs/man/upsrw.txt, docs/net-protocol.txt, server/netget.c
Any variable that is not STRING, RANGE or ENUM is just a simple numeric value.
The protocol documentation (net-protocol.txt) was previously stating that "The
default <type>, when omitted, is integer." which was not fully true, since a
variable could also be a float.  Hence, the wording was changed to advertise
this, and that each driver is then responsible for handling values as either
integer or float.  Moreover, instead of returning a TYPE "UNKNOWN", return
"NUMERIC", which is more suitable, and aligned with the NUT protocol
specification
=> Default to type NUMBER for variables

data/cmdvartab, data/driver.list.in, docs/nut-names.txt, drivers/Makefile.am, drivers/apc-ats-mib.c, drivers/apc-ats-mib.h, drivers/eaton-ats-mib.c, drivers/eaton-ats-mib.h, drivers/snmp-ups.c
Extend NUT namespace to support a new type of power device: ATS - Automatic
Transfer Switch.  These devices are used to setup 2 power systems, such as
UPS, to power a single power supply system, and be able to automatically
transfer between the input sources in case of failure of the primary one.
Also implement support for Eaton ATS in the snmp-ups driver. APC ATS may follow.
=> Add support for ATS - Automatic Transfer Switch

docs/download.txt
The previous link is over 5 years old, nut is now maintained in the packages repository on GitHub.
=> Update OpenWRT package information

docs/configure.txt, m4/nut_check_libgd.m4, m4/nut_check_libnetsnmp.m4
Current m4 scripts assume a fixed program name to be in PATH. This is not always the case, e.g. in Solarish oi-userland we have /usr/bin/net-snmp-config-{32,64} and /usr/bin{,/$(MACH64)}/gdlib-config
=> Allow to customize path to gdlib-config and net-snmp-config programs

configure.ac, docs/Makefile.am, docs/configure.txt, docs/man/Makefile.am
Rationale: on a build-host that prepares packaging for multiple architectures in empty workspaces, it suffices to build the docs just once, including manpages (should the buildhost recipe define so). Now this can be done indeed.
Note: disabled manpage generation explicitly causes "make dist" to fail, in order to avoid dist'able tarballs not conforming to spec and expectations.
Also this PR reduces noise about systemd on OSes or builds that are not relevant for it.
=> Configure : allow to fully toggle generation of manpages among other docs, and do not ALWAYS blindly attempt systemd setup

configure.ac
Follow-up to NUT PR #288 after some offline discussion
=> configure.ac : prefer "/usr/share/augeas/lenses/dist" over "/usr/share/augeas/lenses" if present

drivers/powerp-txt.c
Verified to invoke deep test on the CyberPower OL3000RMXL2U.
=> Add deep battery test for CyberPower OL3000RMXL2U

drivers/libhid.c, drivers/tripplite-hid.c, drivers/usbhid-ups.c, scripts/upower/95-upower-hid.rules
Note that protocol 1330 does not respond to requests for
UPS.OutletSystem.Outlet.DelayBeforeReboot, therefore those
requests needed to be bypassed in the driver.
Reported values appear correct, no further testing performed.
Signed-off-by: Timothy Pearson <kb9vqf@pearsoncomputing.net>
=> Add support for SU3000LCD2UHV

clients/nutclient.cpp
If device doesn't exist, getClient() returns NULL. Then calling the method
like getClient()->getDeviceDescription(getName()) causes segfault.
We rather check the status and throw an exception in this case.
=> nutclient: fix library segmentation fault if device name doesn't exists.

docs/man/snmp-ups.txt, drivers/snmp-ups.c
Review on PR #314 mentioned that the snmp-ups manpage does not reflect all built-in MIBs. Indeed... and I found no easy way to list them in a pretty manner. So now here is one ;)
=> Add mib2nut listing (this should help set up snmp-ups driver)

common/common.c, include/common.h
For debugging output, we want to prepend the debug level so the user can e.g. more easily lower the level (less -D's on command line) to retain just the amount of logging info he needs to see at the moment. Using '-DDDDD' all the time is too brutal and needed high-level overview can be lost. This [D#] prefix can help limit this debug stream quicker, than experimentally picking ;)
Example screenshot (testing code in screenshot is not part of this commit, a copy for reference is just below in the comment):
````
$ ./snmp-ups -DDDDDDDD -a x
Network UPS Tools - Generic SNMP UPS driver 0.99 (2.7.4-109-g0059555)
0.000000	[D2] Processing CLI option  1 'D' : '(null)'
0.000018	[D2] Processing CLI option  1 'D' : '(null)'
0.000025	[D2] Processing CLI option  1 'D' : '(null)'
0.000033	[D2] Processing …
```
=> Enhance Upsdebugx with the message's debug-level tag

tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
These are two somewhat separate, but quite interwoven pieces of work which are easier to push together than to untangle backwards:
* revision of nut-scanner code structure for logging approaches common with other NUT programs (e.g. use `upsdebugx()` and `-D` flag) and push the help-text printer out of common loop into a separate routine,
* enhance netxml(udp) scanning to do not only broadcasts on a connected segment as before (if no target IP is provided), but also be able to scan single IP (`-s` alone), range of IPs (`-s` + `-e`) and subnets (`-m`) instead
* this includes a more evolved variant of not-suggesting XMLv4 devices mistakenly as if they were netxml-supported (so this code supersedes PR #324)
Work by Jim Klimov and Michal Vyskocil (@vyskocilm).
=> Nut-scanner debugging revision and NetXML scanning support for IP addresses

clients/upsclient.c
struct timeval is declared in sys/time.h, so we need to #include it.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
=> client/ups: add missing include

.gitignore, .travis.yml, ci_build.sh, configure.ac, docs/Makefile.am, docs/man/Makefile.am
Combining the features of PR #352 and #353, this one offers builds that are faster thanks to not installing the doc-processing packages and not generating any docs in most cases; it does however enable distcheck for the `default-alldrv` case so it became a bit slower than in PR #352 by doing twice the work (but being on a safer side now).
Compare the results at https://travis-ci.org/jimklimov/nut/builds/188979713 (`--with-doc=skip`) and https://travis-ci.org/jimklimov/nut/builds/188980602 (without skipping).
=> Travis matrix builds with docskip (PRs 352+353 synergized together)

.gitignore, .travis.yml, ci_build.sh, docs/Makefile.am
This extends the basics of PR #351 and defines several build scenarios that would run in parallel - and provides a template for future similar customized tests. As detailed in issue #338 this adds several build scenarios to quickly see if a coding/Makefile error breaks the repo:
* a "default-nodoc" build takes about a minute (just build and install - no docs, no distcheck)
* a "default" build (just manpages and a distcheck) is over 2 minutes
* a "default-withdoc" (all formats and distcheck) is over 5 minutes
* a "default-alldrv" (no doc => no distcheck, but otherwise `--with-all`) is just a bit longer than "default-nodoc"
These times might be improved by integrating the changesets (PR #353) which added support for `--with-doc=skip` so that a (limited) `make distcheck` can still be done …
=> Travis CI matrix builds

common/snprintf.c, configure.ac
For kicks I configured and built with "-Wall -Werror"... and the build died on me, on several OSes. So this is a proposed fix, as far as syntax is concerned. Testing desired (that strings are still printed as they should be), and running on the buildbot farm should be useful too ;)
=> Fix warnings (C99; local snprintf() and math functions)

data/driver.list.in, drivers/Makefile.am, drivers/apc-pdu-mib.c, drivers/apc-pdu-mib.h, drivers/snmp-ups.c
Upstreaming fixes applied to our project at work
From: Arnaud Quette <arnaud.quette@free.fr>
Date: Fri, 8 Apr 2016 14:40:00 +0200
Subject: [PATCH] snmp-ups: support APC PDU
Based on initial work and data from Opengear, using SNMP subdriver creation
script, add support for the more recent APC PDU.  This was tested with a AP8958,
but should cover other models
=> APC ePDU MIB support

drivers/snmp-ups.c
Checked that in `*-mib.c` tables there is no standalone "bypass" (except for a few status or config nodes):
````
$ git grep bypass drivers/*-mib.c | grep -v input.bypass
drivers/apc-mib.c:	{ "bypass.start", 0, 2, ".1.3.6.1.4.1.318.1.1.1.6.2.7.0", "", SU_TYPE_CMD | SU_FLAG_OK, NULL },
drivers/apc-mib.c:	{ "bypass.stop", 0, 3, ".1.3.6.1.4.1.318.1.1.1.6.2.7.0", "", SU_TYPE_CMD | SU_FLAG_OK, NULL },
drivers/compaq-mib.c:	{ 4, "OL BYPASS" /* bypass */ },
drivers/compaq-mib.c:	 * bypassFeed(4)
drivers/delta_ups-mib.c:    { 2, "BYPASS" },    /* bypass */
drivers/ietf-mib.c:	{ 4, "OL BYPASS" /* bypass */ },
drivers/mge-mib.c:static info_lkp_t mge_bypass_info[] = {
drivers/mge-mib.c:	{ 4, "BYPASS" /* bypass */ },
drivers/mge-mib.c:	{ "ups.status", ST_FLAG_STRING, SU_INFOSIZE, …
```
=> snmp-ups.c : presumed typo fix : NUT var for bypass mapping is "input.bypass"

docs/man/netxml-ups.txt, docs/nut.dict, drivers/mge-xml.c, drivers/netxml-ups.c
Made a debug level 5 notice for end-users, and bumped subdriver version for clarity.
Note: version bump from 0.26 to 0.28 accounts for another recent PR against this file that bumps it to 0.27.
=>  Disable mge-xml.c::convert_deci() that was needed a decade ago 

drivers/mge-xml.c
Suggested by travis warnings in FTY branch
=> Update mge-xml.c : Include drivers/main.h to get testvar() declared properly

scripts/systemd/nutshutdown.in
Use "systemctl reboot --force --force" to reboot the machine has not
been shutdown after the POWEROFF_WAIT delay.
Closes: #382
=> Add support for POWEROFF_WAIT parameter

docs/nut.dict
@jimklimov I noticed a few of the words (ID's, Javadoc) jumped around in the sort order. Is that a fluke, or should we force `LANG=C` for sort in docs/Makefile.am?
It is also possible that I messed something else up, hence the PR rather than committing directly.
=> Re-sort nut.dict

.travis.yml
Solution in .travis.yml : since Travis cloud starts the jobs as soon as it has resources, move the bulk of quicker matrix jobs to start after the longest withdocs build. Experimental note: we still need one job defined in the simple matrix for default environment, but can keep others in a single explicitly ordered list. Now the "Running for" time got cut from 8-9 to 5.5-6 minutes.
=> Problem: NUT tests in Travis CI often wait for default-withdoc

docs/man/liebert-esp2.txt, docs/nut.dict, drivers/liebert-esp2.c
• Refactor output format of liebert-esp2 driver to follow that of other drivers to fix the nut-cgi interface as well as for overall consistency. 
• Implement proper support for "2 phase" i.e. split phase input Liebert GXT2 series units. Existing driver treats these units as 3 phase which results in a large number of unpopulated/zero values being returned by the driver.
• Correct battery voltage scaling for GXT2 series units.
• Include notes in liebert-esp2 man page that the DB9 cable used to interface a GXT2 series UPS to its host system must not connect and handshaking/flow control lines since these are used for other features such as non "smart" shutdown and power loss notification. Using a DB9 cable with full handshaking with a GXT2-6000RT208 UPS is confirmed to cause an unintended …
=> liebert-esp2 changes: Correct battery V scaling, update docs, implement split-phase unit support

clients/upsclient.c, drivers/gamatronic.c, drivers/openups-hid.c, drivers/snmp-ups.c, server/netssl.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/nutscan-serial.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
This is another attempt to improve the code through static code analysis, using Cppcheck
Command line: `cppcheck --inconclusive --std=c89 --force .`
1rst iteration, limited to errors and using c89 as the standard.
Errors list:
Notes:
* warnings on common/snprintf.c can be fixed by refreshing with https://github.com/weiss/c99-snprintf
=> [WIP - DO NOT MERGE] Cppcheck improvements

Makefile.am, configure.ac
* Support --with-systemdsystemshutdowndir=DIR as a separate configure option
* Add the workaround path option in distcheck defaults
* Detect presence of systemd, so --with-systemd*=auto is in effect by default for units and the script
Extends work and review done in #424 and #425 by @stanislav-brabec and @clepple and myself :)
=> Improve the fix for nutshutdown and systemd

docs/nut-names.txt, drivers/eaton-mib.c, drivers/snmp-ups.c
Outlets groups can now publish the electrical phase to which the physical
outlets group (Gang) is connected to. This is useful for 3ph ePDU
=>  snmp-ups: add support for outlet.group phase

docs/man/nutupsdrv.txt, drivers/main.c
Hello,
Sometimes, some specific scenarios need to be able to run some driver instances not based on ups.conf.
For example, we could want to temporary launch a driver with specific configuration without having to modify the ups.conf file and discuss directly to it, without passing by upsd. This can be useful to validate existence of some devices, temporarily testing credentials, acquire some data, all of that without polluting upsd data.
This patch only add a specific driver option "-s" similar to existing "-a" but without reading ups.conf file.
Best regards,
Emilien
=> Add cmdline option to run drivers not based on ups.conf.

tools/gitlog2changelog.py
Alternative to https://github.com/networkupstools/nut/pull/427
=> gitlog2changelog: Date header only occurs at start of line

configure.ac, docs/Makefile.am, docs/man/Makefile.am, m4/nut_check_asciidoc.m4
As reaction to issue #448 this PR changes handling of `--with-doc=man=auto` (which is the default behavior if no `--with-doc` is specified on command-line) to fall back to installation of pre-built docs (currently just manpages) that can be available in either build or source dir, for tarball distributions.
Tested with `./configure --with-all=no && make distcheck-light` by requiring a non-existently large minimal version of ASCIIDOC in m4 in one case, and leaving the correct version in the other - so both codepaths seem to install the manpages correctly.
=> Support builds and installs on systems without suitable asciidoc (fix issue #448)

drivers/Makefile.am
Other than formerly assumed in the makefile cflags can be more than
includes. And some of them need to be in sync in regard to CFLAGS and
LDFLAGS - for example usage of -fPIE.
This conflicts with a current assumption in the makefile "In any case,
CFLAGS are only -I options, so there is no harm".
On a Distribution where PIE is enabled by default, but disabled for
special cases (like net-snmp) the configure detection gets them as:
LIBNETSNMP_CFLAGS = -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2
-fdebug-prefix-map=/build/net-snmp-nlMQSZ/net-snmp-5.7.3+dfsg=.
-specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong
-Wformat -Werror=format-security -DNETSNMP_USE_INLINE -Ulinux
-Dlinux=linux -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv
-fno-strict-aliasing -pipe …
=> automake: only pass net-snmp cflags to snmp-ups

data/driver.list.in, docs/nut-names.txt, drivers/eaton-ats16-mib.c
ATS can now publish the electrical dephasing between input sources
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
=> snmp-ups: add support for input.phase.shift

configure.ac, tests/Makefile.am
See also #472 and #366 and #466
=> Improve cppunit and C++11 support via configure.ac

Makefile.am, configure.ac, scripts/systemd/Makefile.am
The configure script assumes that systemd is installed below ${libdir},
which is not true on many biarch Linux distros with /lib64. Instead of
guessing, use pkg-config to find the path and provide a
--with-systemdshutdowndir option so that make distcheck can override it.
Also, rename the internal varable to systemdshutdowndir to rhyme with
the respective systemd.pc variable.
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
=> configure.ac: Fix systemd shutdown directory detection

tools/nut-scanner/nut-scanner.c
Solution: Move the call to this stateless function to the point after we parse arguments and just before we'd start the actual scans. Later this can be extended to also consider which scans were requested and so which libs to load.
Thanks to @clepple for research in https://github.com/networkupstools/nut/issues/500
=> Problem: nutscan_init() called before debug is enabled

data/driver.list.in
The IDG and IPG models were not included in the protocol documentation provided
to the NUT project. Some values are also returned as 0xFF/0xFFF/0xFFFF - see
the HCL for details.
Source: http://lists.alioth.debian.org/pipermail/nut-upsdev/2017-November/007357.html
=> HCL: Change Riello IDG/IPG support level to 4

drivers/main.c, drivers/upsdrvctl.c
Tracing issues with service development, I found these messages are less than useful, and in case of `upsdrvctl stop` - even misleading (why does it make a pidfile with device name but look for the port name? oh, now we know).
=> main.c upsdrvctl.c : make debug messages a bit more useful

tools/nut-snmpinfo.py, tools/nut-usbinfo.pl
so that nut builds in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.
=> Sort input file list

tools/nut-scanner/nut-scanner.c
As noted in #502 (https://github.com/networkupstools/nut/pull/502#issuecomment-373559680), that patch is a bit problematic and made some `nut-scanner`'s options unavailable -- something like this should work, instead, without those side effects.
...or we could lower our smartness a notch or two and simply list and process all the options always and then only call the relative routine if really available.
=> nutscanner: get debug level early (for nutscan_init()) and restore options

.travis.yml, ci_build.sh, configure.ac
Solution: detect presence and usability of pkg-config program
and autotools macros (they end up as unexpanded tokens if
pkg-config is not installed), and use this knowledge to
proceed with search for libcppunit - or not. When the test is
optional, we should not kill the build if we can not make it
due to missing tools.
=> Problem: configure fails on system without pkg-config

docs/man/Makefile.am, scripts/subdriver/gen-snmp-subdriver.sh
Hope to get to refreshing the bigger ones sometime soon too :)
=> Upstream smaller fixes from 42ity NUT

scripts/systemd/Makefile.am
On some systems, distcheck complained without this in place, and passed with it.
=> EXTRA_DIST scripts/systemd/nut.target also

common/common.c
Should help 64-bit builds on Solaris-like platforms (assuming they are from the last decade or two, so an `amd64` or `sparcv9` subdirectory is symlinked as `64`) and illumos-based distros.
=> get_libname() : support more 64-bit pathname patterns

.travis.yml
A bite-size rearrangement to practically enable the `default` test scenario.
=> .travis.yml : matrix job seems to require having at least two items

Makefile.am, tools/Makefile.am, tools/nut-scanner/Makefile.am, tools/nut-snmpinfo.py, tools/nut-usbinfo.pl
Avoid rebuilding nut-scanner upon every invokation of `make` or after `make deps`.
=> Nut scanner deps

clients/upsmon.c, clients/upssched.c, common/parseconf.c
File descriptors are leaking to processes spawned by upsmod and
upssched, leading to SELinux errors when (for example) sendmail
attempts to read from fd #4.
=> Add FD_CLOEXEC flag to config files, pipes and sockets

drivers/mge-xml.c, drivers/netxml-ups.c, drivers/netxml-ups.h
This sets the CAL status whenever a battery self-test is in progress. Tested on an Eaton 5PX 2200.
=> netxml-ups: Report calibration status

drivers/eaton-pdu-marlin-mib.c, drivers/hpe-pdu-mib.c
Add support for extra parameter for instant commands on Eaton and HPE ePDU
=> snmp-ups: support extra param for instcmd (Eaton/HPE)

clients/Makefile.am, clients/nutclient.cpp, clients/nutclient.h, docs/net-protocol.txt, docs/nut.dict
Instant commands were almost ready for supporting additional parameter.
However, it was not documented, and libnutclient was not supporting it yet
Signed-off-by: Arnaud Quette <arnaud.quette@free.fr>
=> Add support for extra parameter for instant commands

common/common.c
Solution: Do our best to guess the bitness of a build,
and use it in search paths for get_libname()
=> Problem: 32-bit builds fail to load 64-bit libs

clients/Makefile.am, tools/nut-scanner/Makefile.am
While NUT itself currently does not provide packaging recipes, or at least not those so hardcoded to be directly impacted by the change in #652, these comments would serve to remind developers also associated with OS packaging distributions that changes in the `-version-info` parameter can have far-reaching effects.
Also these can serve as a reminder to somehow "macroize" and automate setting and finding the shared library versions, so the makefiles in NUT codebase and the consuming packaging recipes elsewhere can have a reliable contract to exchange this data.
=> nut-scanner and clients Makefile.am : comments about version-information

configure.ac
Solution: bump from XXXXX to XXXXXXX which did not complain in another part of the configure script
Example errors here : http://buildbot.networkupstools.org/public/nut/builders/OpenBSD-x64/builds/579/steps/compile/logs/stdio and recently here : http://buildbot.networkupstools.org/public/nut/builders/OpenBSD-x64/builds/706/steps/configure/logs/stdio
````
...
checking for strptime... yes
checking for setlogmask... yes
checking whether LOG_UPTO is declared... yes
checking whether ln -sr works... mktemp: insufficient number of Xs in template `dir1.XXXXX'
no, using ln
checking for unsigned long long int... yes
checking for vsnprintf... yes
...
````
=> Problem: OpenBSD mktemp complains on short pattern

clients/nutclient.cpp, clients/nutclient.h, docs/new-clients.txt, docs/nut.dict
Extends libnutclient's C++ API to support tracking commands.
=> Implement tracking commands in libnutclient

clients/upsclient.c, clients/upssched.c, m4/nut_check_libopenssl.m4, server/netssl.c
Tumbleweed (openSUSE) is switching to OpenSSL-1.1.0 shortly. Apply changes to server & client code and AutoConf magic to make this happen.
=> Add support for openssl-1.1.0

tools/nut-scanner/scan_snmp.c
Scanning isn't working when SNMPv3 authentication/privacy password is required. Tested with an Eaton ePDU.
=> Fix SNMPv3 in nut-scanner

tools/nut-scanner/scan_snmp.c
nut-scanner is omitting `snmp_version` option when required for SNMPv3.
=> Fix nut-scanner SNMPv3

server/conf.c
Solution: as a quick fix, pick the first char of the string we pass.
The proper fix would be to use the str_*() API for safe conversions,
in a later iteration.
See-also: https://github.com/networkupstools/nut/issues/676
=> Problem: isdigit() receives a char* instead of char

configure.ac
/me bad, foolish typo... hid for log...
=> configure.ac : fix mismatched usage of have_cxx11 envvar

.travis.yml, Makefile.am, ci_build.sh
It is annoying to find foolish typos like quotation mark mismatch after spending time to build a package... so this should happen no longer :)
NOTE: This is in the end not part of common required `check-local` because tools for this activity (like `file`) may be missing on an arbitrary system and should not block builds there. Maybe this can be extended by a `configure` check later on.
For good output, see e.g. https://travis-ci.org/networkupstools/nut/jobs/503591138
And a staged example failure at https://travis-ci.org/jimklimov/nut/jobs/503593246#L924 :
````
...
+/bin/sh -n tests/nut-driver-enumerator-test.sh
tests/nut-driver-enumerator-test.sh: 318: tests/nut-driver-enumerator-test.sh: Syntax error: newline unexpected (expecting ")")
ERROR: Syntax check failed for script file: …
```
=> Introduce shell script syntax checks

drivers/snmp-ups.c
Driver had been setting read/write parameters as
either Integer or String, but OIDs that expect
TimeTicks cannot be set using an Integer.
snmp-ups already supported getting TimeTicks
correctly and had helper functions for setting
TimeTicks, but logic had not been implemented in
su_setOID().
=> snmp-ups: add ability to set TimeTicks correctly

drivers/bestfcom.c
"off" command for FE7000 required at least 5 seconds for the command to be accepted.  
Also should match the off with autostart or "o" with "a" to be consistent with the manual: https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/backup-power-ups/eaton-ferrups-tower-ups/eaton-ferrups-FE-QFE-userguide-.pdf  (o [time] a is how the manual references the "short" command)
=> Fix for Ferrups FE7000 "off" command

common/common.c
A small typo with big consequences. Thanks to colleagues with a zoo of distros for helping notice this.
=> common.c : BUILD_64 not detected in some distros, needs stdint.h

drivers/tripplite_usb.c
The debug output for a device using the Tripp Lite
09ae 3005 protocol seems to show that the
ups.debug.L is the load as noted on mailing
list posts. Decode it and report it as ups.load.
Tested on TRIPP LITE SMART500RT1U.
=> Report load for Tripp Lite USB 3005 protocol

m4/nut_check_libgd.m4
gdlib-config has been dropped from version 2.3.0 with https://github.com/libgd/libgd/commit/d62f608c7c4a814c70d4ba777725e3e62d9e2cde
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> nut_check_libgd.m4: try to find gd through pkg-config

drivers/apcupsd-ups.c, drivers/apcupsd-ups.h
This commit fixes the `ignorelb` flag for the `apcupsd-ups` driver. Previusly "battery.charge" and "battery.runtime" was cleared before invoking `status_commit()` which caused the LB-condition to always be `false`.
=> Do not call `dstate_delinfo()` for LB-condition variables

drivers/apcupsd-ups.c
This commit removes the hardcoded poll-interval of 60 seconds and instead only makes sure that the user-defined interval is greater than a minimum-interval.
=> Do not overwrite `poll_interval` in `apcupsd-ups`

common/state.c
=> Respect `ST_FLAG_IMMUTABLE` in `dstate_delinfo()`

clients/upsmon.c, clients/upsmon.h
Some UPS calibration procedures (e.g. CyberPower) involve
discharging the battery below the LB level, but we don't
want systems to shut down if the UPS is only on battery
because it is calibrating.
=> Do not shutdown if UPS is performing calibration

configure.ac, drivers/Makefile.am, drivers/asem.c, drivers/pijuice.c
This PR adds support for the PiJuice HAT (https://uk.pi-supply.com/products/pijuice-standard)
Included with this patch is more robust autoconf support for the 3.x and 4.x releases of the i2c-tools library, with the 4.x release adding the user space include file name i2c/smbus.h to resolve a user/kernel include file naming conflict.  This will make it easier for future I2C drivers to handle both build environments.
I also fixed a compile warning in the ASEM driver where it needed sys/ioctl.h for a constant, but I did not update that driver to use the new I2C definitions since I do not have the hardware to test that it would not break anything.
> $ upsc hat@localhost
> battery.capacity: 1.820
> battery.charge: 93.7
> battery.charge.low: 25
> battery.charger.status: resting
> …
=> Add support for PiJuice HAT

configure.ac, docs/man/Makefile.am, docs/man/index.txt, docs/man/pijuice.txt, docs/nut.dict, drivers/Makefile.am, drivers/asem.c, drivers/pijuice.c
Follows up from #730 to solve its PR-merging nits.
=> Pijuice cleanup

drivers/main.c
Do not switch to statepath, nor write pidfile, when using the
datadump (-s -d) mode
=> Driver datadump improvements

drivers/cyberpower-mib.c
1. `shutdown.return`
1. `shutdown.stayoff`
1. `ups.delay.start`
1. `ups.delay.shutdown`
* CyberPower's CPS-MIB provides different delay values for return vs stayoff. I am using the return (aka sleep) value, because that is the more common use case.
1. `ups.delay.reboot`
* Not supported by CPS-MIB but the subdriver reports as 0, because that is the de facto default for CyberPower.
1. `load.off/on`
1. `test.failure.start`
1. `test.panel.start`
1. `test.battery.start`
1. `calibrate.start/stop`
* `sysOID` was CyberPower's enterprise OID, not what the UPS RMCARDxxx returns, which is `CPS-MIB::ups` (*CyberPower_enterprise_OID*.1.1.1)
* `ups.status` is more informative
1. Reports BOOST
1. Reports RB (replace battery)
1. Reports CAL (calibration in progress)
* `battery.runtime` now returns the …
=> cyberpower-mib: Add shutdown capability and other instant commands

.travis.yml, docs/developers.txt, drivers/solis.c
Follows up for PR #824 answering to issue #823 to bring green (nowarn) jobs into the realm of configs no longer allowed to fail, and fix a minor issue with `solis.c` driver to have at least no-warn builds of NUT in gnu89 mode too.
This also documents in `developers.txt` that we support C99 at this time.
=> Reshuffle Travis CI matrix of allowed_failure jobs

docs/developers.txt
I suppose this would cause a fair bit of bikeshedding as any style doc does, so put it as a separate PR :) 
But AFAIK, this just spells out the existing precedent so should not stall for too long.
=> docs/developers.txt : document coding style examples for tabs vs spaces

clients/nutclient.cpp, clients/nutclient.h
These are invalid in c++17 and must be removed for compatibility with modern compilers.
=> Remove dynamic exception specifications from clients/nutclient.cpp

.travis.yml, ci_build.sh
Follows up from #829 (for issue #823) to disable in master branch and PR builds the test cases which are currently failing and not actively being addressed, to conserve Travis CI resources. Developers who would pick up experiments on fixing those builds (warnings made fatal, strict C standards, Windows builds) can easily uncomment these lines in their branches, and eventually post to master new green lines for future commits to keep up as green.
There were other possibilities experimented, with Travis conditions https://docs.travis-ci.com/user/conditions-v1 as one possibility (reduce CI stress from "main" codebase by default, while letting more build in forks by default), or build stage support to avoid probably-failing builds if the required part of codebase fails to pass the tests, but …
=> More flexible Travis CI matrix test options: disable failed codepaths by default

.travis.yml, ci_build.sh
Follow-up for #823 : adding more options for building with different compilers, C standards and target platforms (adding MacOS X and Windows potentially, or different CPU architecture builds).
Separated the numerous build cases into "yaml includable" blocks that developers can combine into a job matrix for running their branches - e.g. when someone gets to work on fixing cases that are far in the red now, such as MacOS X or Windows builds that are costly to set up for the Travis infra team and so are a limited resource we should not waste by default in the master branch - not until those cases get fixed by contributors eventually.
=> More flexible Travis CI matrix test options

docs/nut.dict
Small dictionary bump. Not sure why spellcheck test-case in Travis CI did not complain, but workstation builds went haywire.
=> docs/nut.dict: update for conf/upsstats-single.html.sample

.travis.yml, ci_build.sh, configure.ac, docs/developers.txt, docs/nut.dict, include/common.h
This PR follows up from #823 and is part of a larger effort to detect and fix warnings issued by newer compilers and exposing issues in NUT codebase; it just lays the groundwork for subsequent PRs that would propose fixes for different groups of problems (logic, maintainability, overflow, ...) detected.
It also enables optional Travis CI builds for the larger test matrix for branches whose names contain  "fightwarn" (or PRs targeted at branches so named) so that usual builds of NUT and its pull requests would not waste CI resources predictably-in-vain.
Over time as some test cases do become "green" and are moved to not being optional successes, this optional buildability would impact less and less cases, hopefully.
One practical point worth mentioning to the team is the addition of …
=> Fightwarn groundwork

clients/upsc.c, clients/upscmd.c, common/snprintf.c, drivers/blazer_usb.c, drivers/mge-hid.c, drivers/nutdrv_atcl_usb.c, drivers/nutdrv_qx.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usbhid-ups.c, server/upsd.c, tools/nut-scanner/nut-scanner.c
This one I intend to merge with little need for discussion, maybe within a week. Still, review and approval would be warmly appreciated :)
=> Fightwarn fallthrough trivial

drivers/blazer_usb.c, drivers/netxml-ups.c, drivers/nutdrv_qx.c
We had a number of data reads formatted as unsigned ints or hexes, written into signed variables with insufficient range for scanf'ing the potential size of unsigned original number. Commits in this PR aim to work around those situations.
=> Fightwarn - sscanf signed vs unsigned

drivers/asem.c, drivers/pijuice.c
This PR follows up from recently merged #730 that added the PiJuice HAT driver, and #844 effort that hunts for warnings. It fixes several complaints about exceeded data type ranges and/or meaningless comparisons (is an `uint8_t < 0`? is it `> 255`? neither can be, ever...)
Another issue was about `__FUNCTION__` being apparently a hack introduced by GCC, and only later a `__func__` was added into standards and superseded it.
CC @aander07 for review (and possible similar bug-hunts in your other code).
=> Fightwarn - pijuice

drivers/al175.c, drivers/apcsmart.c, drivers/bcmxcp.c, drivers/eaton-pdu-marlin-mib.c, drivers/hidparser.c, drivers/isbmex.c, drivers/libusb.c, drivers/rhino.c, drivers/snmp-ups.c, drivers/solis.c, drivers/solis.h, tools/nut-scanner/scan_xml_http.c
Fixes to various small issues discovered thanks to CI improvements from #844
=> Fightwarn - unclassified fixes

clients/upsmon.c, clients/upssched.c, clients/upsset.c, drivers/liebert-esp2.c, drivers/masterguard.c
This PR adds "reasonable" usage of unused variables discovered thanks to CI improvements from #844
=> Fightwarn - find uses for unused variables

drivers/upscode2.c
* drivers/upscode2.c: comment the fallthrough in upsc_simple() switch, so far consider it explicitly desired as it was before
=> Fightwarn fallthrough questionable - upscode2

drivers/mge-xml.c
* drivers/mge-xml.c: avoid implicit switch fall-through (and comment whether that wondering is the right thing to do though)
=> Fightwarn fallthrough questionable - mge-xml

drivers/main.c
This fixes a buffer overflow crash when NUT drivers are used in dump mode.
=> Fix faulty dump mode logic

configure.ac, drivers/belkin-hid.c, drivers/upscode2.c
A number of maths comparisons for negligibly small values were originally done using `abs()` which is (per warnings from many systems) intended for integers. This PR changes those cases to use `fabs()` from `math.h`.
=> Fightwarn - floating-point abs()

drivers/nutdrv_qx_voltronic.c
drivers/nutdrv_qx_voltronic.c: avoid buffer overflows iterating item->info_rw, possible NPE, and fix the check for hitting the sentinel entry
Fix warnings like:
````
nutdrv_qx_voltronic.c:4037:39: error: division
'sizeof (info_rw_t *) / sizeof (info_rw_t)' does not compute
the number of array elements [-Werror=sizeof-pointer-div]
4037 |  if (i >= (int)(sizeof(item->info_rw) / sizeof(item->info_rw[0]))) {
|                                       ^
nutdrv_qx_voltronic.c: In function 'voltronic_p31g_set':
````
=> Fightwarn - nutdrv_qx_voltronic.c: avoid buffer overflows, possible NPE, and fix the check for hitting the sentinel entry

ci_build.sh, clients/upsclient.c, m4/nut_check_libnetsnmp.m4, m4/nut_check_libnss.m4, server/netssl.c
Another piece for the effort started in #823 / #844, here we explore builds with Mozilla NSS as the SSL implementation and document or fix some hiccups seen along the way.
=> Fightwarn - builds with Mozilla NSS

.travis.yml
This PR follows up from #823 and #844, and enables the results of recently added commits:
* to mark a newly successful test-case as part of required baseline,
* and to actually test on Travis CI both OpenSSL and Mozilla NSS implementations (follows up from #871).
=> Fightwarn - a bit more groundwork

scripts/augeas/gen-nutupsconf-aug.py
scripts/augeas/gen-nutupsconf-aug.py: drop unused variables
Originally PR meant to drop "global" modifier outside a local
function context, but found that nothing defines or uses these
three names. Must be some leftover from planned but unfinished
development.
Re-ran ./autogen.sh and it generates the same file for the build.
Fixes part of LGTM.com suggestions per https://github.com/networkupstools/nut/issues/823#issuecomment-724135948
And replaces PR #881
=> scripts/augeas/gen-nutupsconf-aug.py: drop unused "global" vars

drivers/bcmxcp.c, drivers/pijuice.c, drivers/powercom.c
Fixes part of LGTM.com suggestions per https://github.com/networkupstools/nut/issues/823#issuecomment-724135948
We have a number of cases where either an uint type is tested for (non-)negativity, or a signed int was recently assigned from a function that returns unsigned types (the latter I am reluctant to "fix" as different OSes might return different types and ranges), or was assigned from an element of an array of uint's.
=> Fightwarn - lgtm.com - bogus comparisons

.travis.yml, autogen.sh, ci_build.sh, configure.ac, m4/ax_c_pragmas.m4
Follows up from #823 / #844 efforts. This PR adds tests on FreeBSD, moves tests on Windows a bit forward (though they are still not generating the `configure` script yet), and adds detection of pragma support used by subsequent PRs being prepared.
=> fightwarn - some more groundworks

configure.ac, drivers/libusb.c, drivers/nutdrv_atcl_usb.c, drivers/richcomm_usb.c, drivers/tripplite_usb.c, m4/ax_c_pragmas.m4, m4/nut_compiler_family.m4
Follows up from #823 and #879 in particular.
=> fightwarn - fix diags pragmas to use our configured-support macros for cleaner fencing (unreachable code)

.travis.yml
Follows up from #823 and #897, to clean up test cases now required to succeed for FreeBSD. The two test cases with clang follow suit of other clang test cases, and complain a lot (so are optional and allowed_to_fail), which is the focus of other PRs.
=> fightwarn - fix many freebsd test cases

.gitignore, .travis.yml, common/common.c, drivers/gamatronic.c, include/timehead.h, m4/nut_report_feature.m4
Follows up from #823 and #844 efforts, to add a platform with different CPU type for comparison. A next step here might be `s390x` if it introduces a different (big) endianness also... Still, with routers and Raspberries and so on, an ARM system is quite likely to run NUT so is a practically interesting benchmark.
Early tests have already exposed issue #900 by the way.
=> Fightwarn - Introduce ARM64 builds and some minor fixes

clients/upssched.c, common/common.c, drivers/apcupsd-ups.c, drivers/bestfortress.c, drivers/blazer.c, drivers/dstate.c, drivers/mge-utalk.c, drivers/nutdrv_qx_bestups.c, drivers/nutdrv_qx_blazer-common.c, drivers/nutdrv_qx_mecer.c, drivers/nutdrv_qx_voltronic-qs-hex.c, drivers/nutdrv_qx_voltronic-qs.c, drivers/powerp-txt.c, drivers/serial.c, drivers/tripplite.c, tools/nut-scanner/nutscan-serial.c
Follows up from #823 and #844 to address warnings from clang10 on MacOS builds: NUT extensively uses string variables from tables or calculated at runtime to pass into various likes of `snprintf()` and NUT's own routines with fmt+varargs syntax.
This PR highlights such cases of intentional use of non-literal format strings with pragmas to quiesce GCC and CLANG warnings for this.
The main possible point of PR review is to double-check if these cases (now wrapped in pragmas, sometimes spanning large blocks of code with many `snprintf`s inside) are all intentional and unavoidable. Otherwise, there is little change from previous state of codebase (one avoidable case avoided), so this PR is not likely to break anything :)
=> Fightwarn - macos llvm - nonliteral format strings

drivers/powerman-pdu.c, drivers/powerp-bin.c, drivers/tripplite_usb.c
Follows from efforts at #823 / #844 to squash as many bugs and "fishy coding" warnings found by newest compilers.
This PR is separated from the stream of others since it addresses a common theme - that a few `switch()` cases reacting to values of an `enum` did not cover all options listed in that enum - so something might end up not handled intentionally and just fell through default handling.
In case of `powerp` driver below, such change is trivial - there were two options in enum, so one handled already and other "obviously" same as `default`.
The case of `tripplite_usb` worries me more, since there are 6 options and just a small subset of these were handled initially, to state support of binary or smart protocol, and to control outlets. While the change to spell out the previously not …
=> fightwarn - fix how we work with enums

clients/upsclient.c, clients/upsclient.h, common/common.c, drivers/apcsmart.c, drivers/serial.c, drivers/serial.h, include/common.h
Routines for `read()` and `write()` or `send()` are defined with `ssize_t` wherever I found to look.
Builds on MacOS complained about bitness range mismatch of `int` and `ssize_t` so the chain of calls was modernized here.
Follows up from #823 and #844 efforts.
=> Fightwarn - macos llvm - ssize_t for read()/write()/send()

.travis.yml
Picks up the torch from #901 to bring more tested platforms to CI of NUT.
=> Issue #823 follow-up: add s390x (BigEndian) builds in Travis CI

drivers/powerman-pdu.c
drivers/powerman-pdu.c: query_one() query_all(): do not shadow global varname "pm" with same-named func argument
Changes proposed in this PR concern me a bit more than in others: "I wonder if we should we save the values of function arguments into the global variables for this driver instance?" (and would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs powerman-pdu

drivers/tripplite_usb.c
drivers/tripplite_usb.c: subdriver_match_func(): do not shadow global varname "hd" with func argument "hd"
Changes proposed in this PR concern me a bit more than in others: "I wonder if we should we save the values of function arguments into the global variables for this driver instance?" (and then would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs tripplite-usb

drivers/mge-xml.c
drivers/mge-xml.c: numerous routines: do not shadow global varname "val" (for XML element temp store?) with same-named func argument
Changes proposed in this PR concern me more than in others: what role does the global `val[]` play - is it a scratch buffer, or does it carry pieces of data between routines e.g. during XML parsing?
I wonder if we should we save the values of function arguments into the global variables for this driver instance? (and would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs mgexml

drivers/netxml-ups.c
drivers/netxml-ups.c: send_http_request(): do not shadow global varnames "session" and "uri" with func arguments
Changes proposed in this PR concern me a bit more than in others: "I wonder if we should we save the values of function arguments into the global variables for this driver instance?" (and would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs netxml

drivers/upscode2.c
upscode2.c: upsc_setstatus(): do not shadow global varname "status" with func argument "status"
Changes proposed in this PR concern me a bit more than in others: "should we save the value of function arguments into the global variables for this driver instance?" (and would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs upscode2

drivers/usbhid-ups.c
Changes proposed in this PR concern me a bit more than in others: "should we save the value of function arguments into the global variables for this driver instance?" (and would it play well with several instances running), so additional review and sanity-checking would be very welcome.
=> Fightwarn - lgtm com - hiddenargs usbhid

clients/Makefile.am, clients/nutclient.cpp, clients/nutclient.h, configure.ac, include/str.h, m4/ax_c_pragmas.m4, tests/Makefile.am, tests/cpputest.cpp, tests/example.cpp, tests/nutclienttest.cpp, tests/nutlogtest.c
After a practical fix for #880, at least 50 errors were emitted by clang-9 for the remaining C++ code in this file. Most though not all taste of syntactic sugar, but whatever - if it helps the code be clean and nice.
Follows up from #823 / #844 efforts.
=> fightwarn - nutclient.{h,cpp} : fix an horde of warnings

.travis.yml, ci_build.sh
Picks up the torch from #901 and #911 to bring yet more tested platforms to CI of NUT. It took some effort to set up a 32-bit (i386) environment inside the 64-bit Xenial, in a way that all needed packages are present and linker would not try to mix different-bitness binaries. Probably this ordeal could be solved more cleanly, future improvements are not ruled out. But, this contraption "as is" works and passes the builds.
=> Issue #823 follow-up: add explicitly x86 32-bit builds in Travis CI 

drivers/bcmxcp.c, drivers/dstate.c, drivers/powercom.c, drivers/riello.c, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Follows up from #823, this PR is more of a syntactic sugar regarding "useless no-op statements" represented by a single extra semicolon being the end of empty statement.
Also some ifdef-ed build cases were found where variables introduced due to API were not actually used - those are now not complaining any more.
=> fightwarn - mark up some more NUT_UNUSED_VARIABLEs and drop redundant semicolons

drivers/phoenixcontact_modbus.c, drivers/usbhid-ups.c
Changes proposed in this PR seem relatively straightforward, but additional review and sanity-checking would be welcome.
=> Fightwarn - lgtm com - hiddenargs simple

clients/upsset.c, drivers/dummy-ups.c, drivers/libhid.c, drivers/libshut.c, drivers/snmp-ups.c, drivers/upscode2.c, server/sstate.c
Follows up from #823 effort and earlier work on shadowing arguments.
=> Fightwarn - do not shadow global varname with same-named func argument

drivers/nutdrv_qx.c, drivers/powerp-bin.c, drivers/tripplite_usb.c, drivers/upscode2.c, drivers/usbhid-ups.c, m4/ax_c_pragmas.m4, server/upsd.c
Follows up from #823 effort.
The bug hunt got us into a peculiar situation: we have warnings for NOT handling all enum values, for handling them all and having a `default` case that should not catch anything, and for a switch without default...
Quiesce at least some of that deadlock here.
=> Fightwarn - do not complain for defensive programming with switch defaults

drivers/apcsmart.c, drivers/nutdrv_qx.c, drivers/rhino.c, drivers/solis.c
Follows up from #823 / #844 efforts, this PR avoids initializing variable-length arrays in the code. In most cases it was changed to dynamic `xmalloc/free-before-return` handling. A couple of subsequent fixes for `rhino.c` also got here, which depend on these changes.
In the `solis.c` driver it was just replaced by the macro which (in header) initializes the unmodifiable (right?) typed variable:
````
#define PACKET_SIZE 25
static const int packet_size = PACKET_SIZE;
````
=> fightwarn - avoid variable-length arrays, their support became optional after C99

drivers/bestfortress.c, drivers/mge-xml.c, drivers/tripplite.c, drivers/tripplitesu.c
Follows up from #823 effort.
This PR has potential to somehow change interpretations of numbers in NUT calculations, so careful review is encouraged. Also I hope I did not mix up parenthesis grouping and negations, but it is late night here so everything is possible (caught some of those before posting)...
Would merge after someone LGTMs this :)
=> fightwarn - avoid "bad function cast" by casting explicitly the return value of the function

drivers/bestfortress.c, drivers/blazer.c, drivers/nut-libfreeipmi.c, drivers/powerpanel.c, drivers/rhino.c, drivers/solis.c
Follows up from #823 effort.
This PR adds error-checking for many of the cases, but has potential to somehow change interpretations of values in NUT calculations (especially where unsigned ints are pre-initialized into zeroes which might mean something as a value if actual read from wire was skipped for whatever reason), so careful review is encouraged.
Would prefer to merge after someone LGTMs this :)
=> fightwarn - initialize variables to avoid potential uninitialized use

clients/upsclient.c, server/netssl.c
=> fightwarn - avoid implicit size_t (arch-dependent) vs. PRInt32 (Mozilla NSS) integer conversion

tools/nut-scanner/scan_snmp.c
In libnetsnmp, usmAES128PrivProtocol is a pointer, while usmAESPrivProtocol is an array.
This change is the same as in c7cf507454bcf6f40b24b58e61c130c7772c5bf2.
=> Fix incorrect usmAESPrivProtocol import in nut-scanner

drivers/blazer_usb.c, drivers/nutdrv_qx.c, drivers/usb-common.c, drivers/usbhid-ups.c
Following up with issue #940, this PR adds some debug tracing for device-vs.-driver matching in codepaths I've encountered in practice. A cursory look across the codebase exposed similar logic used in some other drivers, but it is not something I can test quickly now, nor decide if similar change is welcome there too. Anyway, later PRs can be modeled after this one ;)
Also just two drivers were recognized to support the "subdriver" flag, `nutdrv_qx` (only for USB mode) and `blazer_usb` so only their help routines were updated to list the USB subdrivers. Example output:
````
$ ./drivers/nutdrv_qx -h
...
Acceptable values for 'subdriver' via -x or ups.conf in this driver: cypress, phoenix, ippon, krauler, fabula, fuji, sgs
Read The Fine Manual ('man 8 nutdrv_qx')
````
There is also …
=> Help troubleshoot USB driver setups

common/common.c, drivers/al175.c, drivers/bcmxcp.c, drivers/eaton-pdu-marlin-mib.c, drivers/libusb.c
The one in al175 had me puzzled, and seems to be more of a bug in some versions of GCC than in our code. Still, there are ways around it (checking the return for errors) that make sense other than plastering over the potential even if fantastic issues as in many other cases.
A few recent improvements introduced back cases of uninitialized structure members.
And a couple of whitespace cleanups that make code prettier and later PRs more focused on the bugs they solve.
Part of the effort started with #823.
=> fightwarn - a few small warnings and cosmetics

.travis.yml, autogen.sh, ci_build.sh, configure.ac, docs/Makefile.am, docs/developers.txt, docs/man/Makefile.am, docs/nut.dict, m4/nut_arg_with.m4, m4/nut_compiler_family.m4
The options chosen into pre-sets are what we use for Travis CI tests since #823, and revised further for what I used locally for some builds.
This PR adds support for:
* `--enable-Werror(=yes/no)` - make warnings fatal
* `--enable-warnings(=arg)` - enable certain warning presets:
** `gcc-hard`, `clang-hard`, `gcc-minimal`, `clang-minimal`, `all` - actual definitions that are compiler-dependent (the latter just adds `-Wall` which may be relatively portable)
** `hard` or `minimal` - if current compiler is detected as CLANG or GCC, apply corresponding setting from above (or `all` otherwise)
** `gcc` or `clang` - apply the set of options (regardless of detected compiler) with default "difficulty" hard-coded in configure script, to tweak as our codebase becomes cleaner
** `yes`/`auto` - if …
=> Fightwarn - standardize warnings we care about via configure script arguments

drivers/bcmxcp_ser.c, drivers/bcmxcp_ser.h, m4/ax_c_pragmas.m4
Fixes issue #932 (checked on a system with gcc-4.4.4, and on a NUT buildbot that spewed over a hundred new warnings otherwise).
The applied use-case builds on top of, and so includes, data type fixes for baud-rate processing in `bcmxcp_ser.c` also.
=> m4/ax_c_pragmas.m4: separate support inside vs outside function bodies, and fix speed_t in bcmxcp_ser.c

drivers/snmp-ups.c
Instant commands using numeric parameters, like on/off/cycle
commands, were failing due to a bad value submitted type (time
instead of integer)
Cherry-picked from https://github.com/42ity/nut/pull/120
=> snmp-ups: fix instant commands using numeric parameters

drivers/eaton-pdu-marlin-mib.c
Fix a regression that caused a mis-determination of the SNMP base
OID index (0 or 1, should be 1). This in turn caused a mis-iteration
over the outlets, from 0 to N-1 instead of 1 to N, which resulted in
the missing Nth outlet (last outlet of the PDU). This also caused some
data refresh issues
Replay of https://github.com/42ity/nut/pull/124 into main development
=> snmp-ups: fix regression on Eaton ePDU

drivers/apc-ats-mib.c, drivers/baytech-mib.c, drivers/delta_ups-mib.c, drivers/huawei-mib.c, drivers/mge-mib.c, drivers/powerware-mib.c, drivers/raritan-pdu-mib.c, drivers/raritan-px2-mib.c, drivers/xppc-mib.c
Ported from 42ity fork, this PR makes the SNMP MIB helper lookup table names unique across the codebase.
Originally this was required by DMF capability (to load tables by names from XML descriptor files), but now having the same fix in upstream also helps cross-pollination of the fork and upstream repos (more relevant diffs) as they both actively evolve.
Uniqueness verifiable with:
````
$ grep info_lkp_t drivers/*-mib.c | sed 's,^.*info_lkp_t.* \(.*\) =.*$,\1,' | sort | uniq -c | sort -n
````
Note there are some commented-away entries (seen by leading asterisk in the line when just grepping)
=> SNMP MIB subdrivers: rename lookup tables to unique identifiers

ci_build.sh, scripts/upower/95-upower-hid.rules, tests/.gitignore
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
Thanks to Jeff and Arno for bringing up this oversight in CI, missing the need to update the file in source (or perhaps evict it from git and make a dist-only resident).
=> 95-upower-hid.rules script updated for PowerVar USB (catch up to #733)

drivers/Makefile.am
When building the nut drivers with slibtool (https://dev.midipix.org/cross/slibtool) it fails with the same issues in several places.
```
rdlibtool --tag=CC --mode=link gcc -I../include -I/usr/include/libusb-1.0 -g -O2 -Wall -Wsign-compare -Wno-error -o al175 al175.o ../common/libcommon.la ../common/libparseconf.la main.o dstate.o serial.o -lpthread
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/nut/drivers"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 45, .st_ino = 557816}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3.
rdlibtool: lconf: fstat(3,...) = 0 {.st_dev = 45, .st_ino = 557467}.
rdlibtool: lconf: openat(3,"libtool",O_RDONLY,0) = 4. …
```
=> drivers: Fix undefined references with slibtool.

configure.ac
...Then m4 macros we use are not defined, so autotools pastes their lines verbatim and shell syntax is botched. Luckily it has `ifdef` macro just for such cases.
=> configure.ac: avoid syntax errors if pkg-config is not installed

drivers/powercom.c
This fixes a typo in the powercom driver that can cause the output voltage to be calculated incorrectly for some KIN models.
=> Fix a small error in powercom driver output voltage processing

drivers/bestups.c, drivers/blazer.c, drivers/blazer.h, drivers/blazer_ser.c, drivers/blazer_usb.c, tools/nut-usbinfo.pl
Based on a recent discussion due to PR#979, we realized it was not clear for new contributors to NUT where to add support for their new Qx devices. Unfortunately, there is little indication easy to find that some drivers are heading to end-of-life after being superseded by nutdrv_qx, with the UPGRADING document mentioning that for bestups, blazer_ser and blazer_usb.
I suppose @zykh would best explain the current situation with what other older drivers can also be tagged this way (if any), and perhaps which are not ported yet (if any). At the moment I can see drawing a graph of comments "this was copied and 75% adapted from that" so I suppose a majority of *_usb drivers may be siblings, but maybe that is just about the generic skeleton and not actual protocols and logic.
That said, I am …
=> Obsoletion notices in Megatec/Qx legacy driver sources in favor of common nutdrv_qx core and subdrivers

data/driver.list.in, drivers/Makefile.am, drivers/delta_ups-hid.c, drivers/delta_ups-hid.h, drivers/usbhid-ups.c
This PR adds support for Delta UPS Amplon R Serise (https://www.deltapowersolutions.com/en/mcis/1kva-3kva-single-phase-ups-r-series.php)
Tested on R1K and R3K model. 
```
battery.capacity: 100
battery.charge: 100.0
battery.charge.low: 20
battery.charge.warning: 20
battery.runtime: 6496
battery.temperature: 31.9
battery.voltage: 54.1
battery.voltage.nominal: 48
device.mfr: DELTA
device.model: UPS202R2000B0BA
device.serial: [reduced]
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 5
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4-1-gb34f2434
driver.version.data: Delta UPS HID 0.1
driver.version.internal: 0.41
input.frequency: 59.9
input.sensitivity: normal
input.source: normal
input.transfer.high: 280 …
```
=> Add support for Delta UPS Amplon R Series

drivers/tripplite-hid.c, scripts/upower/95-upower-hid.rules
Fix for https://github.com/networkupstools/nut/issues/962
=> Add Tripplite AVR750U (0x3024). Use smart1500lcdt_scale 

drivers/powercom-hid.c
add temperature readings (battery.temperature) support for Powercom MRT-3000
=> add temperature readings for Powercom MRT-3000

drivers/hidparser.c
Reworks the conversion of bytes in little-endian order to host order to
operate independently of the sizeof(long) and the byte-order of the host system.
The extracted value is stored as uint32_t as the code already performs casts
to signed/unsigned of varying sizes as appropriate to the context of use.
Closes issue #1015
=> Extract values in HIDParse correctly when compiled in 64-bit (LP64) mode

docs/man/blazer-common.txt, docs/man/nutdrv_qx.txt, docs/man/tripplite_usb.txt, docs/man/usbhid-ups.txt, drivers/blazer_usb.c, drivers/libusb.c, drivers/nutdrv_qx.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.c, drivers/usb-common.h, drivers/usbhid-ups.c
I needed a `device` argument for USB matching in order to independently match two identical UPSen attached to the same bus.
The changes to usb-common.[hc] and libusb.c are straightforward (sans the `DEBUG_EXACT_MATCH_DEVICE`, which I modelled after `DEBUG_EXACT_MATCH_BUS`, whatever that is used for).
The changes to the various USB drivers are mechanical. Maybe some `#define` for the regex array size (or even seven more `#defines` for the magical index values) would be useful.
I documented the `device` field only where the existing `bus` field was documented (which is not the case everywhere it's actually used).
=> Add USB device number matching

docs/nut-names.txt
Credit goes to Roger Price @NUT-RogerPrice for providing the wording for most of the changes.
https://alioth-lists.debian.net/pipermail/nut-upsdev/2021-May/007553.html
=> docs/nut-names.txt: reword the intro paragraphs and define the "experimental.*" namespace

docs/nut-names.txt
The existing battery.date means the installation or last
replacement date, as it seems to be implemented by various
drivers.
Add an additional battery.date.maintenance for the next
replacement or maintenance date
=> RFC: clarify and complete battery dates

ci_build.sh, configure.ac, tests/cpputest.cpp
For the first shot, this disables their use in build scenarios known to fail for some systemic reasons.
Next shot, if possible, would be to fix these situation (maybe in NUT, maybe in distro):
* FreeBSD with GCC fails to link cppunit based tests; passes okay with CLANG
* OpenIndiana fails with cppunit (segfaults with GCC)
* OpenIndiana fails libgd => CGI detection in configure script when using gcc-4.9 and gcc-4.4.4-il with either bitness; okay in other GCC and CLANG versions
For cppunit, possibly some shared library should be linked; differences of GCC vs CLANG imply some ABI mismatch though? In any case, a more proper solution would be for configure script to detect if it can build and run a trivial test, not for CI systems to set up exclusions.
For libgd and gcc-4.x, more log digging …
=> ci_build.sh: work around handling cppunit and libgd/cgi faults on NUT CI farm agents

Jenkinsfile-dynamatrix, ci_build.sh, configure.ac, tests/cpputest.cpp
Note: code includes #1089 to avoid already addressed CI-farm build errors.
After revising the recipe bundles, it seems plausible that CI was scheduling a number of nearly identical runs with different envvars set - and not even competing values of those. Gotta bome leftover of early experiments with the new dynamatrix, ashes on my old head!
Hopefully this also solves the "strange" builds for "ci_build.sh" method that did not get any "BUILD_TYPE" value set, and so produced unexpected faults beside the extra compute load.
=> Jenkinsfile-dynamatrix: reduce the amount of build combos by careful use of dynamatrixAxesCommonEnv

Jenkinsfile-dynamatrix, ci_build.sh, clients/upsclient.c, server/netssl.c
Our two most expensive build types are distchecks and especially builds with docs. Notably, these are less about code quality and more about recipe quality vs. available non-compiler tools provided on the build workers (make implementation, asciidoc and friends) so we do not need to run them as many times as we have various compiler versions.
This PR aims to reign them in, reducing the redundant builds and those that bring little value for much CPU churn, and revising/documenting what different BUILD_TYPE scenario names do.
At the moment of posting, it does not yet address the calling of (docs-included) builds once per target OS, which is a separate goal that may come later in this or future PR.
Partially helps address https://github.com/networkupstools/jenkins-dynamatrix/issues/4 as …
=> ci_build.sh/Jenkinsfile-dynamatrix: constrain the sprawl of build cases (doc/distcheck)

Jenkinsfile-dynamatrix
... (e.g. no big rebuilds for a docs-only change)
Should address the issue described at https://github.com/networkupstools/jenkins-dynamatrix/issues/5 and solved in the library by supporting the fields we set in this PR, and a way to get the list of files changed by the tested build and process them against the regexes.
=> Jenkinsfile-dynamatrix: find a way to constrain build scenarios not relevant to the changed files

ci_build.sh, include/common.h
* The parenthesized "(label)" in debug macros is a safer expansion than the original "label"
* Avoid the dangling "args..." that may be not-specified by caller (C99 compat)
=> Fix some fallout from PR #685

Jenkinsfile-dynamatrix, ci_build.sh, docs/Makefile.am, docs/nut.dict
Let the first spellcheck attempt be quiet in the log; only redo the work verbosely if that fails.
NOTE: This was originally part of a PR to track which files were spell-checked, so that retry would only double-check and report the failed documents -- improving the UX for developers who would see all the errors concisely. The first shot at that solution worked well, but only in GNU make, so has to be tracked as a separate effort.
=> Use ci_build.sh for CI spellchecks, and check some more docs files

ci_build.sh, configure.ac, m4/nut_check_libnss.m4
On Solaris-legacy systems, NSS is historically delivered to /usr/lib/mps or /usr/lib/mps/(amd)64 and the automated smarts of the system to substitute "lib" to match 32 or 64 bit dependencies as appropriate do not kick in. So for CI (and workstation) builds to test this reliably, we have to tell pkg-config which version of the "nss.pc" to expose depending on bitness we build for. Otherwise it tends to report data from "/usr/lib/pkgconfig/nss.pc" which embeds paths to 32-bit libs, and that breaks for 64-bit builds.
Also, the link checks done in the m4 script did not take into account the bitness of the build (which failed for the non-standard paths pattern detailed above), so now this is explicitly set for gcc-compatible tooling.
=> Extend CI_OS_NAME in ci_build.sh; fix 32/64 pkg-config builds against Mozilla NSS on illumos/Solaris

.gitignore, Makefile.am, ci_build.sh, conf/Makefile.am, configure.ac, data/Makefile.am, docs/Makefile.am, docs/cables/Makefile.am, docs/man/Makefile.am, lib/Makefile.am, scripts/Makefile.am, scripts/augeas/Makefile.am, scripts/ufw/Makefile.am, tools/nut-scanner/Makefile.am
Follows up from #1099 to do implement incremental spellcheck ability and only report the failed files.
Note that for interactive developer use with GNU Make this may come with a cost of some noise (entering/leaving directory for every child make process); this effect is hidden with CI builds however.
=> Makefiles: mark every spellchecked text file with a touch-file to not re-test it again needlessly

drivers/generic_modbus.c, drivers/generic_modbus.h
Follows up from #1052 to clean up compilation warnings.
CC @dtsecon - in original PR I asked whether generic types like "int" should become specific-bitness types to match wire protocol, etc.? If there is something to fix, please base that over this cleaned-up code :)
Also, `ser_parity` is not sanity-checked (at least when received from config); should it be? Any others?
UPDATE: CI likes the change so I'll merge it now; feel free to post further PRs based on NUT master branch.
=> drivers/generic_modbus.{c,h}: fix compilation warnings

.gitignore, Makefile.am, autogen.sh, ci_build.sh, configure.ac, m4/nut_check_python.m4, scripts/Solaris/.gitignore, scripts/Solaris/Makefile.am, scripts/Solaris/precheck.py.in, scripts/augeas/.gitignore, scripts/augeas/Makefile.am, scripts/augeas/gen-nutupsconf-aug.py.in, scripts/python/Makefile.am, scripts/python/app/.gitignore, scripts/python/app/NUT-Monitor.in, scripts/python/module/.gitignore, scripts/python/module/PyNUT.py.in, scripts/python/module/test_nutclient.py.in, tools/.gitignore, tools/Makefile.am, tools/gitlog2changelog.py.in, tools/nut-snmpinfo.py.in
Some distros do not deliver a "python" at all now, going for more explicit "python2" and/or "python3" symlinks to the implementation like `python2.7` or `python-3.9` whichever way they would name it.
Detect one of those 3 basic options from the build operating environment, or use the value specified by caller (in PYTHON envvar for autogen.sh, and proper `--with-python=...` for configure script).
For generalization, this also adds support to explicitly specify a `PYTHON2` and `PYTHON3`, if we (or NUT forks) identify any scripts that are not compatible with the other version.
Respective `HAVE_PYTHON{,2,3}` automake macros can be used in the Makefiles to optionalize certain actions.
Also updates the `PyNUT.py` library to work with both generations of the interpreter (checked by the nearby …
=> Detect $PYTHON versions instead of hardcoding a "python" string

Jenkinsfile-dynamatrix, docs/developers.txt, docs/nut.dict
Do run low-warning GNU89 scenarios even for master, but don't run them with high warning levels even in usual "fightwarn" branch cases (support a separate "fightwarn-c89" to suffer the noise intentionally).
=> Jenkinsfile-dynamatrix + developers.txt: rearrange for GNU89 support

.lgtm.yml, autogen.sh, configure.ac, scripts/systemd/Makefile.am
Follows up from PR #1037 for issue #1030 to let the trick work for distcheck and similar out-of-tree builds.
Also piggy-backs a little cleanup into CI
=> nut-common.tmpfiles.in: fix systemd magic vs autoconf magic

configure.ac, docs/ci-farm-lxc-setup.txt, docs/nut.dict
Recipes:
* do not fail on systems with dysfunctional valgrind (program present but CPU not supported)
* do not complain a lot for C89 builds with "auto" warnings level (mapped to "minimal" for gcc)
=> Small docs/ci-farm-lxc-setup.txt and configure.ac fixes

drivers/apc-mib.c
I started using NUT recently and noticed it does not show the active/apparent power counters my UPS exposes over SNMP, so I added them.
Let me know if this needs any changes (such as naming conventions etc)
My UPS is a `ups.model: Smart-UPS X 1500` from APC
=> Add active power and apparent power from APC MIBs for single-phase UPS

autogen.sh, ci_build.sh, configure.ac, m4/nut_type_socklen_t.m4
With a Git-Bash build environment, I ended up mixing some of:
* Git-Bash SDK at https://github.com/git-for-windows/build-extra/releases/latest
* "Just" Git-Bash at https://gitforwindows.org/
* Python for Windows at https://www.python.org/downloads/windows/
* PERL for Windows at https://strawberryperl.com/
...and fixes from this PR -- and I got the ./ci_build.sh with defaults to generate and pass the `./configure` script.
NOTE: This is a long shot from getting current NUT actually built (more headers differ, more ifdefs may be due, etc.), and MSys/Cygwin/MinGW etc. are a very different environment from making a "native" Windows build. But at least this can help get somebody started.
Caveats:
* The shell-script driven autotools environment is known to be very slow due to lots of …
=> A few recipe improvements for baby-steps on Windows builds

drivers/Makefile.am, drivers/snmp-ups-helpers.c, drivers/snmp-ups.c, drivers/snmp-ups.h
This should help re-usability of the helpers in certain cases
=> Separate source files of snmp-ups.c (driver core) and snmp-ups-helpers.c (shared mapping tables and funcs)

Jenkinsfile-dynamatrix
Matches doc changes in #1121
Currently constrained to branches with `qemu` in the name; later may be part of `master` branch baseline builds. Should figure out from practice which containers should be used with which access methods.
Should also improve performance of usual builds by fixing a typo from early days of the dynamatrix ;)
=> Jenkinsfile-dynamatrix: allow limited use of QEMU containers as build agents (slow workers => few combos)

ci_build.sh, clients/Makefile.am, common/Makefile.am, drivers/Makefile.am, server/Makefile.am, tests/Makefile.am, tools/nut-scanner/Makefile.am
* We had issues (links welcome) with builds of parts of codebase from sub-directories, rather than builds arranged normally from the root directory. Large part of the mess was the absence of dependencies on files (e.g. `*.la` archives) located in other sub-directories, so those were not automatically built when we wanted to e.g. `configure && cd tests && make`. Now such situations should resolve correctly.
=> Fix the web of Makefile cross-references across subdirs

ci_build.sh, docs/developers.txt, tests/getvaluetest.c
...and add a couple of helpers in `ci_build.sh`
Follows up from #823 to fight warnings in NUT codebase, and #1040 / #1055 / #1023 about HID parser fixes.
CC @nbriggs
=> Fightwarn: fix warnings in codebase of recently added `getvaluetest`

ci_build.sh, docs/Makefile.am, docs/man/Makefile.am
One allows to use `ci_build.sh` in a git workspace with random logs, helper scripts, notes, etc. that are neither git-tracked nor git-ignored (avoid choking on `git status -s` returning not empty).
Another allows to `(cd docs && make docs)` regardless of whether they are enabled or not -- helping with PRs like #1152
=> Small fixes for CI and developer workflows

docs/developers.txt, docs/documentation.txt, docs/man/dummy-ups.txt, docs/nut-names.txt
Offenders found with `grep`:
````
$ git grep -E  'link:[^ \[]*( |$)' | egrep -v '\.(svg|ac)'
docs/developers.txt:link:config-prereqs.txt and link:ci-farm-lxc-setup.txt documents.
docs/documentation.txt:or as a pull request against link:https://github.com/networkupstools/nut-ddl
docs/man/dummy-ups.txt:link:https://networkupstools.org/ddl/index.html with files which can be used
docs/nut-names.txt:For more details see examples at link:https://en.wikipedia.org/wiki/ISO_8601
docs/nut-names.txt:and the publicly available RFC at link:http://tools.ietf.org/html/rfc3339
````
=> docs: fix use of "link:" tag in asciidoc (issue #1111)

tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-ip.c
Seems that builds in recent OSes exposed that we manipulated free'd memory to parse CIDR string (indirectly - by saved pointers to sub-string contents behind `cidr_tok`, such as `mask` and `saveptr`), and this no longer "happens to work".
Freeing of `cidr_tok` should happen as late as it is appropriate.
=> Fix nut-scanner subnet/mask handling

clients/Makefile.am, common/Makefile.am, configure.ac, drivers/Makefile.am, server/Makefile.am, tests/Makefile.am, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
If extremely many threads are spawned, e.g. scanning a very large IP address range, the `nut-scanner` program can crash due to resource exhaustion or hitting some constraints in pthreads implementation (various effects were seen on different generations of OSes) or third-party libraries used in particular scanners.
This PR adds a (CLI-configurable as `--thread N`) limit to amount of threads that would be spawned by different parallelized scanners (snmp, nut, netxml, serial), and if the limit gets hit - it would `pthread_tryjoin_np()` to wait for some of the threads to complete their work, and only then proceed to spawn another.
Note that while there is locking to increase or decrease the overall thread counter, checks are not mutex'ed and I anticipate that small accounting errors are …
=> Limit nut-scanner thread count

clients/upscmd.c, clients/upsrw.c, drivers/bcmxcp.c, drivers/gamatronic.c, drivers/mge-hid.c, drivers/nutdrv_qx_masterguard.c, drivers/oneac.c, m4/ax_c_pragmas.m4
Follows up from #823 "fightwarn" effort to revise the warnings about string format truncation (printing from a buffer potentially too large for the destination to hold) and address accordingly:
* increase the destination,
* reduce the limit of copy/print size,
* ignore the warning by pragmas where tested or "assumed" safe (e.g. if "vendor + model" exceed 512*2 chars, we have some other problem), or dictated by protocol layout ("these 16 bytes from the message buffer are...")
=> Fightwarn: string format truncation

drivers/snmp-ups.c, m4/nut_check_libnetsnmp.m4, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_snmp.c
Porting an improvement from 42ITy fork of NUT, to support modern SNMPv3 encryption and auth algorithms.
=> Add new auth methods to SNMPv3

configure.ac, tools/nut-scanner/Makefile.am, tools/nut-scanner/README, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-init.h, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
The 42ITy fork of NUT developed a way to limit parallel nut-scanner thread counts back in 2017. It was not as granular as the solution recently merged to NUT master (which can try to wait for some threads to complete, instead of requiring that each and all earlier launched threads for this scanner type have finished), but it relied on standard semaphores (where available) instead of "naive" integer counters used in the recent PR. Also, it worked for earlier glibc versions where `pthread_tryjoin_np()` was not introduced yet.
=> Improve nut-scanner threadcount limitation with semaphore processing from 42ity fork

clients/Makefile.am, clients/nutclient.cpp, clients/nutclient.h, configure.ac, drivers/Makefile.am, server/Makefile.am, tests/Makefile.am, tests/nutclienttest.cpp, tools/nut-scanner/Makefile.am
During investigation for #1126 it was discovered that some bug lurks in CppUnit which in some of our NUT CI farm build environments causes assertions to fail regardless of argument value. These cases should now be better visible (if some new similar situation arises) by doing some more test cases - so trivial that they should not fail - and it now impacts auto-detection in `configure` script of the ability to run CppUnit tests. Faulty environments would not pollute our CI verdicts anymore :)
=> Fix sanity-checking of the ability to run CppUnit tests

drivers/snmp-ups.c, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
This should satisfy part of issue #1169, about reporting relevant algo names as supported by a particular build of NUT.
=> Make SNMPv3 multiple auth/priv algo support more flexible in usage() messages

Jenkinsfile-dynamatrix, ci_build.sh, clients/upsmon.c, configure.ac, docs/configure.txt, drivers/Makefile.am, drivers/bcmxcp_ser.c, drivers/mge-utalk.c, drivers/nut-ipmi.h, drivers/nut-ipmipsu.c, drivers/nut-libfreeipmi.c, drivers/snmp-ups-helpers.c, drivers/snmp-ups.c, m4/nut_check_libavahi.m4, m4/nut_check_libfreeipmi.m4, m4/nut_check_libgd.m4, m4/nut_check_libmodbus.m4, m4/nut_check_libneon.m4, m4/nut_check_libnetsnmp.m4, m4/nut_check_libnss.m4, m4/nut_check_libopenssl.m4, m4/nut_check_libusb.m4, m4/nut_check_pkgconfig.m4, tools/nut-scanner/scan_snmp.c
There were issues building against old or new FreeIPMI (different types in lib headers), avoiding `valgrind` on agents that say they lack it, and using `pkg-config` regardless of its presence.
Also fixes a few mild warnings found by the newly consulted compiler versions.
=> Fix builds on older platforms

drivers/snmp-ups.c, drivers/snmp-ups.h
While work on original #1147 stalled due to testing against a real daisy-chained setup (signedness changes apparently brought up some issues), other commits from that PR to fix a few warnings were not as "toxic". This one passes reasonably a walk of a real daisy-chain of ePDUs so should be "safe" to merge.
More importantly however, this work brought into spotlight what I think is a bad mess of use of bit-masked values in our flags (and in 42ITy builds, there are collisions of flags defined like `(1<<19)` and `(2<<18)` with different names and meanings, during DMF file generation).
My first reaction was to just spread those values around so they don't even overlap, but several of those definitions just seem bogus so additional points of view would be welcome:
* `(0 << whatever)` remains 0, …
=> Fightwarn: snmp-ups simple half

Jenkinsfile-dynamatrix, ci_build.sh, clients/upsmon.c, configure.ac, docs/configure.txt, drivers/Makefile.am, drivers/bcmxcp_ser.c, drivers/mge-utalk.c, drivers/nut-ipmi.h, drivers/nut-ipmipsu.c, drivers/nut-libfreeipmi.c, drivers/snmp-ups-helpers.c, drivers/snmp-ups.c, m4/ax_c_pragmas.m4, m4/nut_check_libavahi.m4, m4/nut_check_libfreeipmi.m4, m4/nut_check_libgd.m4, m4/nut_check_libmodbus.m4, m4/nut_check_libneon.m4, m4/nut_check_libnetsnmp.m4, m4/nut_check_libnss.m4, m4/nut_check_libopenssl.m4, m4/nut_check_libusb.m4, m4/nut_check_pkgconfig.m4, tools/nut-scanner/scan_snmp.c
Follows up from #1179 with a shot at fixing some warnings reported by `clang-3.4` (compared to no warnings in master branch at easy level until now).
=> Fix builds on old platforms (add-on)

data/driver.list.in
Support for CyberPower RMCARD205 was added in #686 and #793.
This pull request simply adds the card to the Hardware compatibility list
Thank you to everyone involved in making this awesome application
=> Add CyberPower RMCARD205 which is already supported

ci_build.sh, drivers/bcmxcp_ser.c, drivers/bcmxcp_ser.h, drivers/bcmxcp_usb.c, drivers/bestfortress.c, drivers/phoenixcontact_modbus.c, tools/nut-scanner/scan_eaton_serial.c
This PR follows up from #823 and addresses some warnings from LGTM.com analyses that are easy to address.
Some would likely remain reported until we find a way to quiesce the alerts (similar to GCC pragmas that seem ignored by that analyzer), like where we check numeric types and ranges that differ between platforms. A few of these are already (or with this PR) commented as non-issues at least.
Another case that would likely stay until further research is the names of mib2nut mapping tables ("apc" and "mge" are too short for comfy globals).
Also this PR adds some improvements to `ci_build.sh` script trace messages.
=> Fightwarn: short global variable names and other minor alerts from LGTM.com

drivers/snmp-ups-helpers.c, drivers/snmp-ups.c
One is a potential bug (copy-paste typo allowed `strncmp` to look beyond fixed string literal potentially, although just into its ending nul char).
Another is "cosmetic" update to the usage message.
=> Semi-cosmetic fixes to snmp-ups SNMP version processing

common/Makefile.am, configure.ac, docs/config-prereqs.txt, docs/nut.dict
This should complete the fix for #1190 started in PR #1194, addressing a quirk with the `make` implementation on that platform in a way that other systems in CI farm should also be content with.
Buildbot should now be all-green again :)
=> More fixes for builds on older platforms (OpenBSD 6.4)

docs/man/huawei-ups2000.txt, docs/nut.dict, drivers/huawei-ups2000.c
This commit introduces three minor changes after #954 merge.
* Thanks to the user report by @whc2001 in #1066, we finally have a beta tester with a UPS2000-G model with positive result. This commit adds UPS2000-G-3KRTS to the list of tested model in the man page, with slightly updated instructions for submitting new user reports. Two minor typos in the man page are also fixed.
* Currently the driver prevents the user from executing `load.on` when the UPS is already on, and reports a `STAT_INSTCMD_FAILED` with error logs. While executing "load.on" when the UPS is already in "normal-mode on" has no effect, it's still a legal command and should not be rejected arbitrarily, which can potentially confuse downstream applications and users (Update: But we still need to do this if the UPS is in …
=> Huawei UPS2000: Update Man Page, Change Logic for "load.on" command

Jenkinsfile-dynamatrix, configure.ac, m4/ax_c___attribute__.m4, m4/nut_check_headers_windows.m4, m4/nut_check_libnetsnmp.m4, m4/nut_func_getnameinfo_argtypes.m4, m4/nut_type_socklen_t.m4
Avoid failures with default `./configure` run that e.g. enables serial drivers (yes by default) but can't run the compiler to check for headers and so fails.
=> configure.ac: AC_LANG_PUSH before AC_COMPILE_IFELSE and similar tests

docs/configure.txt, m4/nut_check_libgd.m4, m4/nut_check_libnetsnmp.m4, m4/nut_check_libpowerman.m4, m4/nut_check_libusb.m4, m4/nut_check_libwrap.m4, m4/nut_check_pkgconfig.m4
A number of third-party libraries provide their CFLAGS, LIBS and/or LDFLAGS with either `pkg-config` standard files, or with their own `something-config` scripts (which generally are less preferable, especially for multi-arch builds).
We should not assume blindly that a program to call exists in PATH or fail trying to call it, but detect with `AC_CHECK_PROGS` explicitly and go from that knowledge that the program exists. Also this PR augments an ability to `configure --with-something-config=/path/to/something-config` where that was missing, and documents such options.
=> CI/BUILD: avoid directly calling *-config progs from m4 functions

drivers/snmp-ups.c
Messages logged by the driver are not always easily actionable, e.g. to cross-check the device accessibility ("oh, which IP was it?") by other tools like ping or snmp-walk. Now the debug trace should offer better visibility for troubleshooting.
=> Trace snmp-ups MIB-probing better

drivers/huawei-ups2000.c
CC @biergaizi (so split from #1215 and earlier PRs with other similar fixes): Fixing CI warnings for the new huawei-ups2000 driver from PR #1198 and #954 for issue #1017 
````
$ (cd drivers/ && make -k huawei-ups2000.o)
depbase=`echo huawei-ups2000.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/usr/lib/ccache/clang-9 -DHAVE_CONFIG_H -I. -I../include   -I/export/home/jim/nut-DMF/tmp/include -I../include  -I/usr/include/neon   -I/usr/include/modbus -I/export/home/jim/nut-DMF/tmp/include -std=gnu17 -m64 -Wno-unknown-warning-option -D_REENTRANT -ferror-limit=0 -Wall -Wextra -Weverything -Wno-unused-macros -Wno-reserved-id-macro -Wno-padded -Wno-documentation -Wno-cast-qual -pedantic -Wno-float-conversion -Wno-double-promotion -Wno-implicit-float-conversion -Werror -MT huawei-ups2000.o -MD -MP -MF …
```
=> Fightwarn: huawei-ups2000

docs/man/nut-scanner.txt, docs/man/snmp-ups.txt
Apply https://github.com/42ity/nut/pull/160 to list the protocols recently added with PRs #1165 and #1172 (and mention their availability depends on build conditions - libnetsnmp version)
=> Update snmp-ups authproto/privproto docs

drivers/usbhid-ups.c
For some devices, missing instcmds are emulated by calling two
instcmds that do exist in sequence. For some devices, when these
commands arrive too quickly, they are not properly processed. (One,
both, or neither of the commands are acted upon.)
Adding a 1/8th-second delay (125,000 microseconds) between the two
instcmds that make up the fallback command has worked to make the
TrippLite AVR750U (new version with the 3024 productId/protocol)
behave consistently when using the fallback commands (shutdown.return
and shutdown.stayoff). This delay is also short enough that it seems
unlikely to cause a problem for any devices which don't exhibit
this issue.
=> Add a short sleep between fallback instcmds in usbhid-ups.

drivers/hidparser.c
At least one UPS [APC Back-UPS BX1600MI FW:294201G -302201G] is known
to have encoding errors in its USB HID report description such that a
conforming interpretation of the encoded LogicalMaximum value
indicates that it is -1 and the resulting LogicalMin..LogicalMax range
is 0..-1.
The actual report values read are correctly encoded.  Rather than log
a range error each time a value is read we can detect the encoding
error when the report description is read (once, at startup) and
adjust for the encoding error at that time.
Closes #1208
=> Move check for LogMax encoding error to parsing of report description

drivers/blazer_usb.c, drivers/nutdrv_qx.c, drivers/richcomm_usb.c, drivers/riello_usb.c, drivers/usbhid-ups.c, tools/nut-scanner/scan_usb.c
Preparation for merges of libusb-1.0(+0.1) support, to minimize diffs specifically relevant for that change.
=> drivers/*_usb.c: fix whitespace (break long lines)

Jenkinsfile-dynamatrix, ci_build.sh, common/common.c, conf/upsmon.conf.sample.in, configure.ac, docs/developers.txt, docs/nut.dict, drivers/hidparser.c, drivers/hidparser.h, drivers/libhid.c, drivers/libhid.h, drivers/libshut.h, drivers/libusb.h, drivers/usbhid-ups.c, include/nut_stdint.h, m4/ax_c_pragmas.m4, server/upsd.c, tests/Makefile.am
Follows up from #823 for the fightwarn effort, and offloads some changes that would be relevant for libusb-1.0(+0.1) merge to minimize specific diff of that (and/or that were non-specific changes for libusb API variations, that happened to be made while developing those branches).
=> Fightwarn, style and CI recipe revisions

Jenkinsfile-dynamatrix, ci_build.sh, common/common.c, conf/upsmon.conf.sample.in, configure.ac, data/driver.list.in, docs/developers.txt, docs/man/nut-scanner.txt, docs/man/snmp-ups.txt, docs/nut.dict, drivers/blazer_usb.c, drivers/hidparser.c, drivers/hidparser.h, drivers/libhid.c, drivers/libhid.h, drivers/libshut.h, drivers/nut_libusb.h, drivers/nutdrv_qx.c, drivers/richcomm_usb.c, drivers/riello_usb.c, drivers/tripplite-hid.c, drivers/tripplite_usb.c, drivers/usbhid-ups.c, include/nut_stdint.h, m4/ax_c_pragmas.m4, scripts/upower/95-upower-hid.rules, server/upsd.c, tests/Makefile.am, tests/getvaluetest.c, tools/nut-scanner/scan_usb.c
Bringing libusb-1.0 and libusb-1.0+0.1 branches to another level of common baseline, to simplify subsequent PRs for eventual merge of the feature to master for #300.
Note: For finishing touches, https://github.com/networkupstools/nut/tree/fightwarn-libusb-1.0+0.1 will be merged into this target branch next.
=> libusb 1.0+0.1 resync from master as of 2021-12-21

configure.ac, docs/configure.txt, drivers/Makefile.am, drivers/bcmxcp_usb.c, drivers/blazer_usb.c, drivers/libhid.h, drivers/libshut.c, drivers/libshut.h, drivers/libusb1.c, drivers/nut_libusb.h, drivers/nutdrv_atcl_usb.c, drivers/nutdrv_qx.c, drivers/richcomm_usb.c, drivers/riello.h, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.h, drivers/usbhid-ups.c, m4/nut_check_libusb.m4, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/scan_usb.c, tools/nut-usbinfo.pl
Helper "runner-up" commits for PR #1241 (rebasing that changeset over current target branch state, to minimise the noise in log and githubweb diff).
=> Fightwarn libusb 1.0+0.1 rebased part1

docs/ci-farm-lxc-setup.txt, docs/config-prereqs.txt, docs/nut.dict
Documenting a few discoveries about running a CentOS 7 guest container on a Debian 11 host.
For some reason, LXC installer for CentOS 8 did not work...
=> docs/ci-farm-lxc-setup.txt: clarify how to find defined LXC templates and install CentOS on Debian host

clients/upsclient.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_snmp.c
While testing nut-scanner with large subnets and many protocols enabled, I found the output rather messy (some timestamped `[D#]` logs, and some plaintext) so replaced the majority of non-system error reports from unconditional `fprintf(stderr, ...)` to manageable `upsdebugx()` (arbitrarily starting at level 2) in SNMP and IPMI scanners. This allows to optionally not flood the console with info about unresponsive devices.
There is also a bit of impact outside nut-scanner codebase - in the upsclient.c to clarify the messages seen in nut-scanner for "Old NUT" protocol:
````
Error while connecting to X.X.X.X, disconnect
````
changed to
````
Error while connecting to NUT server X.X.X.X, disconnect
````
=> Revise nut-scanner logging

configure.ac, drivers/hidparser.c, drivers/hidparser.h, drivers/libhid.c, drivers/libhid.h, drivers/libshut.c, drivers/libshut.h, drivers/libusb0.c, drivers/libusb1.c, drivers/nut_libusb.h, drivers/nutdrv_atcl_usb.c, drivers/richcomm_usb.c, drivers/riello_ser.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.h, drivers/usbhid-ups.c
This PR updates the libusb-1.0 branch with "fightwarn" considerations (following up from effort in #823 to get the NUT codebase CI-tested and free from more and more classes of warnings, so we can enable non-regression testing for them with future iterations), allowing to proceed with issue #300 to get libusb 1.0 API supported by NUT officially. In fact, this PR would complete the current definition of "medium" level warnings, allowing to set them as default requirement.
One important change here, that was questionable to myself but got "rationalized", is the step back from fixed C-standard fixed-size numeric value types like `size_t`, to `typedef ... usb_ctrl_...` with types defined by respective backend API for libusb-1.0, libusb-0.1, libhid, libshut and some drivers. For statically …
=> Fightwarn with libusb-1.0

configure.ac, drivers/hidparser.c, drivers/hidparser.h, drivers/libhid.c, drivers/libhid.h, drivers/libshut.c, drivers/libshut.h, drivers/libusb0.c, drivers/libusb1.c, drivers/nut_libusb.h, drivers/nutdrv_atcl_usb.c, drivers/richcomm_usb.c, drivers/riello_ser.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.h, drivers/usbhid-ups.c
This PR updates the libusb-1.0+0.1 branch with "fightwarn" considerations (following up from effort in #823 to get the NUT codebase CI-tested and free from more and more classes of warnings, so we can enable non-regression testing for them with future iterations), allowing to proceed with issue #300 to get libusb 1.0 API supported by NUT officially. In fact, this PR would complete the current definition of "medium" level warnings, allowing to set them as default requirement.
One important change here, that was questionable to myself but got "rationalized", is the step back from fixed C-standard fixed-size numeric value types like `size_t`, to `typedef ... usb_ctrl_...` with types defined by respective backend API for libusb-1.0, libusb-0.1, libhid, libshut and some drivers. For statically …
=> Fightwarn libusb 1.0+0.1

ci_build.sh, clients/nutclient.h, clients/nutclientmem.h, common/common.c, configure.ac, docs/config-prereqs.txt, docs/nut.dict, drivers/asem.c, drivers/nut-libfreeipmi.c, drivers/nutdrv_qx.c, drivers/snmp-ups.h, m4/ax_c_pragmas.m4, m4/nut_check_libnetsnmp.m4, m4/nut_compiler_family.m4, tests/cpputest.cpp, tests/example.cpp, tests/nutclienttest.cpp, tools/nut-scanner/nut-scanner.c
Follows up for the "fightwarn effort" per #823 and the raised bar (default warnings sensitivity) with libusb-1.0 support merged in #1255 and a series of PRs before that - to solve most of the issue types that were reported with that level.
=> Fightwarn for medium level

ci_build.sh, m4/nut_compiler_family.m4
Note: similar change applied in jenkins-dynamatrix library for "direct autotools" builds in e.g. `fightwarn` #823 branches.
This should reduce the amount of text printed by default in CI builds, especially when they are successful, reducing the storage consumption and I/O and making human navigation in the log feasible :)
=> ci_build.sh: refactor make-verbosity settings and repeated logic

tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_usb.c
* Report in usage() if "library not detected" (rather than silently omitting possible params for that detector)
* Avoid using a not-opened device via libusb-1.0 - accesses (even closing) can segfault on some builds of the library if the device access is denied and not actually opened
=> Some fixes for nut-scanner

data/driver.list.in, drivers/salicru-hid.c, scripts/upower/95-upower-hid.rules
See also issues #450 and #1142 and #999, PR #1199 and NUT-DDL PR https://github.com/networkupstools/nut-ddl/pull/17
СС @CindyZhan19891207 : can you please check if a build from this branch would detect your UPS "out of the box" as desired?
=> data/driver.list.in and drivers/salicru-hid.c: add known compatibility for Salicru TWIN (PRO2, PRO3, RT3...)

drivers/mge-xml.c
power and realpower for 3ph Lx were not publishing values
when they were 0
=> Eaton NMC: fix the non publication of real/power with 3ph

drivers/snmp-ups.c, tools/nut-scanner/scan_snmp.c
As a fallout of bugfixing for some platforms, we created another bug: now the code checked not for exact complete e.g. "SHA" match, but effectively that the argument starts with "SHA". This PR makes sure we still check the complete string.
=> tools/nut-scanner/scan_snmp.c, drivers/snmp-ups.c: fix match of shorter "SHA" and "AES"

drivers/snmp-ups.c, drivers/snmp-ups.h
This PR follows up from findings of PRs #1147 and #1177, and aims to just redefine the bit-flags used to identify nuances of data points in MIB2NUT mappings.
Given that many value ranges had to move around and expand to avoid overlapping/conflicts (several macros had zero values, a few had different numbers shifted by different offsets to same result, etc.), some defined values were relocated considerably to group them better.
=> Redefine bit-flag map values for snmp-ups.h

configure.ac, drivers/Makefile.am
As  raised in #1017 and detailed in #1271, until now we could request specific drivers to build, but that also required to still specify dependencies involved.
With this PR, requiring a driver would require the corresponding dependencies - same as if `--with-modbus` etc. was specified, unless some other flag for that dependency is requested explicitly.
Also this fixes handling of `--with-linux-i2c=yes` and `--with-macosx-ups=yes` to fail on unsuitable platforms (unable to fulfill explicit requirement), but to not default them to "yes" blindly everywhere (via `--with-all` or `--with-drivers=all`), just on those platforms ("auto" on others to try building anyway but not failing if can't configure such build).
Closes: #1271
=> configure.ac: improve "--with-drivers=name[,name...]" handling [issue #1271]

drivers/riello_ser.c, drivers/riello_usb.c
This should address the issues in #530. Tested with an IDG1600
Output from `upsc` below
```
battery.capacity: 9
battery.voltage: 27.0
battery.voltage.nominal: 24
device.mfr: RPS S.p.a.
device.model: UNV1
device.serial:
device.type: ups
driver.name: riello_usb
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/ttyUSB0
driver.parameter.synchronous: no
driver.version: 2.7.4-4547-gc911e825
driver.version.internal: 0.07
input.bypass.frequency: 409.50
input.bypass.voltage: 4095
input.frequency: 50.10
input.voltage: 240
output.frequency: 50.10
output.frequency.nominal: 50.0
output.L1.current: 0
output.L1.power: 0
output.L1.realpower: 0
output.L2.current: 0
output.L2.power: 0
output.L2.realpower: 0
output.L3.current: 0
output.L3.power: 0
output.L3.realpower: 0
output.power.percent: 0 …
```
=> Update riello (ser, usb) for shutdown/reboot delays (Fixes #530)

docs/man/upsdrvctl.txt, drivers/upsdrvctl.c
Closes: #1036
(Note: that issue discusses other possible improvements around this subject, which are synergetic with this one and posted as separate issues and PRs)
=> drivers/upsdrvctl: add "-d" option to pass current debug level from upsdrvctl to drivers

scripts/systemd/nut-driver@.service.in
Work around default throttling where systemd gives up eventually.
Closes: #799 
See also https://github.com/systemd/systemd/issues/2416
=> scripts/systemd/nut-driver@.service.in: make sure drivers always try to start

clients/upsmon.c, common/common.c, conf/upsd.conf.sample, conf/upsmon.conf.sample.in, docs/man/upsd.conf.txt, docs/man/upsd.txt, docs/man/upsmon.conf.txt, docs/man/upsmon.txt, include/common.h, scripts/systemd/nut-server.service.in, server/conf.c, server/upsd.c
This PR aims to address concerns from issues like #123 and #1299 and optionally allow service daemon lifecycle without a PID file, including sending of signals for `reload` and other operations. 
It adds two ways of addressing the original problems:
* Allow foreground-running mode to create PID file for upsd, by specifying `-F` argument twice (e.g. `upsd -FF`), so that service integrations, init-scripts, etc. that would switch to using a non-forking daemon can still manage it with a PID file
* Allow to specify `-P pidnum` argument on command line of `upsd` and `upsmon` to directly tell it the PID number of the process to signal, instead of reading the value from a PID file. This should play well with systemd units that can pass a `$MAINPID` variable and that is not ambiguous (`upsd`).
As …
=> Enhance ways that upsd/upsmon can send signals to their running siblings

NEWS, conf/ups.conf.sample, docs/man/ups.conf.txt, drivers/dstate.c, drivers/main.c, drivers/snmp-ups.c, server/upsd.c
Closes: #1309
Also
Closes: #1314 (to not snmpwalk an "unitary" device twice)
Some commits picked from #320
While the issue was discovered with snmp-ups driver, the problem after analysis seems to generally impact drivers with many data points, depending on performance and competing workload of the machines running the drivers and data server. I suspect this may be why reports with particularly Raspberry Pi, especially of older revisions, were prominent in the recent years of issue tracking.
=> Introduce `synchronous=auto` as new default value for the driver setting

drivers/libusb0.c
The libusb 0.1 interface definition declares a (signed) char type for
control messages.  The HID descriptor length contained within a control
message is intended to be interpreted as a pair of unsigned bytes so
we must cast to uint8_t when doing the arithmetic rather than trip over
the sign bit.
Closes #1261, closes #1312.
=> Cast to unsigned type when interpreting HID descriptor length bytes (libusb 0.1)

drivers/apc-hid.c, drivers/usbhid-ups.c
Some APC UPSes allow for setting battery.mfr.date, so it can be
easily referenced later, even if there were no stickers or papers
left to refer to.
This patch has been tested to work with APC Back-UPS ES 550G.
Signed-off-by: Nita Vesa <werecatf@outlook.com>
=> APC HID UPS: Add ability to set battery battery.mfr.date

drivers/blazer_usb.c, drivers/libshut.c, drivers/libusb0.c, drivers/libusb1.c, drivers/nutdrv_qx.c, drivers/riello_usb.c, drivers/tripplite_usb.c, tests/getvaluetest.c
As recently found, the chosen approach with conversion to "typedef'ed" support of libusb/libhid/libshut/... codebases and respective APIs, including the buffer-passing that ultimately evaluated to arrays of signed or unsigned chars, had backfired a bit in cases where code did some maths (and bit maths) with individual bytes of those buffers.
As @nbriggs suggested, I went over the codebase looking for files that contain `usb_ctrl_char` string and further for operations in them that matched regex `(>>|<<|[^&~|^][&^|~][= (0-9A-Za-z])` and in fact there were not many places that looked doubtful, PR #1320 caught almost all of them which seemed significant :)
Building and testing in practice with various architectures (32/64-bit, x86, SPARC, ARM...) would be very useful I guess, to be more sure …
=> LibUSB related code - revise for bit-maths with signed char

docs/man/socomec_jbus.txt, drivers/Makefile.am, drivers/socomec_jbus.c
Added a driver for the modbus-based JBUS protocol over serial RS-232 for Socomec UPS. Obviously a modbus sub-driver.
The documentation was found freely on the net but in there it is stated ``This is a product for restricted sales distribution to informed partners. Installation restrictions or additional measures may be needed to prevent disturbances”.
So the legal status is dubious at best.
It only reads UPS status at the moment and has no support for writing UPS variables or sending commands.
Based mostly on the work done for huawei-ups2000 by Yifeng Li.
Most of the read functions appear to work as expected, though it's only been tested with a DIGYS 3/3 15kVA model.
Tested and working on Linux x86-64 and Raspberry-pi3 ARM.
=> Added socomec_jbus implementation

NEWS, UPGRADING, docs/config-prereqs.txt, docs/nut.dict
Just a bit of text
Bump suggested by semver question in #1263
=> NEWS: Docs bump to summarize recent PRs and declare NUT 2.8.0 (instead of 2.7.5) as next release

drivers/belkinunv.c, drivers/riello.c, m4/nut_compiler_family.m4
As tested on Ubuntu impish 21.10, `clang-13` complains about underscores in identifiers, mostly stemming from system headers:
````
libtool: compile:  /usr/lib/ccache/clang -DHAVE_CONFIG_H -I. -I../include -I/home/abuild/nut/tmp/include -I../include -I/home/abuild/nut/tmp/include -Qunused-arguments -fdiagnostics-color=always -Wno-unknown-warning-option -std=gnu99 -ferror-limit=0 -Wno-system-headers -Wall -Wextra -Weverything -Wno-disabled-macro-expansion -Wno-unused-macros -Wno-reserved-id-macro -Wno-padded -Wno-documentation -Wno-cast-qual -pedantic -Wno-float-conversion -Wno-double-promotion -Wno-implicit-float-conversion -Wno-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Werror -MT common.lo -MD -MP -MF .deps/common.Tpo -c common.c  -fPIC -DPIC -o .libs/common.o …
```
=> Clang 13 ready

NEWS, UPGRADING, clients/upsmon.c, docs/net-protocol.txt, scripts/python/module/PyNUT.py.in, server/netcmds.h, server/netuser.c, server/netuser.h, server/upsd.c
CC @NUT-RogerPrice
This PR completes the effort for issue #840 to move away from master/slave terminolgy, now covering also the protocol.
The implementation allows `upsmon` client to request `PRIMARY <ups>` elevation from a server and fall back to requesting a `MASTER <ups>` in case it talks to an older server.
The server (or rather `netcmds` table) in turn handles both keywords, mapping respectively to `net_primary()` and `net_master()` as implementations, which both call a static `do_net_primary()` to weed out error cases like before, and then return `OK PRIMARY-GRANTED` or `OK MASTER-GRANTED` respectively. The server would log callers of the deprecated command, e.g.:
````
3.397427     User upsmon@127.0.0.1 logged into UPS [dummy]
3.397464     [D1] WARNING: Client upsmon@127.0.0.1 …
```
=> [Issue #840] Protocol update for "PRIMARY" command (alias to deprecated "MASTER")

Jenkinsfile-dynamatrix
Try to limit the time a single executor may be occupied by a dynamatrix build scenario. Sometimes Jenkins does not detect factual drops early enough and builds linger for hours without progress - better drop this attempted stage and try it on another agent (or another lifetime of a restarted agent).
=> [CI] Jenkinsfile-dynamatrix: make use of dsbcStageTimeoutSettings

Jenkinsfile-dynamatrix, ci_build.sh, configure.ac, docs/config-prereqs.txt, drivers/libhid.c, m4/ax_c_pragmas.m4, m4/ax_check_compile_flag.m4, m4/nut_check_libgd.m4, m4/nut_compiler_family.m4
Change warning level and fatality to `auto` by default, moving the choice to logic instead of hardcoding in `configure.ac` - e.g. based on gcc version, if detected (versions too old do not support pragmas/options to ignore certain warnings).
Address some issues that precluded gcc-4.2.1 and.or clang-6.0.0 builds on the openbsd-6.4 worker.
=> [CI] Unblock auto builds on openbsd-6.4

NEWS, UPGRADING, configure.ac, docs/config-notes.txt, docs/man/upscmd.txt, docs/man/upsrw.txt, docs/net-protocol.txt
Update the `configure.ac` to report the new version in `netmisc.c`, and update docs that referred to "2.7.5" as the new release to speak about "2.8.0" which sings to similar tune as #1263.
Also documents `PRIMARY` command as alias to `MASTER` (per #840) in protocol 1.3, although the practical implementation is expected to be compatible with protocol 1.2 client/server (see #1328).
CC @NUT-RogerPrice
=> Announce NUT_NETVERSION=1.3

Makefile.am, autogen.sh, ci_build.sh, common/parseconf.c, common/str.c, docs/Makefile.am, docs/config-prereqs.txt, docs/man/Makefile.am, docs/nut.dict, drivers/apcsmart-old.c, drivers/apcsmart.c, drivers/mge-utalk.c, drivers/serial.c, drivers/snmp-ups.c, m4/nut_compiler_family.m4, server/conf.c
Added a chapter about dependencies and tricks for a NetBSD 9.2 builder setup.
Also updated `ci_build.sh` and addressed some issues found with clang-13 builds (tends to use `ctype_inline.h` which uses macros for `isdigit()` etc. and complains when it sees the default `signed` char - for that family of macros the argument is an array offset). There were not too many cases of that, so did not add cumbersome exceptions in `configure` script, went for cumbersome casting in code instead.
=> Doc for netbsd builds, more clang 13 support, more manpage related recipes

drivers/usbhid-ups.c
Probably came with merge of libusb branches per #300 so the same logging line (attributed to same timestamp in `git blame`) happened before and after we check if the reported `hidups_item` is NULL. I suppose the logging "before" is a merge duplicate and okay to drop.
=> Address segfault reported in issue #1346

drivers/usbhid-ups.c
I have a CyberPower CP1300EPFCLCD which in normal conditions reports ACPresent 1 / Charging 0 / Discharging 0 (presumably the battery condition is OK so it has no need to actively charge). This isn't handled by the change recently brought in for onlinedischarge (a8e3687 in usbhid-ups.c, PR #811).
Here's an excerpt from -DDDDDD showing the problem.
```
0.135100     [D2] Path: UPS.Output.DelayBeforeShutdown, Type: Feature, ReportID: 0x15, Offset: 0, Size: 16, Value: -60
0.135103     [D3] Report[buf]: (2 bytes) => 0b 11
0.135104     [D5] PhyMax = 0, PhyMin = 0, LogMax = 1, LogMin = 0
0.135106     [D5] Unit = 00000000, UnitExp = 0
0.135107     [D5] Exponent = 0
0.135109     [D2] Path: UPS.PowerSummary.PresentStatus.ACPresent, Type: Feature, ReportID: 0x0b, Offset: 0, Size: 1, Value: 1 …
```
=> reinstate handling for STATUS(ONLINE) in usbhid-ups

UPGRADING, docs/FAQ.txt, docs/man/bestups.txt, docs/man/blazer-common.txt, docs/man/masterguard.txt, drivers/bestups.c, drivers/blazer.c, drivers/masterguard.c
Seeing quite a few `blazer_ser` and `blazer_usb` mentions in the issue tracker (for varied NUT version TBH), I thought that it would be helpful to point users who copy-paste configurations from older tickets and blogs to try `nutdrv_qx` instead.
I looked for drivers whose source mentions `"Q1"` or `"Q3"` and came up with the ones in this PR:
* bestups
* blazer
* masterguard
There are also some whose protocol I am not sure about, but per "fightwarn" effort they needed similar fixes (at least among themselves) :)
* riello
* bcmxcp
* richcomm
=> Report deprecation messages when starting older Qx drivers

Makefile.am, NEWS, UPGRADING, ci_build.sh, clients/nutclient.h, clients/upssched.c, common/common.c, common/str.c, configure.ac, docs/configure.txt, docs/man/clone.txt, docs/man/dummy-ups.txt, docs/nut-qa.txt, docs/nut.dict, drivers/clone-outlet.c, drivers/clone.c, drivers/dstate.c, drivers/dummy-ups.c, drivers/main.c, include/common.h, include/str.h, scripts/python/Makefile.am, server/sockdebug.c, server/sstate.c, tests/.gitignore, tests/Makefile.am, tests/NIT/Makefile.am, tests/NIT/nit.sh, tests/cpputest-client.cpp
Recent PRs added the "usable PoC" of NIT (NUT Integration Testing suite), which is a portable-shell script to set up the sandbox with a running `upsd` and some dummy-ups instances, and tests them with a few `upsc` queries as well as PyNUT self-test suite (so that code gets regularly covered also).
In some ways it is similar to Ubuntu QART `test-nut.py` (see issue #3) which tests a packaged installation; however NIT should be able to test a recent build iteration right in the source/build tree, as well as a separate (packaged) recent version of NUT with compatible CLI, without impacting system configuration, processes and communication ports/sockets.
This PR refines the script a bit and integrates it with `make check` and `make distcheck` recipes for NUT.
It also adds and calls a simple …
=> Hook NIT into (dist)check targets

.gitignore, Jenkinsfile-dynamatrix, ci_build.sh, docs/man/Makefile.am, docs/man/index.txt, docs/man/nutupsdrv.txt, docs/man/upsd.txt, docs/nut.dict
Also add handling of out-of-tree builds (not distcheck) with `ci_build.sh` by running it from a remote directory or specifying a `CI_BUILDDIR` envvar.
Thanks to @GregTroxel for locating the issue. Fallout from #1372
=> Fix inclusion of `linkman*.txt` files from a builddir

drivers/libusb0.c, drivers/libusb1.c
e.g. no USB devices present (found), or no access permissions to each one device tried (e.g. driver started not as a user specified in udev rules).
Closes: #477
=> drivers/libusb{0,1}.c: report why we could not open any HID devices

drivers/bcmxcp_usb.c, drivers/blazer_usb.c, drivers/nutdrv_qx.c, drivers/richcomm_usb.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.c, drivers/usb-common.h, drivers/usbhid-ups.c
Informative message to help in troubleshooting
Closes: #1368
=> USB-capable drivers: introduce warn_if_bad_usb_port_filename()

data/driver.list.in
case.
(several vendors do use same interface chips for unrelated protocols).
`scripts/upower/95-upower-hid.hwdb` file
file. If the …
=> Hcl updates

drivers/dummy-ups.c
Copy-pasta monster eradicated. We did not have use for nanoseconds here anyway. Still, a dozen other OSes did not complain...
=> drivers/dummy-ups.c: use better portable st_mtime [fallout of #1383, fix #1415]

drivers/main.c, drivers/upsdrvctl.c
See #1423 for context and "screenshots"
The short of it is along these lines:
````
10.017450     Duplicate driver instance detected (PID file /var/run/nut/nutdrv_qx-innotech.pid exists)! Terminating other driver!
15.026749     Duplicate driver instance is still alive (PID file /var/run/nut/nutdrv_qx-innotech.pid exists) after several termination attempts! Killing other driver!
kill: No such process
20.038688     Could not signal the other driver after kill, either its process is finally dead or owned by another user!
````
=> SIGKILL an earlier driver instance if SIGTERM does not cut it [part of #1423 fix]

docs/config-notes.txt
There's no man page for blazer[8]; I think blazer_usb is the intended
one, since all the links in that set are to the USB drivers.
(I was reading https://networkupstools.org/docs/user-manual.chunked/ar01s06.html and that link was broken.)
=> docs/config-notes.txt: Fix link to the blazer_usb manual page

docs/man/usbhid-ups.txt, docs/nut.dict, drivers/usb-common.h, drivers/usbhid-ups.c
The purpose of this evolution is to allow the introduction of a relaxation time, before a reconnection attempt following an error, to allow time for the ups firmware to recover from a possible fail state and avoid it to crash.
A parameter "waitbeforereconnect" is added for this purpose, default value 0, unit seconds.
I spent quite a bit of time, trying first many parameters configuration sets (enlarging pollinterval, pollfreq, MAXAGE) without convincing result, then debugging, to figure out why an **Eaton MGE Ellipse 1500 Max UPS** is able to abruptly cut off the load and go Online Off (OL OFF) for no reason. 
The results of my investigations, carried out on the configuration described below with the ups being always powered by the mains, shows that the observed sequence is the following …
=> Adding waitbeforereconnect parameter to usbhid-ups (default 0 second)

docs/man/huawei-ups2000.txt, docs/nut.dict, drivers/huawei-ups2000.c
We received a report of the existence of a new hardware variant from the bug tracker [1].
This UPS unit has the model number UPS2000-G-3KRTS just like a model we've previously tested, and it has the same V2R1C1SPC50 firmware, which was tested by us as well (although not on UPS2000-G-3KRTS but on UPS2000-A-2KTTS).
However, there are two obvious hardware differences. First, this unit reports itself as "UPS2000G" via the protocol instead, which is a new value not found in the datasheet or previously encountered by us. Previously, even a "UPS2000G" model reports itself as the "UPS2000A". Another difference is the use of WCH CH341 serial-to-USB converter chip instead of the MaxLinear/Exar RX21V1410 chip.
Bus 002 Device 005: ID 1a86:5523 QinHeng Electronics CH341 in serial mode, usb to serial …
=> Huawei UPS2000: support newer UPS2000G/CH341 variants.

docs/man/huawei-ups2000.txt, docs/nut.dict
This commit adds UPS2000-G-1KRTS to the list of tested UPS models. Thanks GitHub user @sumsethan for reporting it [1]. Coincidentally, it also fixes a spellcheck regression in 7bfc617c1f6de1d57fe2c06d1a94a9cd97838497 by adding the developer's name to the dict.
[1] https://github.com/networkupstools/nut/issues/1066#issuecomment-1180005297
=> Fix spellcheck regression & document UPS2000-G-1KRTS.

drivers/huawei-ups2000.c
In Fightwarm fix #1216, several bugs have been fixed, but it also introduced some changes that I perceive as unnecessary hypercorrectionism. For example, it used three type casts when it's only necessary to use just one type cast (as far as I can see, it's the case, but the CI/CD should let us know if the compiler disagrees). This is a minor cleanup Pull Request to remove these changes.
=> huawei-ups2000:  fightwarn hypercorrectionism cleanup

drivers/cps-hid.c
This fix addresses #1338, by adding support for CP1500PFCLCDa (product ID: 601) when applying the report description fix.
=> Fix CPS wrong output voltage

drivers/upscode2.c, server/upsd.c
Thanks to @marekm72 for noticing in #1455 that `str_rtrim()` modifies the original string, but macroization of `upsdebugx()` et al in #685 caused this method to not get called unless debug level is high - so less-than-expected data goes down the datapath.
Not sure if it practically impacted `upsd`, but for the `upscode2` driver this did cause a regression in NUT v2.8.0 release compared to earlier releases.
I went over the codebase to look at other arguments to existing debug calls, with the following grep, and did not notice other similar "offenses":
````
:; git grep -A10 -E 'upsdebug(x|_hex|_ascii|_with_errno)' | (\
H=false; while IFS= read LINE ; do
case "$LINE" in *upsdebug*) H=true ;; esac;
$H && echo "$LINE" ;
case "$LINE" in *");") H=false; echo "---" ;; esac ;
done )| uniq | less …
```
=> Avoid meaningful work in upsdebug*() macro call [#1455]

NEWS, docs/config-prereqs.txt
Initially the committed state of the `NEWS` file contained a lot of planned work for 2.8.1 as catching up with ideas not finished (not urgent) before cutting the NUT v2.8.0 release a few months ago.
As we accumulated (and fixed in master branch) some reports of regressions in that release, it becomes more urgent to cut a bug-fix release soon so the better-functioning code can get into distributions etc. Many of those are still catching up with updating the recipes to provide something after 2.7.4 anyway.
Milestone definitions in Github were updated, although work not completed in practice by whenever we decide that 2.8.1 is ready to roll would move in planning to 2.8.2 just at that point in time (moving of lines in `NEWS` in this PR now may be not final).
=> News update for NUT v2.8.1

tests/NIT/nit.sh
This PR addresses part of issue #1405 to help troubleshoot (and in one situation try to fix) flakiness of the new NUT integration tests.
Empirically, when the NUT CI farm has build storms (e.g. a PR or few have landed, and some got merged, etc.) or the VMs involved are otherwise slow (Fosshost hypervisors overloaded by other projects?), the `make check-NIT` part of the builds tends to randomly fail one or a few times across the build matrix, requiring log investigation by NUT team to make sure the problem was not with contributed codebase.
This is something hard to reproduce otherwise, so the assumption is that the root cause gotta be about timeouts, with ordinarily sub-second operations such as driver start-up, connection to upsd, and responding to queries suddenly taking order(s) of …
=> Fix/troubleshoot NIT on slow systems

NEWS, configure.ac, docs/man/Makefile.am, docs/nut.dict
Regression for custom-builders in NUT 2.8.0 release
Closes: #1467
Thanks: @Kaapeli64 for the finding and suggesting a mostly-correct fix
=> Fix man-page building when just a few drivers are built by name

tests/NIT/nit.sh
On some runs there is still a situation where we try to start `upsd` and it logs some messages; however later the expected PID is not seen running (and can't be killed). These commits aim to help in troubleshooting, as well as improve around a possibly related issue.
One wild guess is that if/when `libtool` wrappers are used, the actually launched PID_UPSD is that of a wrapper script, and maybe that one exits/crashes unexpectedly while the daemon works?
Given how the problem happens on random platforms, there may be something else in play (including an OOM killer where relevant? nothing logged in the build consoles about that...)
=> Some more troubleshooting for `make check-NIT`

drivers/huawei-ups2000.c
Originally, in the struct array `ups2000_cmd[]`, a `REG_NONE` macro was used as a short-hand for a nonexistent register value. Unfortunately it was in conflict with a Windows NT macro of the same name (previously not found because it was only tested on Unix systems). Thus, this commit renames it to `REG_NULL`. To avoid visual confusions with the function pointer field (which also uses C's NULL for its nonexistence), this commit also replaces it with a new macro `FUNC_NULL`, which is a simple alias to C's `NULL`.
It's not exactly the best practice, a `UPS2000_` prefix should've been used in principle. However, using it in this case creates exceedingly long lines and makes the struct array definition more difficult to read, which defeats the very purpose of defining these macros to begin …
=> huawei-ups2000.c: rename NULL macros, close #1474.

server/upsd.c, tests/NIT/nit.sh
Currently every once in a while `upsd` silently does not start in tests - not reproducible well.
Failed case:
````
[INFO] Test UPSD allowed to run without driver configs
fopen /dev/shm/jenkins-nutci/nut_nut_PR-1527@4/tests/NIT/tmp/run/upsd.pid: No such file or directory
Could not find PID file '/dev/shm/jenkins-nutci/nut_nut_PR-1527@4/tests/NIT/tmp/run/upsd.pid' to see if previous upsd instance is already running!
not listening on ::1 port 35057
not listening on 127.0.0.1 port 35057
not listening on localhost port 35057
no listening interface available
Network UPS Tools upsd 2.8.0-210-g7510847
[WARNING] Had to wait a few retries for the UPSD process to appear
[ERROR] upsd was expected to be running although no devices are defined
[INFO] Trying to report users of NUT_PORT=35057
[INFO] UPSD …
```
=> Troubleshoot upsd start for `make check-NIT`: `testcase_upsd_allow_no_device()`

drivers/mge-mib.c
This must be upper case to avoid duplicate discoveries
Closes: IPMPROG-4489
(cherry picked from commit a10f5967154e6c6d2dfa53975de6f874b9966804)
=> Fix case for EATON manufacturer

clients/upsmon.c, clients/upssched.c, common/common.c, common/parseconf.c, include/common.h
Originally proposed as part of #1524 and earlier as a way to isolate Windows-vs-POSIX code.
=> Refactor fcntl(..., FD_CLOEXEC) as set_close_on_exec() where possible

drivers/blazer_usb.c, drivers/libshut.h, drivers/nut_libusb.h, drivers/nutdrv_qx.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usbhid-ups.c
This is about `*_communication_subdriver_s` fields for function pointers named "open" and "close" - renamed to "*_dev" in order to avoid conflict with `serial.h` macros defined for WIN32 builds.
Relatively "noisy" code change originally proposed in #1524
=> drivers/libusb.h, libshut.h, nutdrv_qx et al: rename open/close fields

drivers/adelsystem_cbi.c, drivers/generic_modbus.c
Fix code using less-than-standard type names.
CC @dtsecon - FYI
=> Modbus drivers: fix to use `uint16_t` and `unsigned int`

common/common.c
Part of changes originating in older Windows branch, initially proposed for master in #1524
=> common/common.c: refactor confpath() and dflt_statepath()

scripts/Solaris/Makefile.am
Hot-fixes a problem found and raised in issue #1488
A cleaner fix is desirable (to consider the build target in configure script), but at least there should be less mess on non-Solaris/illumos systems now already.
=> scripts/Solaris/Makefile.am: do not install Solaris init files uninvited

NEWS, configure.ac, scripts/Solaris/Makefile.am, scripts/Solaris/nut-driver.xml.in, scripts/Solaris/nut-server.xml.in, scripts/Solaris/svc-nut-server.in
Closes: #1554
Closes: #1564
Note: while testing on an older OpenIndiana system, could not get the nut-driver manifest to re-import and see the new `start/exec`. Doing `svccfg delete nut-driver; svccfg import /usr/share/nut/solaris-smf/manifest/nut-driver.xml` helped however.
=> Some fixes for Solaris/illumos packaging and SMF support

scripts/python/module/PyNUT.py.in, scripts/python/module/README, tests/NIT/nit.sh
Follow up to #549 (and #746 which dealt with dual py2/py3 compatibility)
=> Fix PyNUT ListClients() and DeviceLogin() for Python 3 string API

docs/man/usbhid-ups.txt, drivers/apc-hid.c, drivers/cps-hid.c, drivers/usbhid-ups.c, drivers/usbhid-ups.h
=> Add a `usbhid-ups` driver option to toggle report descriptor fixup activation

drivers/snmp-ups.c
only walk the number of present alarms, instead of INT_MAX,
to avoid potential blocking
=> snmp-ups: fix alarm processing

INSTALL.nut, Makefile.am, NEWS, appveyor.yml, ci_build.sh, docs/nut.dict, m4/nut_check_python.m4, scripts/Windows/build-mingw-nut.sh, scripts/Windows/dllldd.sh
After the merge of #1580 the Windows-v2.8.0-1 branch is finally sailworthy enough to pass `make check check-NIT` in MSYS2/MinGW build environment (natively on Windows)! And AppVeyor is kind enough to provide Windows builders (among others) to FOSS projects. So what are we waiting for? Let's make the two meet!
Example run log: https://ci.appveyor.com/project/jimklimov/nut/builds/44493334
Closes: #1552
CC:
* #869
* #5 
* #917
UPDATE: As part of the exercise, this also integrates third-party DLL bundling with main Makefile and separate helper script to find them, so addresses a new spin on #1492 as well. Now `make  DESTDIR='/tmp/nut_install' install-win-bundle` is a thing!
UPDATE: Also some python packaging issues were noted...
Closes: #1583
Closes: #1584
=> CI: Set up regular native (MSYS2/MinGW) NUT for Windows builds with AppVeyor

drivers/blazer.c
It allows setting the "idleload" parameter equal to zero
=> Blazer: Accept the value of "idleload" equal to zero

common/common.c
Part of this was merged to master earlier, except the header include; follows up from #1524
=> common/common.c: avoid realpath() on platforms that lack it

Jenkinsfile-dynamatrix, appveyor.yml, ci_build.sh, clients/Makefile.am, clients/nutclient.cpp, clients/nutclient.h, clients/nutclientmem.cpp, common/snprintf.c, docs/config-prereqs.txt, include/timehead.h, m4/nut_check_libnetsnmp.m4, scripts/Windows/build-mingw-nut.sh, scripts/Windows/dllldd.sh, tests/Makefile.am, tests/NIT/Makefile.am, tests/NIT/nit.sh, tools/nut-scanner/Makefile.am
Closes: #1594
UPDATE:
Closes: #1598
Closes: #1603
=> Fix Windows v2.8.0 C++11 and cppunit builds

scripts/python/module/PyNUT.py.in, scripts/python/module/README, scripts/python/module/test_nutclient.py.in, tests/NIT/nit.sh
Closes: #1589
Closes: #1568
These tests did help find a number of cross-platform regressions (including the differences of Py2 vs Py3) but only as long as someone looked at outputs and made sense of them. This PR lets the test script analyze the outcomes (depending on circumstances - e.g. inability to do secure actions while we lack a login is not a real fault; the opposite is, in fact) and so allows automated tests to produce more relevant outcomes without a human poring over the build logs.
=> Revise PyNUT self-test to actually fail

NEWS, docs/nut.dict, drivers/dstate.c, server/sstate.c
Closes: #1626
Currently if a driver claimed "Data stale" and later crashed or was killed, upsd keeps polling its file descriptor and never closes it (because it quickly bails out on the stale device). This precludes later copies of the driver from being recognized and handled by upsd.
=> Be sure to (eventually) disconnect upsd from dead drivers

drivers/usb-common.h, m4/nut_check_libusb.m4, tools/nut-usbinfo.pl
Note: this is currently somewhat hardcoded for MSYS2 packaging of `mingw-w64-x86_64-libusb-win32` so if other environments (32-bit MSYS2, cross-builds on Linux, etc) would be pursued, changes to `m4` scripts here should get refactored for more flexibility.
Currently this allows to build against "modern" (post 2011) releases of libusb-win32, to let someone iterate on making it functional as a variant of libusb-0.1 implementation.
Currently the driver quickly refuses to start:
````
> usbhid-ups.exe -a nutdev1 -DDDDDD
Network UPS Tools - Generic HID driver 0.49 (Windows-v2.8.0-alpha3-754-g7ecd1949d)
USB communication driver (libusb 0.1) 0.43
0.000000     [D1] debug level is '6'
0.001401     [D5] send_to_all: SETINFO device.type "ups"
0.003262     [D2] Initializing an USB-connected UPS with …
```
=> Windows branch: fix builds against libusb-win32

configure.ac, drivers/libusb0.c
Avoid changing the string literal.
Used just for WIN32 libusb-0.1(-compat) builds at the moment.
=> configure.ac, drivers/libusb0.c: fix detection of strlwr() and fallback strcasestr() implem

configure.ac, drivers/libusb0.c, m4/nut_check_libusb.m4
Not really sure if this would help (checking) but the Windows branch was originally developed before libusb-1.0 effort started, so tweaks to code applied to what is now `libusb0.c` should be more successful.
In limited dev-testing so far, builds with plain libusb-1.0 and with it wrapped as libusb-0.1-compat (mis-)behave in a similar manner, claiming I/O errors with interrupt processing mode, and nearly no data collected with polling mode. Maybe snatching the device from "kernel" should be done differently (Windows does represent the "USB HID Battery" and probably holds the critical resources).
Have yet to try with original libusb-win32 project the branch was built against.
=> m4/nut_check_libusb.m4: when on Windows, prefer libusb-0.1 [#1507]

drivers/usbhid-ups.c
Closes: #1627
Partially touches on #1295
Follows up from #1335
=> usbhid-ups: do not crash due to auto-reconnecting

clients/upslog.c
Messages to stderr are unreliable when output to the console and
mesg is n (0600). For example, the following will disallow console
output to UID uucp.
is n
is n
crw-------  1 root  wheel   0x7 Aug 29 14:03 /dev/console
crw-------  1 root  wheel  0x46 Aug 29 12:32 /dev/ttyv0
case.
(notably `blazer` and other single-device family drivers for Qx …
=> upslog: Messages should go to syslog

NEWS, clients/upslog.c, docs/man/upslog.txt
upslog is a utility that logs UPS status at regular intervals, specified
by the -i option. Unfortunately upslog supports only one UPS. For sites
that need to monitor multiple UPSs the options are to cobble an rc script
for each or doctor up the nut_upslog.in script to support cloning of the
script. Unfortunately an rc script capable of being cloned would become
the source of more PRs and would require significanly more tehcnical
documentation that by itself might become confusing for the average
system administrator.
Therefore a new -m option is added to support multiple UPSs using the
same invocation of upslog. The patch parses a -m option, polling each
ups listed.
compatible and actually tested/developed against), …
=> upslog: Add support for multiple UPSs

NEWS, UPGRADING, clients/Makefile.am, clients/upsclient.h, include/Makefile.am, include/parseconf.h, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scan.h
Pull in system-provided headers for int types (`uint16_t`, `size_t`, `ssize_t` etc.), as well as `useconds_t` and the `time_t` as required by NUT API since 2.8.0 release, so the delivered headers are instantly usable (at least, with build systems which declare `HAVE_SOMETHING_H` like GNU autotools do).
Follows up from #1615/#1616 and should address #1638
=> Further revise NUT public API headers

clients/upslog.c, common/Makefile.am, common/strsep.c, configure.ac, include/Makefile.am, include/str.h
GitHub WebUI driven merge had some accidents, and PR #1639 introduced use of `strsep()` which is missing in MSYS2/MinGW.
=> Revisit NUT for Windows v2.8.0 branch after upslog update

docs/ci-farm-lxc-setup.txt, docs/config-prereqs.txt, docs/nut.dict
Part of investigation for #1279 - needed a platform to reproduce user build failure. That is tangentially related to #1650 (also exposes `strptime` issues).
=> Document LXC setup for NUT builds with Arch Linux

configure.ac
This should help find strptime() in particular on systems that have both time.h and sys/time.h files, and one does not include the other (e.g. Arch Linux as seen in #1279 testing).
Arguably a regression with Windows branch merge that introduced the fallback code and need to check for its presence in the OS.
=> configure.ac: move detection of TIME_WITH_SYS_TIME to before we use it

ci_build.sh, docs/Makefile.am, docs/man/Makefile.am, indent.sh, scripts/subdriver/gen-snmp-subdriver.sh, scripts/subdriver/gen-usbhid-subdriver.sh, scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in, tools/nut-scanner/scan_snmp.c
Coding style primarily. Hoping no OS on horizon is too old to *lack* `grep -E`
=> Replace "egrep" by "grep -E" in shell code - modern systems frown upon the former

docs/man/upscode2.txt, docs/nut.dict, drivers/blazer.c, drivers/eaton-pdu-pulizzi-mib.c, drivers/snmp-ups.c
Online dictionaries suggest that both single-S and double-S versions are correct. But it is messy seeing both on the same page. There can be only one! (Or two in this case)
=> Spell Guesstimation consistently

NEWS, clients/upsclient.c, docs/man/upscli_init.txt, tests/NIT/nit.sh
Follows up from discussion for PR #1662
=> Support NUT_QUIET_INIT_SSL envvar to hide "Init SSL without certificate database" message

AUTHORS, data/driver.list.in, docs/man/snmp-ups.txt, docs/nut.dict
The Eaton Gigabit Network Card (Network-M2) is already well-supported by the powerware driver. This patch updates the documentation to reflect this.
(Replaces #1676.)
=> Documentation update regarding Network-M2 card

drivers/snmp-ups.c
Fix walk issue with snmpv3 by adding the treatment of type error exception in loop reading.
=> Fix walk issue with snmpv3 (** add type error exception **)

NEWS, common/common.c, docs/nut.dict, tests/NIT/nit.sh
We lacked log information about changes of chroot jail (uncommon) and uid/gid (everywhere), which makes troubleshooting harder (e.g. lack of access to config files or USB device nodes). Now we have it :)
This PR also enhances `make check-NIT` for builds done as `root` (relaxes permissions to generated test config files, so de-levated `nobody` can read them), so their default `make check` passes.
=> Debug chroot and setuid

docs/config-prereqs.txt, scripts/Windows/README
Not sure why it is not packaged by MSYS2, but at least checked we can build it (and against it) okay... Mostly resolves what remained of #1475
TODO: Automate in AppVeyor builds?.. #1491?
=> Document builds with net-snmp in MSYS2 MinGW (Windows) [#1475]

appveyor.yml, scripts/Windows/README, scripts/Windows/build-mingw-prereqs.sh
Addresses #1475 to distribute more relevant CI-built snapshots of NUT for Windows (made on Appveyor).
Unlike linux+mingw, the MSYS2+mingw builds still fare without augeas, ipmi, avahi... but the snmp-ups is a much more commonly useful feature.
See also #1491 for which this might be a good beginning...
=> CI: Build missing prerequisites for NUT for Windows

NEWS, data/driver.list.in, docs/nut.dict, drivers/Makefile.am, drivers/hpe-pdu3-cis-mib.c, drivers/hpe-pdu3-cis-mib.h, drivers/snmp-ups.c
This support is unitary (no daisychain support yet). Also note that, due to SNMP v1 implementation limitations on this device, you should prefer SNMP v3 to get both read and write rights
=> snmp-ups: add support for HPE G2 Metered & Switched PDU

NEWS, UPGRADING, docs/man/snmp-ups.txt, docs/nut.dict, drivers/Makefile.am, drivers/eaton-ups-pwnm2-mib.c, drivers/eaton-ups-pwnm2-mib.h, drivers/eaton-ups-pxg-mib.c, drivers/eaton-ups-pxg-mib.h, drivers/snmp-ups.c
To better manage the slight nuances (especially in ups.status), between Eaton UPSs, implementation file was split in 2 files, and mib name were renamed from 'pw' to 'eaton_pw_nm2', and from 'pxgx_ups' to 'eaton_pxg_ups'
Thanks to Quentin Renard (Eaton) for discovering the bug
=> snmp-ups: split Eaton pw and pxgx_ups implementation

NEWS, drivers/snmp-ups.c
Fix that long standing issue, which was tied to non-existent OIDs, not well handled in some part of the driver
Closes: #743
=> snmp-ups: fix "Warning: excessive poll failures"

m4/ax_c___attribute__.m4, m4/ax_c_pragmas.m4
Future C compilers will likely default to language modes which do not support implicit function declarations. Rebuilding nut with an [instrumented compiler](https://fedoraproject.org/wiki/Toolchain/PortingToModernC#Discovering_Packages_Which_Need_Fixing) revealed a few issues in the configure script.
=> C99 fixes for the configure script

clients/upsmon.c, common/common.c, conf/ups.conf.sample, conf/upsd.users.sample, conf/upsmon.conf.sample.in, configure.ac, docs/FAQ.txt, docs/config-notes.txt, docs/man/upsd.txt, scripts/systemd/nut-server.service.in, server/upsd.c
Follow-up from #1721 discussions, mostly to clarify docs and messages to be more actionable with regard to changes in NUT 2.8.0 and systemd unit wrapping (e.g. that by default it starts `upsd -F` and so does not save PID files).
Also clarifies some example texts to be more consistent between files (e.g. NUT user for upsmon).
=> Suggest in docs and daemon messages how command-signals vs. PID files vs. systemd units interact

drivers/eaton-pdu-nlogic-mib.c
Use generic name in mib2 instead of the real device name in eaton mib.
=> Fix discovery issue with Eaton pdu nlogic

ci_build.sh, tests/NIT/nit.sh
Recent builds were very slow. Found ccache was not used in some scenarios, and upsd did not always respond to NIT in time (VM swapping).
=> Speed bump for laggy CI

tools/gitlog2changelog.py.in
Older python-2.7 environments have no problem generating the changelog. Newer ones with recent 3.x seemingly too. However on systems with python-3.6 it fails with utf-8 content and default ascii decoder. According to https://discuss.python.org/t/pep-597-use-utf-8-for-default-text-file-encoding/1819/1 the defaults may be fixed from 3.7 onward.
This PR was tested against 2.7 and 3.6 (on openbsd) to open git process and output file in ways that the program does not crash, and generates reasonable output (the files produced do differ due to line-wrapping method evolution). Earlier this disability precluded running `make dist(check)` on the platform.
It also newly avoids prefixing entries with filename lists which duplicate filenames listed in the start of commit message (if any), as long as …
=> Update gitlog2changelog for python-3.6

tools/nut-scanner/nutscan-init.c
Closes: #1735
Note: libnetsnmp is not bundled in mingw, but can be built additionally as documented in NUT sources - and automated for Appveyor CI builds.
=> nutscan-init.c: adjust WIN32 shared library detection for SNMP and NEON

drivers/Makefile.am, drivers/bcmxcp.h, drivers/blazer_usb.c, drivers/nutdrv_atcl_usb.c, drivers/nutdrv_qx.c, drivers/richcomm_usb.c, drivers/riello_usb.c
Should fix #1754 and #1744 among other issues. Thanks to @shgubar for convincing me that the bug is there, and to trace the code with more attention.
Note: "bcmxcp_usb" driver suffers a similar problem but was not easy to fix in a similar fashion (conflicts with symbols in the built `LIBUSB_IMPL` of the day, and impacts nut-scanner build per different dependency chain), so attempt to fix it along with others was shelved.
A side note from debugging: the regex-matching in usb-common.c is not logged in full detail because array elements are not interactively useful (precompiled regexes, not original strings).
=> Fix common USB matching options for riello, richcomm and nutdrv_atcl

NEWS, docs/man/Makefile.am, docs/man/bcmxcp_usb.txt, docs/man/blazer-common.txt, docs/man/nut_usb_addvars.txt, docs/man/nutdrv_atcl_usb.txt, docs/man/nutdrv_qx.txt, docs/man/richcomm_usb.txt, docs/man/riello_usb.txt, docs/man/tripplite_usb.txt, docs/man/usbhid-ups.txt, docs/nut.dict, drivers/Makefile.am, drivers/nutdrv_atcl_usb.c, drivers/richcomm_usb.c
Refactored docs to include same description file, and combined different pieces of knowledge into it.
Follows up from #1763 (and adds a comment for #1764 in the text).
=> Update USB matching options in man pages

drivers/nutdrv_qx_masterguard.c
Add `experimental.` prefix in `masterguard_claim()`. Needed because that prefix had been added (in 7ef2874e81952fac532014a8840a217cf1d636b6 to the variable names in the `masterguard_qx2nut[]` table.
=> Add experimental prefix missed in 7ef2874e81

NEWS, docs/man/nut_usb_addvars.txt, drivers/libusb0.c, drivers/libusb1.c, drivers/usb-common.c
Closes: #1756 
Initially also addressed #1767 (seen in "screenshots" below) but that change was offloaded to PR #1771
Also does minor codebase maintenance, and partially follows up from recent work in PRs:
* #1766
* #1763
May help in situations raised in issues such as:
* #1744
* #1754 
* #1414
* #1273
* #1174
Note that use of USB device matching by a unique combination of fields is much more preferable to `allow_duplicates` (if possible).
-------
Example with use of the new feature (while the driver is running as another process):
````
Network UPS Tools - Generic HID driver 0.49 (2.8.0-Windows-299-g5e8e40cca)
USB communication driver (libusb 1.0) 0.43
0.000000     [D3] main_arg: var='driver' val='usbhid-ups'
0.000015     [D3] main_arg: var='port' val='auto'
0.000022     [D5] send_to_all: …
```
=> Introduce an `allow_duplicates` flag for common USB matching options

drivers/libusb1.c
During USB enumeration, set `curDevice->Device`.
Try to use _libusb1_'s port number obtained by `libusb_get_port_number()`, but that seems useless at least on NetBSD. So, use `devnum` (the enumeration loop variable), which at least makes two identically looking USB UPSen distinguishable again.
Maybe we want to add a `Port` property set to what `libusb_get_port_number()` reports?
Previously missed during refactoring to libusb1.
=> Set curDevice->Device during USB enumeration

drivers/huawei-ups2000.c
Currently, failures in `modbus_read_registers()` or `modbus_write_registers()` do not show any error code or message in the log, making it difficult to debug. This commit logs the error code, errno, and `modbus_strerror()` if an error occurs. Furthermore, the log level of a fatal warning has been changed from `LOG_WARNING` to `LOG_ERR` (`LOG_WARNING` was previously used due to an oversight).
=> huawei-ups2000.c: log error code/string for Modbus failures

NEWS, clients/upsclient.h, clients/upsmon.c, clients/upsmon.h, conf/upsmon.conf.sample.in, docs/man/upsmon.conf.txt, docs/man/upsmon.txt, docs/nut.dict
Closes: #506
````
Jan 07 22:49:50 pve nut-monitor[4103053]:   97.199079        Reloading configuration
Jan 07 22:49:50 pve nut-monitor[4103053]:   97.199178        Applying debug_min=2 from upsmon.conf
...
Jan 07 22:50:26 pve nut-monitor[4106871]:    0.001183        [D1] Trying to connect to UPS [eco650]
Jan 07 22:50:26 pve nut-monitor[4106871]:    0.001410        [D1] Logged into UPS eco650
Jan 07 22:50:26 pve nut-monitor[4106871]:    0.001440        [D2] pollups: eco650
Jan 07 22:50:26 pve nut-monitor[4106871]:    0.001472        Poll UPS [eco650] failure state code changed from -1 to 39; report below will only be repeated to syslog every 5 polling loop cycles:
Jan 07 22:50:26 pve nut-monitor[4106871]:    0.001476        Poll UPS [eco650] failed - Driver not connected
Jan 07 22:50:26 …
```
=> upsmon: Introduce POLLFAIL_LOG_THROTTLE_MAX

docs/man/bestfcom.txt, docs/man/bestfortress.txt, docs/man/bestups.txt, docs/man/upsdrvctl.txt, docs/man/upsmon.txt
This PR has three documentation changes:
* Clarify Best driver support for the LI660, as it seemed like newer drivers should be used
* Explain `upsdrvctl shutdown` better
* Explain that `upsmon` will remove `POWERDOWNFLAG` on startup
=> Documentation improvements

NEWS, docs/nut-names.txt, docs/nut.dict, drivers/adelsystem_cbi.c, drivers/bcmxcp_usb.c, drivers/blazer_usb.c, drivers/generic_modbus.c, drivers/main.c, drivers/nutdrv_qx.c, drivers/powerman-pdu.c, drivers/richcomm_usb.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usbhid-ups.c
Closes: #1767
Closes: #1388
Split off from PR #1770 as a separate feature, and at that - one for NUT community to agree upon (new standard nut-names entry).
This change allows drivers to uniformly report (to NUT clients as well as a dstate entry that can be internally consulted by driver logic) whether they are at this moment initializing, reconnecting, updating info from the device, or just being quiet between work bursts.
=> Introduce `driver.state` tracking

NEWS, ci_build.sh, drivers/libusb0.c, drivers/libusb1.c, tools/nut-scanner/scan_usb.c
Closes: #1790
Currently nut-scanner did not report a `device` value (should mean physical port number on a hub, where supported and not much guaranteed), so systems connected to two UPSes from same vendor could not discern between them (especially if handled by same USB bus, and lacking a serial number).
Many USB drivers use the common routine (more after #1763 was merged) which checks for `device = NNN` if provided.
For that matter, the common matcher also reports (and considers internally) the "bcdDevice" (version) although does not match it from user-provided configuration. FWIW this change prints that value out, commented.
Example output after the change:
````
:; ./tools/nut-scanner/nut-scanner -U
Scanning USB bus.
[nutdev1]
driver = "usbhid-ups"
port = "auto"
vendorid = "0463" …
```
=> nut-scanner: report same USB matching values as seeked by libusb{0,1}.c

configure.ac, docs/configure.txt, m4/nut_check_python.m4, m4/nut_report_feature.m4
=> Document configure options regarding Python (module, app)

autogen.sh, configure.ac, docs/config-prereqs.txt, docs/nut.dict, m4/ax_check_compile_flag.m4
A question on mailing list was raised about testing NUT for someone still running CentOS 6, so here goes... spoils of experimental reconnaissance:
"Surprisingly, it works!" (mostly regarding feature/dependency availability)
With container setup as documented in this PR and downshift to allow autoconf-2.63 (also in the PR), `./ci_build.sh` built and successfully NIT-tested the codebase (without C++11 support due to old GCC-4.4.x; clang-3.4.x refuses to use system-provided C++ headers). 
Although the older `python2.6` is the only one available on the system, `PyNUT` successfully participated in the test; the NUT-Monitor GUI was not tried (headless system).
Java 11 was not available for the platform, so for the time being it can not directly run a Jenkins agent and will not be part of …
=> Revisit NUT CI build on CentOS 6

NEWS, docs/man/upsdrvctl.txt, drivers/upsdrvctl.c
Closes: #1759
Note: this idea does not apply to `upsdrvsvcctl` script which manages service instances with whatever configuration they have. Internally the service units may be calling `upsdrvctl` however, as implementation detail.
=> upsdrvctl.c: add "-F"/"-B" args for drivers to be fore/back-grounded explicitly

tests/NIT/nit.sh, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_nut.c
While the test is rudimentary, it allows to check that `nut-scanner` tool basically works, and the C client library talks to upsd well. In practice during tests in build tree it often depends a lot on libtool wrapper preparing the environment that allows (or not) to find the library at run-time search, so the tests are skipped (not failed) when it says the library could not be found.
Also addresses a poorly-understood message on console when "NewNUT" (avahi) discovery fails.
Note: initially hoped this would be a test for sanity-checker from #1811, with dummy-ups configs providing some bogus or duplicate data, but NUT discovery only reports the client/relay connection point, not further details of the already running driver's config or data.
Closes: #1815
=> CI: add NIT tests for nut-scanner/libupsclient

scripts/python/app/nut-monitor.appdata.xml
Inspired by https://salsa.debian.org/debian/nut/-/blob/a009ca10a327d7db383f5d7726091050ceb4d60f/debian/patches/appdata-launchable.patch from @bigon but adjusted for general version-agnostic dispatcher (py2 or py3, whatever is installed for this end-user deployment)
=> nut-monitor.appdata.xml: add launchable=nut-monitor.desktop

NEWS, drivers/bestfortress.c
This PR does two main things:
- rationalize and improve logging, and add/update comments
- improve shutdown process, fixing a serious bug where the intended 10s delay was not honored, resulting in a way-too-short 1s delay.  Bump driver version because of this.  Fixes #1817.
I have tested a functionally equivalent earlier version on a Fortress LI660 including `upsmom -c fsd`, and this version with `-D -D -D -D -D`.
Changes are entirely in `drivers/bestfortress.c`; interfaces are not changed.
Things that I think can be done later (not in this PR):
- More substantial comment improvements, including about the protocol.
- Enable setting more parameters (there are 10).
- Enable setting the shutdown delay (internal to driver; not a UPS parameter).
- More logging rototilling.
- Reorder functions …
=> Improve Best Fortress driver

configure.ac, drivers/main.c
Issues noted during discussion of [#1848](https://github.com/networkupstools/nut/pull/1848#issuecomment-1427692141)
=> Fixes for unreadable "inplace" sysconfdir, and exclusive '-a id'/'-s id' for drivers

drivers/tripplite-hid.c, scripts/upower/95-upower-hid.hwdb
took inspiration from https://github.com/networkupstools/nut/issues/555
associated issue: https://github.com/networkupstools/nut/issues/1849
case.
VID/PID combinations, or raised discussions when this …
=> add support for minuteman device PRO1500RT2U (a0a0)

common/common.c, configure.ac, m4/nut_compiler_family.m4, m4/nut_report_feature.m4
Examples:
* No `configure` options at all:
````
:; ./autogen.sh && ./configure && make -j 8
:; ./server/upsd -DV
Network UPS Tools upsd 2.8.0-Windows-565-g2e973e674
Network UPS Tools version 2.8.0-Windows-565-g2e973e674 (release/snapshot of 2.8.0.1) built with gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 and configured all by default guesswork
````
* With options (provided by `ci_build.sh` helper scenario):
````
:; rm -f Makefile configure include/nut_version.h; CC=clang CXX=clang++ ./ci_build.sh
:; ./server/upsd -DV
Network UPS Tools upsd 2.8.0-Windows-566-g55a5dca9f
Network UPS Tools version 2.8.0-Windows-566-g55a5dca9f (release/snapshot of 2.8.0.1) built with clang version 10.0.0-4ubuntu1; Target: x86_64-pc-linux-gnu; Thread model: posix and configured with flags: --enable-Wcolor …
```
=> Debug `nut_report_config_flags()`: report version from AC_INIT vs. Git revision (if available) and compiler version

clients/nutclient.cpp, clients/nutclient.h, configure.ac
Older GCC-4.7.2 (in Debian 7 Wheezy, per #1883 discussion) claims to support the language version we need, but in fact has numerous missing features that a build hits (the whole 4.x line added C++11 support step by step, one minor release after another). This PR fixes a warning that seems useful (about `noexcept` in destructors) -- CI will show if newer systems have a problem with that change.
Primarily this PR extends the `configure.ac` check to bail out on some infractions easier to test (lack of `std::map -> emplace()` for example).
NOTE: A few earlier documentation changes went to master branch without a PR, to follow up on setup of the Debian 7 LXC container, etc.
=> C++11 support tighter check

.gitignore, Makefile.am, autogen.sh, configure.ac
* Allow bumping debugging modes for tools called by `autogen.sh`.
* Address m4 `ifdef` support/portability for optional handling of automake silent rules (checked that now an unmodified `configure.ac` works both with older Debian 7 tooling that complained about "too many" parameters by default, and with newer tooling that complained about "excess" parameters if earlier script code was adapted to work for older platforms).
* Implement `AM_PROG_AR` support as suggested by `autoreconf` warnings - checked to make Windows builds quieter (no more warnings about the libraries and their related tooling).
Follows-up: #1821
Follows-up: #1885
Follows-up: #1883 discussion
=> Allow verbose autogen.sh; improve build recipe portability

NEWS, docs/FAQ.txt, docs/nut.dict, scripts/usb_resetter/README.md, scripts/usb_resetter/nut-driver.service
This PR adds documentation for a workaround solution for unreliable USB interfaces, as stated in #1688 
I use this on a couple of UPS for months now, without any major issue.
- [N/A] Updated `docs/acknowledgements.txt` (for vendor-backed device support)
- [N/A] Added or updated manual page information in `docs/man/*.txt` files
and corresponding recipe lists in `docs/man/Makefile.am` for new pages
- [N/A] Passed `make …
=> Add usb_resetter documentation for unreliable USB UPS interfaces (Linux, Python)

NEWS, common/common.c, configure.ac, drivers/main.c, drivers/main.h, scripts/Solaris/nut-driver.xml.in, scripts/systemd/nut-driver@.service.in, server/conf.c, server/sstate.c, server/upsd.c
Partially addresses #1903 by adding on-the-fly reloading config concept to NUT drivers (e.g. to change `debug_min` settings) via SIGHUP, and enhances #1590 by adding systemd `Type=notify-reload` support (introduced there just recently, in 2023 - https://github.com/systemd/systemd/pull/25916).
Also addresses a few other issues:
Closes: #1907
Closes: #1908
Note that in practical setups with systemd `nut-driver-enumerator.service/.path`, it may detect change of `ups.conf` and cause restart of the driver instead of reload. This would be tackled later. As currently presented, the feature is of practical use for developers (running drivers from a build workspace), and on systems managing the driver population without NDE.
CC/FYI : @clepple @aquette @bigon @svarshavchik
=> Driver `reload` - basic support

drivers/snmp-ups.c
Hot fix for infinite loop during acquisition of daisychain epdu G3 with sensors (snmp-ups driver).
=> Acquisition failed with daisychain epdu G3 with sensors

docs/man/generic_gpio.txt, drivers/generic_gpio_common.c, drivers/generic_gpio_libgpiod.c, drivers/main.c, tests/generic_gpio_utest.c
Closes: #1892
CC @modrisb to check if removed `addvar()` cases do practically impact your setup?
TBH, I'd drop the "mfr" and "model" addvars too (in favor of `default.mfr` or `override.model` syntax), but these at least make sense from the point of view that we probably can not get those strings via "protocol" from the device itself, right? Or can we?
At least there is precedent for those in a few other drivers, where they are dubbed "overrides" for probably something the driver can find from the device, but not always or in a buggy fashion.
=> Revise use of `VAR_SENSITIVE` and other minor issues in new GPIO drivers

tools/gitlog2changelog.py.in
I am using the `gitlog2changelog.py` utility from this repository for [my project](https://github.com/cea-hpc/modules). As it is really useful, I am pleased to contribute back by proposing a few enhancements on `gitlog2changelog.py` tools:
* First is to make it resilient to specific git log format configured in user's git configuration.
* Second is to apply code change suggested by Black Python code formatter
* Third is to fix code issues spotted by Flake8 Python utility
=> Some small enhancements on gitlog2changelog.py 

NEWS, UPGRADING, tools/gitlog2changelog.py.in
Follows up from #1945
@xdelaruelle : Seems the long-words policy for `TextWrapper()` does it, thanks for the hint. Now the python2/3 generated files are almost identical, and differ a lot from those generated without this change (no longer broken at slashes and dashes in the path names).
````
diff -bu ChangeLog*n
--- ChangeLog2n 2023-06-02 12:11:58.987738723 +0200
+++ ChangeLog3n 2023-06-02 12:12:10.797738492 +0200
@@ -22992,12 +22992,11 @@
2014-02-14  Arnaud Quette <arnaud.quette@free.fr>
-       * docs/acknowledgements.txt: Update NUT team membership for
-         Frédéric Bohe  Frederic Bohe, NUT senior developer and Eaton
-         contractor from 2009 to 2013, is now a retired member. Thanks for
-         all the hard work on the Windows port, nut-scanner, Unix packaging,
- …
```
=> tools/gitlog2changelog.py.in: update TextWrapper settings to not break up file paths

drivers/liebert-hid.c
- Add additional properties by analyzing the HID descriptor of the PowerWalker VI 1200 SHL
- Existing properties were kept as they are to avoid breakage with other devices using the same driver
- See #1967 
case.
or its …
=> Improved Phoenixtec 0x06DA:0xFFFF support

NEWS, clients/upssched.c, docs/man/upssched.txt
Closes: #1964
Probably fallout from #1274 - CC @dtsecon for review
Now it is all quiet ([literally](https://m.xkcd.com/1172/), my fans whirred up without the fix):
````
:; killall upssched ; make -s -j 8 && \
UPSNAME=heartbeat@localhost NOTIFYTYPE=ONBATT \
NUT_STATEPATH=/dev/shm NUT_CONFPATH=`pwd`/tests/NIT/tmp/etc \
./clients/upssched -DDDDD
0.000000     [D2] parse_at: is 'heartbeat@localhost' in AT command the 'heartbeat@localhost' we were launched to process?
0.000052     [D1] parse_at: 'heartbeat@localhost' in AT command matched the 'heartbeat@localhost' UPSNAME we were launched to process
0.000064     [D1] parse_at: processing CANCEL-TIMER
0.000087     [D2] parse_at: is 'heartbeat@localhost' in AT command the 'heartbeat@localhost' we were launched to process?
0.000094     [D1] …
```
=> Avoid `upssched` infinite tight loops with (probably) closed sockets

.github/pull_request_template.md, LICENSE-DCO, docs/developers.txt, docs/nut.dict
=> CI/Legalese: Require DCO (`Signed-off-by:` git tags) in commits

NEWS, drivers/cyberpower-mib.c, drivers/cyberpower-mib.h, drivers/snmp-ups.c
=> Extend support to CPS devices which report the shorter Vendor OID as their sysOID

NEWS, common/common.c, common/state.c, configure.ac, docs/Makefile.am, drivers/apcupsd-ups.c, drivers/dstate.c, drivers/dstate.h, include/common.h, include/state.h, tests/.gitignore, tests/Makefile.am, tests/nuttimetest.c
CC @aquette @clepple : This is a fairly noticeable change to the deep internals, state info trees are at the core of everything in NUT. Would welcome another set of eyeballs that I got this conceptually right :)
Should I be concerned about computational overheads to keep reading and comparing time values? Should this behavior become a toggle (e.g. for programs that know they intend to use this feature at all)?
In context of issue #2007 there is a need to somehow avoid the current behavior with deletion of nearly all info about the device and then re-querying `apcupsd` to populate the dstate again. With this change we hopefully (un-tested so far) have a way to determine if any entries were not updated in the last read, and so should be cleaned away AFTER talking to the device (apcupsd …
=> Introduce state entry timestamping and use it to fix `apcupsd-ups`

NEWS, drivers/apcsmart-old.c, drivers/apcsmart.c
=> drivers/apcsmart(-old).c: do not abort on bad caps, skip them like before

NEWS, UPGRADING, conf/upsd.conf.sample, configure.ac, docs/config-notes.txt, docs/man/upsd.conf.txt, docs/security.txt, scripts/augeas/nutupsdconf.aug.in, server/upsd.c
...and fix some related issues
Closes: #2012
Testing:
* allowing "IPv4-mapped IPv6" mode, expected to be default for most OSes now, getting one socket for both IP versions:
````
...
Aug 05 22:56:41 pve nut-server[1767496]:    0.000240        [D3] setuptcp: try to bind to * port 3493
Aug 05 22:56:41 pve nut-server[1767496]:    0.000245        [D1] setuptcp: handling 'LISTEN * 3493' with IPv4 any-address support
Aug 05 22:56:41 pve nut-server[1767496]:    0.000250        [D1] setuptcp: handling 'LISTEN * 3493' with IPv6 any-address support
Aug 05 22:56:41 pve nut-server[1767496]:    0.000254        [D3] setuptcp: try to bind to 0.0.0.0 port 3493
Aug 05 22:56:41 pve nut-server[1767496]:    0.000273        listening on 0.0.0.0 port 3493
Aug 05 22:56:41 pve nut-server[1767496]:    0.000278 …
```
=> Define `upsd` option to `LISTEN *` as specifically handling both IPv4 and IPv6 "ANY" address

NEWS, data/driver.list.in, docs/nut.dict, docs/nutdrv_qx-subdrivers.txt, drivers/nutdrv_qx.c
Based on a debug output from a newer device (*/PF1) we've improved understanding on how:
- those devices encode the length of a chunk of data.
- how the end of transmission can be marked / detected.
Related to:
https://github.com/networkupstools/nut/pull/2003
https://github.com/networkupstools/nut/issues/1978
Closes #1978 
I'll test this changes for "old" devices in september. *Maybe* earlier.
=> drivers/nutdrv_qx.c: improve Armac subdriver

NEWS, drivers/hidparser.c, drivers/hidparser.h, drivers/libhid.c, drivers/libhid.h, drivers/libshut.c, drivers/mge-hid.c, drivers/usbhid-ups.c
Closes: #2022
Also adds a notion of "Device" to SHUT drivers, primarily to have a definite value there (not a random pointer) and while there, a useful one (store a copy of serial port path), to be on par with USB drivers per #974.
=> Fix some fallout of NUT v2.8.0 release for `mge-shut` (serial HID) driver

NEWS, drivers/cyberpower-mib.c
This reverts commit 8bcf255b624e6ba6c89a2a3eeab37658d9cb8cb4 from PR #686.
Cyberpower `snmp_info_t` got updated to conform with pre 5d97d07 instant
commands layout, but got merged after it. Reverting 8bcf255 so that command
values are correctly in `su_info_t->dfl`.
Fixes #2028.
=> Revert "cyberpower-mib: fix instant command declarations"

configure.ac, drivers/libhid.c, drivers/main.c
Cherry-pick a few small fixes that got bogged down along with PR #1652 - both to improve the main codebase, and to minimize comparison noise for that PR eventually.
Arguably, the change to remember `override.*` and `default.*` values into `driver.parameter.*` values and eventually into reported dstate information, this one is not that non-functional. But did not even feel substantial enough to warrant bumping all driver versions.
=> Cherry-pick nonfunctional improvements from PR #1652 (issue #1279)

drivers/cyberpower-mib.c
Follow-up from #2029 and #2028
Closes: #2040
CC @Bomorav @overhacked
=> drivers/cyberpower-mib.c: restore upsAdvanceControlUpsSleep as "shutdown.return"

NEWS.adoc, clients/upsclient.c, common/common.c
Closes: #2052 
The culprit was that in some libc implementations, calling `strdup(NULL)` causes a segfault, where such `NULL` can be returned by `strtok()` if there were no hits. Using `xstrdup()` introduced across NUT codebase specifically for safety checks like these turns it into a graceful failure that calling code can handle meaningfully.
See also #677 for related concerns.
=> Fix segfault in NUT clients with empty host/device name components

NEWS.adoc, docs/man/nut_usb_addvars.txt, docs/nut.dict, drivers/blazer_usb.c, drivers/libshut.c, drivers/libshut.h, drivers/libusb0.c, drivers/libusb1.c, drivers/nutdrv_qx.c, drivers/riello_usb.c, drivers/tripplite_usb.c, drivers/usb-common.c, drivers/usb-common.h, drivers/usbhid-ups.c, m4/nut_check_libusb.m4, scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in, tools/nut-scanner/scan_usb.c
Closes: #2043 (thanks @wavebvg for initial impulse!)
Related to: #1763 and like its outcome - does not impact the too-different old USB drivers like richcomm, bcmxcp, nutdrv_atcl
Note this is limited to systems that actually support the feature on hardware, OS and libusb version sides.
=> Allow USB device matching by `busport` value

NEWS.adoc, docs/nut.dict, drivers/ever-hid.c
Casually a small bug was found in 2.8.0 release, while processing DDL contributions, with a report value not namespaced.
=> Fix `ever-hid` mapping for `powerfactor`

.gitattributes
In a mixed environment with Windows IDEs chiseling Linux codebase and back, I got `make spellcheck` broken.
Investigation boiled down to CRLF ends of lines used in `docs/nut.dict` at that time, with the `\r` character confusing the Linux build of `aspell`. So far it never worked for me on MSYS2/MinGW x64 workspaces (no aspell builds working there so far), so there is no loss bolting it to be LF always.
=> .gitattributes: make sure docs/nut.dict is always LF (no CR)

ci_build.sh
Currently the `ci_build.sh` script starts many of its build scenarios with `make distclean` or `make realclean`. 
However in case of local development workflows, when some `Makefile.am` file(s) or the `configure.ac` script are edited, this call to `make` causes re-generation of Makefiles by a re-run of `configure` script (refreshed for the purpose) just to discover how to delete the previous build area and follow up with a new generation and configuration. Plain waste of several minutes (on slower platforms).
This PR allows the script to take a shortcut, with proper cleanup happening if recipes did not change since the last time, but a quick deletion of `Makefile` and `configure` products to cause re-generation for the new build right away if recipe files were edited or touched otherwise.
=> CI: Optimize `ci_build.sh` initial clean-up

NEWS.adoc, clients/Makefile.am, common/Makefile.am, common/common.c, configure.ac, docs/man/nutdrv_qx.txt, docs/man/usbhid-ups.txt, drivers/Makefile.am, drivers/nutdrv_qx.c, drivers/usb-common.c, drivers/usbhid-ups.c, include/common.h, m4/nut_check_libregex.m4, m4/nut_check_libusb.m4, tools/nut-scanner/nutscan-display.c
Closes: #1369
By side effect, moves detection of libregex build parameters (if any are needed) into a separate m4 script, and creates automake and C macros to shield about their presence. Generic regex helper methods (not intimate to USB) moved to common.c/h. Also, found that `clients/*` were built by default with `libcommon.la` (not `libcommonclient.la`) and pulled extra dependencies like `-lsystemd` that (most of) the clients should not care about - also addressed.
Example testing outcome: this change allows poking an Eaton device with a "not-its" (Tripplite) subdriver, even getting a bit of info as seen below.
Unlike `nutdrv_qx`, for the iteration shown below I did not constrain this feature to require at least a specified `vendorid` and `productid` in configuration, but makes sense to …
=> Enhance USB device and subdriver matching in `usbhid-ups` to be on par with `nutdrv_qx`

ci_build.sh
Try a few optimizations after recent feature changes (particularly #2065) so the usual CI loops take less time.
=> CI: Run `ci_build` loops faster

docs/nut-names.txt
Have a clear(er) definition, discuss caveats, prevent mishaps.
=> Docs: clarify naming scheme in `docs/nut-names.txt`

NEWS.adoc, UPGRADING.adoc, common/common.c, configure.ac, include/common.h, tests/NIT/nit.sh, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-ip.c
Closes: #317
On one hand, this PR does what issue #317 asked for, to consider "multiarch" path components (if suggested by compiler) when we consider dynamic library loading at run-time (`nut-scanner`, eventually DMF, etc.) Resulting paths are constructed per https://wiki.debian.org/Multiarch/LibraryPathOverview (prefixing `(/usr)/lib(bits)` essentially).
On another, it uncovered and addressed some earlier issues (bugs and annoyances):
* the `get_libname_in_pathset()` method (added after 2.8.0 release, largely as part of NUT for Windows effort) had some issues both with accounting the number of directories checked, and with looking at them in the reentrant fashion (`strtok()` involved in parsing mangled the original string, such as `getenv("PATH")` original, adding `0x00` chars where it …
=> `nut-scanner`: additional multiarch libraries search path; general: fixes to (debug) logging

configure.ac
The code to detect the available drivers does so by parsing `Makefile.am` but it does not do so relative to "$srcdir" so trying to do a configure outside of the source directory will fail.
case. …
=> configure.ac: Fix out of source tree builds

clients/Makefile.am, common/common.c, conf/nut.conf.sample, configure.ac, docs/configure.txt, docs/man/nut.conf.txt, docs/nut.dict, scripts/systemd/nut-driver-enumerator.path.in, scripts/systemd/nut-driver-enumerator.service.in, scripts/systemd/nut-driver.target, scripts/systemd/nut-driver@.service.in, scripts/systemd/nut-monitor.service.in, scripts/systemd/nut-server.service.in, scripts/systemd/nut.target, scripts/systemd/nutshutdown.in
CC @bigon @aquette @clepple : I intend to merge this soon'ish - no big pressure to hurry, but no big reason to wait. Let me know if you want to review this (experiment in practice?) and need more time... :)
In this PR I poked at (lack of) useful messages from `scripts/systemd/nutshutdown` (and I now think this script itself is more generally useful than just for systemd). In a recent power failure I know the server went down correctly with most events traceable per its journal, but I have no idea if this script was tried.
This led to revision in docs (man page and sample of `nut.conf`) as well as updating the shutdown integration script to be optionally verbose (true by default), and to facilitate power-race avoidance shutdowns on systems that are purely NUT clients (have `upsmon` to …
=> systemd integration update and nut.conf comments

NEWS.adoc, data/driver.list.in, drivers/optiups.c
The _optiups_ driver only gave accurate voltage information with 120VAC models and assumed a 12V battery when calculating capacity.
There's an `FV` command that gives a (fixed) voltage that correlates with the voltage selection DIP switches on the back of the UPS, taking into account whether ti's a 120 or 240VAC model. So it's easy enough to do `if (FV > 180) then voltage = voltage * 2`, still using the `NV` and `OV` commands to pull the live in/out voltage data.
I suspect this would apply to all UPS using this protocol, under the assumption that the driver was developed on 120VAC devices where the scaling issue wasn't apparent.  However, as I can only test on a PS-1440RM at 230VAC, I've only applied the change to "PS-*" series UPS through a new `_pollv_ps[]` struct.
It would make sense …
=> Correct voltage and battery capacity for Opti-UPS 230VAC and/or 24VDC models

docs/Makefile.am, docs/man/Makefile.am
Closes: #2081 (to always distribute all man page sources - even if the build was configured only for a few drivers)
Note: thinking about it, this might still falter in contrived use-cases... The dist tarball is supposed to include pre-built man pages (from the distributor's system), so the building systems have an option to not re-generate the pages or even to not have tools for that, and yet to produce packages convenient for end-users. A `configure --with-drivers=usbhid-ups` sort of build config would only pre-generate and dist-tarball that driver's man page. TLDR: "real" dist tarballs should be made on systems capable of (and configured to) building all driver types.
TODO: In fact, no system is able to build all driver types nowadays - e.g. some are specific to MacOS or Linux. A recipe …
=> Fix docs makefiles

Jenkinsfile-dynamatrix, clients/upsclient.c, clients/upssched.c, common/common.c, common/wincompat.c, configure.ac, data/driver.list.in, drivers/apcupsd-ups.c, drivers/clone.c, drivers/dummy-ups.c, drivers/main.c, drivers/upsdrvquery.c, include/wincompat.h, m4/ax_c_pragmas.m4, m4/ax_run_or_link_ifelse.m4, server/netssl.c, tests/Makefile.am, tests/generic_gpio_utest.c, tests/nutlogtest.c, tools/nut-scanner/scan_xml_http.c
Follows up from #823 and related to investigation of recent mess-up with dynamatrix variable passing for test environments per https://github.com/networkupstools/jenkins-dynamatrix/issues/24
As a side bonus, fixes a few actual or potential bugs and reduces the count of static analysis complaints.
=> A little bit of Fightwarn

drivers/compaq-mib.c
Hot fix in snmp drivers: bad mapping in compaq mib for ups (input/output tensions, currents and frequency).
=> Fix issues in compaq mib

NEWS.adoc, docs/man/tripplite_usb.txt, docs/nut.dict, drivers/tripplite_usb.c
@jimklimov My apologies, I screwed up the pull request with a rebase. I just started a new pull request to have a clean slate scenario. Added the NUT_UNUSED_VARIABLE  per your recommendation.
background:
tripplite_usb.c Added UPS ID (upsid) Support: The code now includes support for matching and uniquely identifying UPS devices using the UPS ID (upsid). The upsid configuration option has been added, which accepts a regular expression to match the UPS ID string. This was done by adding a new function called match_by_unitid, that reads the upsid from the config file, then reads the upsid from the device, and checks if they match. This function is now passed to the comm_driver matcher on first connect and reconnects.
Added the upsid to the upsdrv_makevartable function so it is read and …
=> tripplite_usb.c Enhanced Device Identification in the tripplite_usb Driver for Tripp Lite USB UPSes

configure.ac, include/str.h, m4/ax_c_pragmas.m4, m4/ax_run_or_link_ifelse.m4, tests/Makefile.am
Closes: #2109
Follows up from: #2096, #823
As now posted, the PR should allow configure script to gauge practical support of `printf("%s", NULL)` again, and refactors the two detections of this ability, that have evolved over time, into one.
Also includes a little fix to same feature that broke detection of C++ CPPUNIT testability support.
=> Fix loss of configure-phase detection due to recent enhancements

tools/nut-usbinfo.pl
If we don't normalize the case before inserting VID/PID/Driver into `$vendor` we can have duplicate entries.
=> nut_usbinfo.pl: Lowercase the USB ids before inserting

.gitignore, NEWS.adoc, UPGRADING.adoc, common/common.c, drivers/dummy-ups.c, tests/NIT/nit.sh
This PR started as an investigation into occasional NIT (NUT Integration Test) script failures, and so far stumbled on a number of imperfections in the dummy-ups driver - so started with those.
Updated with NIT test-script fixes as well.
NOTE: Strange behavior noted on WSL2 Ubuntu builds (maybe the VM is just slow now) that both `upsd` and `dummy-ups` daemons logged stuff in bursts separated by roughly 10 sec, and those logs took a while to appear on display. There seemed to be a considerable delay between driver start, and readiness, and socket creation, and upsd connection to that socket, and DUMPALL request, and lots of info streaming until DUMPDONE marker - took about a minute overall for that test case initialization, and almost 3 min for the script. On other systems it goes at 1 sec …
=> Clean up `dummy-ups` code, behavior and logs; added `NUT_DEBUG_PID` option

AUTHORS, data/driver.list.in, docs/man/Makefile.am, docs/man/apc_modbus.txt, docs/nut.dict, drivers/Makefile.am, drivers/apc_modbus.c, m4/nut_check_libmodbus.m4, tools/nut-usbinfo.pl
This adds APC Modbus support to address isssue #139. For USB support, this needs a [patch for `libmodbus`](https://github.com/EchterAgo/libmodbus/commits/rtu_usb).
To install the patched `libmodbus`, you need to get the code and install it into a prefix somewhere:
```
./autogen.sh
./configure --prefix=/path/to/prefix
make install
```
to compile NUT you need something like this:
```
./configure --with-drivers=apc_modbus --with-usb --with-modbus --with-modbus-includes=-I/path/to/prefix/include/modbus --with-modbus-libs="-L/path/to/prefix/lib -lmodbus"
```
There is still a bit of work to be done:
a functional change. Notably, coding style changes better …
=> apc_modbus: Support for APC Modbus protocol

drivers/apc_modbus.c
`strncpy` does not necessarily zero terminate the buffer so we replace it with `snprintf` and add error checking.
This also fixes an off-by-one in the `snprintf` error checking of the `_apc_modbus_double_to_nut` and `_apc_modbus_power_to_nut` functions and adds error checking to every `snprintf` call.
fixes #2122 
case.
(notably `blazer` and other …
=> apc_modbus: Use snprintf instead of strncpy

drivers/apc_modbus.c, drivers/apcsmart.c, drivers/belkinunv.c, drivers/openups-hid.c, drivers/optiups.c, drivers/tripplitesu.c, include/common.h, tests/getvaluetest.c
This adds a new `SIZEOF_ARRAY` to `common.h` and changes some code to use it.
case.
(several vendors do use same interface chips …
=> Add `SIZEOF_ARRAY` macro and use where applicable

Jenkinsfile-dynamatrix
=> CI: Apply github notifications and JSL loading enhancements from Fightwarn branch

clients/upsmon.c
fixes #2126 
previously OL devices now no longer go critical in nocomms situations (as intended)
previously not-OL devices still go critical in nocomms situations (as intended)
tested the following situations:
- NUT as master with SNMP driver, UPS last seen as OL => not critical on comm-loss (as intended, works)
- NUT as master with SNMP driver, UPS last seen as OB => critical on comm-loss (as intended, works)
- NUT as slave with NUT master last seen as OL => not critical on comm-loss (as intended, works)
- NUT as slave with NUT master last seen as OB => critical on comm-loss (as intended, works)
input welcome (first code-wise contribution to the project)
=> upsmon: fix discrepancies between linestate & status flags resulting in critical UPS

NEWS.adoc, docs/man/dummy-ups.txt, drivers/dummy-ups.c
This presents a possible follow up for the useful revisions of #2118.
It is currently not possible to utilize the `dummy-ups` driver's repeater function within a local multi-UPS `ups.conf` file, particularly having `upsdrvctl` collectively start all drivers via e.g. `/usr/sbin/upsdrvctl -u root start` or within a systemd environment.
The reason for this is that the `dummy-ups` driver at present terminates prematurely upon encountering any kind of error at repeater mode startup, in particular a connectivity one due to the driver it should repeat not being 100% up yet or `upsd` not being up yet - as encountered during collective `upsdrvctl` startup. This proceeds to raise an erroneous return code from `upsdrvctl` (`Driver failed to start (exit status=1)`) possibly breaking the user's entire …
=> dummy-ups: relax error handling to prevent premature driver termination

NEWS.adoc, clients/upsmon.c, conf/upsmon.conf.sample.in, docs/man/upsmon.conf.txt, docs/nut.dict
As suggested by mailing list: "secondary" systems that take long to stop their workloads can get a power-cut too early because their `upsmon` exits just after calling `SHUTDOWNCMD` and so allow the primary to stop and `killpower`. This PR makes such behavior configurable - adding an option for `upsmon` to linger after telling its system to shut down.
TODO/Idea for further improvement: Handle numbers as the time to linger, not as a boolean?
=> clients/upsmon.c et al: introduce SHUTDOWNEXIT boolean/delay-length option [#2133]

drivers/upsdrvctl.c
Follows up from #2134 discussion; also addresses a few minor issues in the tool.
The current behavior for `upsdrvctl` is to treat timeout (over `maxstartdelay`) immediately as a bump of `exit_error` counter, which leads to `exit(EXIT_FAILURE)` after all the drivers (if many) have been processed. This gives time for some long-initializing driver to have in fact completed the start-up (or definitely fail it).
The PR changes the behavior to separately track timeouts vs. known errors, and only later revise how those PIDs ended up.
CC @desertwitch : would you like to test if this behaves differently for your case (even if just logging the situation more clearly)?
So far the default behavior remains the same - if the driver is still initializing, the tool bumps the error counter and exits with …
=> `upsdrvctl`: separate `exec_timeout` from `exec_error`

NEWS.adoc, common/common.c, docs/nut.dict, scripts/Aix/nut.init.in, scripts/HP-UX/nut-drvctl.sh, scripts/HP-UX/nut-upsd.sh, scripts/HP-UX/nut-upsmon.sh, scripts/RedHat/upsd.in, scripts/RedHat/upsmon.in, scripts/Solaris/nut.in, scripts/Solaris/svc-nut-monitor.in, scripts/Solaris/svc-nut-server.in, scripts/Solaris8/S99upsmon
Issue raised in mailing list, follow-up to #1590 and related issues: messages about *inability* to notify a framework are considered noise on OSes without any framework to notify. They can be important troubleshooting aid on systems *with* frameworks however.
* https://alioth-lists.debian.net/pipermail/nut-upsuser/2023-October/013457.html
=> Introduce `NUT_QUIET_INIT_UPSNOTIFY=true` support

NEWS.adoc, drivers/riello.c, drivers/riello_ser.c, drivers/riello_usb.c
Closes: #2137
Follows up from [#1106 int-type changes to riello.c (among many others)](https://github.com/networkupstools/nut/pull/1106/files#diff-547696e27242b307a42b56fef3bc671cdeb0266794d735e2bb40a16f6a32db7f)
=> drivers/riello*.c: fix back bit maths changed with #1106

m4/nut_compiler_family.m4
Do not use isystem with host paths when cross-compiling
=> m4/nut_compiler_family.m4: fix cross-compilation

m4/nut_check_python.m4
Allow the end-user to override `PYTHON{2,3}_SITE_PACKAGES` as this can be useful when cross-compiling
=> m4/nut_check_python.m4: allow overriding of PYTHON{2,3}_SITE_PACKAGES

drivers/libusb0.c, drivers/libusb1.c, drivers/nut_libusb.h, drivers/usb-common.h
The tactical goal of this change is to change
ret = libusb_get_config_descriptor(device,
(uint8_t)usb_subdriver.hid_rep_index,
&conf_desc);
to
ret = libusb_get_config_descriptor(device,
(uint8_t)usb_subdriver.usb_config_index,
&conf_desc);
Before this change, libusb1.c did libusb_get_config_descriptor() with a config index equal to the interface number. For composite devices using an interface index > 0, this is usally the wrong choice. Concretely, I'm using an Arduino for a DIY UPS project and these are composite devices with multiple interfaces under the first (and only) config descriptor.
In the USB descriptor heirarchy, deivce descriptors have config descriptors which have interface descriptors. Also, nearly all USB devices have a single configuration (index 0).
In order to do this, I …
=> Add usb_config_index to usb_communication_subdriver_s, default to 0.

drivers/dstate.c, drivers/libhid.c
A couple small one-line fixes:
* Fix SIGSEGV while preforming INSTCMD
* Fix passing of errors up from libusb 1.x
=> Misc fixes

scripts/python/Makefile.am
The code as is installs the python module's setup.py in the site-packages directory; this is incorrect.
This commit removes setup.py from an automake variable, which resolves the issue.  I do not know if it impacts any other kind of module publicaition process.  We may need a more complicated fix.
=> python: Do not install setup.py

.github/workflows/PyNUTClient.yml
Other repos lack needed pypi credentials anyway.
@gdt: I think this is the issue you reported.
=> .github/workflows/PyNUTClient.yml: limit auto-runs to NUT upstream [#2158]

clients/upsmon.c, clients/upssched.c, drivers/snmp-ups.c, server/conf.c
When certain NUT daemons (upsd, upsmon, upssched; also snmp-ups with mib.conf files) initialize and parse their configuration, they used to just report seeing a certain parse error and it was not clear if the problem was considered fatal, or if the service proceeded to start.
With this PR, we report and count all such errors, and if the count was non-zero - issue a message to stress that some config entries were ignored but the program proceeds.
It feels reasonable to not start the mis-configured service as well, so the admins would fix it... But that may be a task for some other PR (e.g. consider an older daemon running against newer-syntax config files).
=> Report config parsing errors ("invalid directive")

.github/workflows/PyNUTClient.yml, scripts/python/module/.gitignore, scripts/python/module/Makefile.am, scripts/python/module/setup.py.in
Closes: #2180
Closes: #2181 
Passes installation when built locally:
````
nut/scripts/python/module/dist$ pip install PyNUTClient-2.8.1.139-py3-none-any.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./PyNUTClient-2.8.1.139-py3-none-any.whl
Installing collected packages: PyNUTClient
Successfully installed PyNUTClient-2.8.1.139
````
The `LICENSE-GPL3` file is included in `PyNUTClient-2.8.1.139.dist-info` subdirectory inside the archive.
A one-off test upload: https://test.pypi.org/project/PyNUTClient/2.8.1.139.1/
CC @mtelka
=> PyNUT license and other setup.py metadata

scripts/Solaris/nut-driver-enumerator.xml.in, scripts/Solaris/nut.xml.in, scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
Rely less on NDE (among nut-driver package footprint) being generally installed, and avoid calling it directly if possible; rather try to `refresh` all the anticipated units which do the work.
=> scripts/Solaris/nut.xml.in: revise "refresh" handling in umbrella SMF service

drivers/apcsmart-old.c
The code returned `STAT_SET_UNKNOWN`, which is for variables that were not found, instead this should return `STAT_SET_INVALID`, which means that the variable is not writable.
case.
VID/PID …
=> apcsmart-old: Fix return value for not writable variable

NEWS.adoc, drivers/arduino-hid.c
Add support for the common status flags as well as time remaining, battery voltage and other variables found in other HID subdrivers. The Arduino library always supported these items, just the NUT subdriver didn't pick them up so things like status were always OB.
=> battery.runtime, status OL/OB and more for Arduino subdriver

drivers/libusb1.c
The libusb_get_bus_number() function serves as a simple accessor for the bus number of the opaque device struct. Unlike libusb_get_port_number(), it does not have the ability to convey errors back to the caller, and a bus number of 0 is a valid value. Therefore, any validation around bus_num is redundant.
This commit removes the unnecessary validation code related to bus_num.
Signed-Off-By:	Xin LI <delphij@FreeBSD.org>
=> drivers/libusb1.c: Remove unnecessary validation for bus_num

NEWS.adoc, clients/upsmon.c, conf/upsmon.conf.sample.in, docs/man/upsmon.conf.txt, docs/man/upsmon.txt, server/conf.c
Closes: #2207
Follows up from #1784
Now `POLLFAIL_LOG_THROTTLE_MAX` is actually the "max" and not "skip N loops and report during the next one after N", so the default behavior of reporting the errors on every loop (also as the negative `POLLFAIL_LOG_THROTTLE_MAX` value) is same as setting `1` here. A `0` still goes for reporting only the start and end of a condition; still one tracked `upserror` condition per UPS.
With this PR in place, it also logs the expected report frequency more clearly (in seconds, not just loop counts):
````
Dec 01 12:25:44 pve nut-monitor[1521804]: Poll UPS [dummy] failure state code changed from -1 to 10; report below will only be repeated to syslog every 3 polling loop cycles (15 sec):
Dec 01 12:25:44 pve nut-monitor[1521804]: Poll UPS [dummy] failed - Data …
```
=> upsmon: `POLLFAIL_LOG_THROTTLE_MAX` had an off-by-one error

NEWS.adoc, docs/man/usbhid-ups.txt, docs/nut.dict, drivers/usbhid-ups.c
Closes: #1970
Closes: #2212
Closes: #2213
Closes: #2214
Closes: #2215
Introduces a number of new configurable toggles with hopefully reasonable defaults, which should help to reduce log noise on systems where an UPS reports "online" and "discharging" simultaneously (so far some CyberPower and APC models were reported to behave so, with different physical situations).
=> `usbhid-ups`: allow to throttle or suppress logged messages about `OL+DISCHRG` situation

NEWS.adoc, data/driver.list.in, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_nut.c
When discovering NUT, either with Avahi or old method, the reported driver is "nutclient", which doesn't (yet) exists.
This should be fixed to dummy-ups, which will use the repeater mode, while waiting for #2232 
the short term fix is to symlink nutclient to dummy-ups (example on Debian):
> cd /lib/nut && ln -s dummy-ups nutclient
=> 2236 nut scanner reports non existent driver for nut discovery

NEWS.adoc, data/driver.list.in, docs/developer-guide.txt, docs/man/Makefile.am, docs/man/nut-scanner.txt, docs/man/nutscan_init.txt, docs/man/nutscan_scan_nut_simulation.txt, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/nutscan-device.h, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-init.h, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_nut_simulation.c
Provide an additional nut-scanner "-n | --nut_simulation_scan" option to detect and configure dummy simulation (.dev & .seq) from the default $sysconfdir.
This should standardize and streamline the use of nut-scanner as an automatic detection and configuration tool.
Closes: #networkupstools/nut/issues/2242
=> nut-scanner: detect and configure NUT simulation devices

tools/nut-scanner/nut-scan.h, tools/nut-scanner/scan_nut_simulation.c
nut-scanner: simplify and fix simulation scan code
Remove non-portable directory and alphasort filtering code, since there is no
actual need for it, and cause system portability issues.
Also fix the simulation scan function prototype.
Closes: #2249
=> 2249 nut master branch builds broken after recent prs andor infra changes

Makefile.am, ci_build.sh, clients/Makefile.am, common/Makefile.am, configure.ac, docs/Makefile.am, docs/cables/Makefile.am, docs/man/Makefile.am, drivers/Makefile.am, include/Makefile.am, lib/Makefile.am, scripts/python/module/Makefile.am, server/Makefile.am, tests/Makefile.am, tests/NIT/Makefile.am, tools/Makefile.am, tools/nut-scanner/Makefile.am
Allow configuring it (or have it guessed), and `export` it in the `Makefile`s so that developer workflow benefits from the customized setting when running `make`. Tested to work for GNU and BSD makes, and not work for Sun make/dmake implementation (recipe change is a no-op there).
The namespacing allows the CI farm (or multiplatform/qemu container devs) to use the same `~/.ccache` area in a home directory, with object files grouped by the target build platform, so they can be "evicted" independently (e.g. did not cross-build ARM for a year - nuke just its files), e.g. with: `ccache -sv && ccache --evict-namespace=nut:aarch64-linux-gnu && ccache -sv`
=> CI: make use of `ccache` namespace support, where possible

docs/man/nut-scanner.txt, tests/NIT/nit.sh, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/nutscan-device.h, tools/nut-scanner/nutscan-display.c
When nut-scanner is called separately, to scan different buses, it will generate similar names for each of these:
* USB scan
> [nutdev1]
> ...
* NUT scan
> [nutdev1]
> ...
* ... As a result, one can't just redirect nut-scanner outputs directly to ups.conf, without a 'sed' hack workaround.
Solution: simply refine the device names, like "nutdev-<method><id>".
Ex: nutdev-usb1, nutdev-usb2, nutdev-nut1, nutdev-snmp1, nutdev-simulation1, ...
=> nut-scanner: fix device-name collisions in generated conf

NEWS.adoc, docs/man/nut-scanner.txt, docs/nut.dict
Follow-up from #2245, #2246, #2247...
Should help avoid this:
````
make[2]: Entering directory '/home/jim/nut/docs/man'
DOC-MAN  Generating nut-scanner.8
asciidoc: WARNING: nut-scanner.txt: line 227: missing style: [paradef-literal]: nutdev-usb1
asciidoc: WARNING: nut-scanner.txt: line 237: missing style: [paradef-literal]: nutdev-snmp1
asciidoc: WARNING: nut-scanner.txt: line 237: missing style: [paradef-literal]: nutdev-snmp1
asciidoc: WARNING: nut-scanner.txt: line 256: missing style: [paradef-literal]: nutdev-nut1
````
=> Retouch nut-scanner docs and NEWS

NEWS.adoc, drivers/libusb0.c, drivers/libusb1.c, drivers/main.c
Closes: #2259
Currently emitted messages in this case require some sleuthing. This PR hopefully makes troubleshooting easier:
````
./nutdrv_qx -s test -x productid=1234
Network UPS Tools - Generic Q* Serial driver 0.36 (2.8.1-285-ge2bfdbbd4)
Fatal error: 'productid' is not a valid variable name for this driver.
Look in the man page or call this driver with -h for a list of
valid variable names and flags.
NOTE: for driver 'nutdrv_qx', options like 'productid' are only available
if it was built with USB support. If you are running a custom build of NUT,
please check results of the `configure` checks, and consider an explicit
`--with-usb` option. Also make sure that both libusb library and headers
are installed in your build environment.
upsnotify: notify about state 4 with libsystemd: was …
```
=> Help users about `nutdrv_qx` and similar drivers built for serial-only support but used for USB devices

docs/man/upsd.conf.txt, docs/man/upsmon.conf.txt, docs/security.txt
=> Update upsd/upsmon conf docs regarding NSS and general asciidoc markup

NEWS.adoc, clients/upsmon.c, docs/nut.dict
I was able to replicate the issue #2278, it seems to be as suspected in #2278: Due to `offstate == 1` not being a required condition at present (rather an optional condition) when evaluating UPS criticality, instant FSD is triggered despite `offdurationtime` not being exceeded yet (and `offstate` still being 0) when the UPS is seen both `OB` and `OFF`. This happens due to disregarding `offstate` when `linestate == 0` in combination with the `ST_OFF` flag and `offdurationtime >= 0` is met.
However `offstate` must always be a required condition for `offdurationtime` to have an effect as `ST_OFF` flag is instantly set upon encountering an `OFF` state, regardless of how long the UPS has been in this state.
Testing the proposed change FSD is only happening when `offdurationtime` is reached, …
=> clients/upsmon.c: fix offstate not being a requirement for a critical UPS on OFF

drivers/eaton-ats16-nm2-mib.c
This support is identical to what is in Eaton Marlin and Powerware MIBs. Future improvements should consider putting these bits in a common eaton-sensor-mib file, to avoid multiple definition of the same MIB structure!
Imported from FTY fork / DMF branch (with reductions for main trunk) from commit 40c883f42aede519fe716a6d26e7dff567996d75
Originally by @aquette
NOTE: After merge of other contemporary PRs, this code would welcome wrappings from #2285 (available in #2275 which is where these not-upstreamed lines were "discovered").
=> Eaton: add support for EMP002 on ATS16 NM2 with SNMP

tests/NIT/nit.sh
On some systems NIT did not find many tools or data sources needed to check the busy/free port state, and used BASH `echo ... > /dev/tcp/...` for active probing. It is suspected that at least on older distros this could lead to the previously available port remaining in `WAITING` state, so `upsd` could not bind to it for the first minute or so.
This PR revises the "passive" probing methods to try avoiding this situation.
=> CI: Fix NIT `isBusy_NUT_PORT()` method

NEWS.adoc, drivers/tripplite_usb.c
small fix restoring matching when upsid is undefined in the ups.conf file closes #2282 as per the thread
cc @clepple
=> Fix: tripplite_usb: if upsid is not specified, make any unit ID match

NEWS.adoc, data/driver.list.in, drivers/cps-hid.c, drivers/ever-hid.c, scripts/upower/95-upower-hid.hwdb
Following up from https://alioth-lists.debian.net/pipermail/nut-upsdev/2024-February/007966.html - this PR adds support for VID:PID delegated to Cyber Energy:
> In the past, CyberPower UPS works well with NUT. Today, I want to use another VID/PID to fulfill ODM business rather than CyberPower brand UPS. My engineer will apply standard USB power device description like as CyberPower’s USB design. The only difference is VID/PID.
Note that the oficially registered vendor ID 0x0483 is for ST Microelectronics who then delegate certain product IDs to different OEMs.
=> `drivers/cps-hid.c` et al: add support for Cyber Energy branded devices (by Cyber Power Systems)

Makefile.am, docs/Makefile.am
Follow up from #2318 work: on at least OpenBSD, the existing recipe was all but skipped, so no `ChangeLog` appeared in the builddir and ultimately no `adoc` and `html` products from it.
=> Fix docs generation of ChangeLog (in out-of-tree builds)

ci_build.sh, configure.ac
In some build recipes we use symbolic- or hard-linking of files (e.g. DIST'ed resources) and originally had a fallback to `ln` if relative `ln -s -r` was not available. This fallback did not work when source and build areas (the most typical use-cases) are on different filesystems (e.g. under `/home` and `/tmp`) - with this PR, fall back to full copy would be used instead.
Follows up from #2318 work.
NOTES:
* This macro is not actually used in current Makefiles of the `master` branch so far, but perhaps should be (especially for other out-of-tree concerns, like that with text sources for docs per #2318). It is used in DMF/FTY branches that slowly converge towards getting upstreamed, however. And now that a deficiency in the macro already present in the main codebase is known, fixing it is …
=> `configure.ac`: revise detection of `LN_S_R` method applicable for the build (out-of-tree concerns)

indent.sh, scripts/HP-UX/makedepot.sh, scripts/Windows/build-mingw-nut.sh, scripts/installer/make_package.sh, scripts/subdriver/gen-snmp-subdriver.sh, scripts/subdriver/gen-usbhid-subdriver.sh
Fix the way we refer to `bash` where it is needed.
=> Shell shebang

docs/config-prereqs.txt, m4/nut_check_libltdl.m4
NUT failed to detect `libltdl` and so build `nut-scanner` on OpenBSD; now it should.
=> Fix recipes for openbsd

NEWS.adoc, drivers/nutdrv_qx.c
The current code uses getval() to examine the setting of `battery_voltage_reports_one_pack`. However, since `battery_voltage_reports_one_pack` is a flag rather than a variable, getval() will always return null. Function testvar() must be used instead.
Closes: #2325
=> Correct access method used for flag battery_voltage_reports_one_pack

docs/Makefile.am
When aspell is not unavailable, the cause can either be that aspell itself is not installed, or it has no English dictionary (`aspell-en`). I've wasted several minutes today due to this oversight. Add this reminder in the error message to give clue to future developers.
=> docs/Makefile.am: reminder about missing dictionary when aspell is unavailable

docs/man/huawei-ups2000.txt, docs/nut.dict
I received a user report that the model `UPS2000-G-3KRTL` was shown to be functional using the NUT driver `huawei-ups2000`. Add that to the documentation.
This is notable for being the first reported working "long backup time" variant of the UPS2000 with an external battery pack. Their hardware and firmware are likely identical to the "standard backup time" model, but it's good to see a confirmation of that.
=> huawei-ups2000.txt: add UPS2000-G-3KRTL to the confirmed list

tools/nut-scanner/nut-scanner.c, tools/nut-scanner/scan_nut_simulation.c
Closes: #2334
Closes: #2335
CC @aquette @desertwitch
=> Fix `nut-scanner` caveats about USB optional fields and simulation file discovery

scripts/systemd/nut-driver-enumerator-daemon-activator.path.in, scripts/systemd/nut-driver-enumerator-daemon-activator.service.in, scripts/systemd/nut-server.service.in
Follow-up from #2275
These changes pertained to specifically systemd-oriented optimizations for a massively monitoring system (one NUT server watching hundreds of networked UPSes and responding to many clients).
* `nut-server` change bumps the allowed count of opened file descriptors (also used for network and UNIX sockets) as far as we can drive it
* NDE change revises reaction to external processes which generate `ups.conf` and write it in small pieces (e.g. lines) over time, avoiding that systemd kills the NDE unit as unhealthy
=> Bump NUT `master` branch from FTY: systemd integration

Jenkinsfile-dynamatrix, docs/man/Makefile.am, docs/man/apc_modbus.txt, docs/nut.dict, m4/nut_check_libmodbus.m4, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
A subset of PR #2366 which should be less failure-prone than its attempts to fix/tweak Makefile recipes portably, so as to merge at least some of this iteration quickly.
Includes APC Modbus + USB doc update, as well as hopefully straightforward small codebase fixes from that PR.
=> APC Modbus doc updates

Makefile.am, NEWS.adoc, UPGRADING.adoc, docs/Makefile.am, docs/man/Makefile.am, tools/gitlog2changelog.py.in
Follow-up from #2360 - a few fixes to hiccups uncovered in CI and local runs
NOTE: Started as an APC docs update PR, that direction was eventually offloaded into PR #2368
=> Doc build recipe updates

NEWS.adoc, drivers/belkin-hid.c, drivers/usbhid-ups.c, drivers/usbhid-ups.h
Adding support for the Liebert PSI5 model of UPS, as discussed in #2271 initially.
Maybe addresses similar complaints posted in #2024 
Closes: #2271
=> feat: Add support for Liebert PSI5

NEWS.adoc, drivers/belkin-hid.c, tests/.gitignore, tests/Makefile.am, tests/driver-stub-usb.c, tests/getexponenttest-belkin-hid.c, tests/getexponenttest.c
As raised on the mailing list at https://alioth-lists.debian.net/pipermail/nut-upsuser/2024-March/013626.html as well as in discussions for #2271, #2369 and #2370, there is some mess in exponents calculation of `drivers/belkin-hid.c`, where the driver tries to adjust for what seems wrongly encoded voltage readings in USB HID reports, which may be off by some orders of magnitude (3, 7...) depending on reading type and HW/FW model.
As detailed in https://github.com/networkupstools/nut/issues/2370#issuecomment-2017664722 : The original logic which purported to fix this was broken, but by coincidence seems to have taken the right code path for the majority of devices up till NUT v2.7.4. This was fixed in NUT v2.8.0 to correct logic, but the order of magnitude estimation results no longer fit …
=> Unit-test and fix the Belkin/Liebert HID UPS exponents math

NEWS.adoc, clients/upsmon.c, conf/upsmon.conf.sample.in, docs/man/upsmon.conf.txt
Part of findings from investigation for issue #321
=> Clarify the value of POWERDOWNFLAG in `upsmon -h` and document that it must be set

clients/upsmon.c, drivers/main.c, drivers/upsdrvctl.c, scripts/misc/notifyme-debug, scripts/systemd/README.adoc, server/upsd.c
Closes: #1783
Initially noticed for `upsmon` doing this for every `notify()`, but later found to happen for other daemons' exit as well.
=> Avoid printing NUT banners at `exit()` of each forked child process

docs/Makefile.am
Recent changes to docs building before NUT v2.8.2 release amplified the noise from "bogus spellcheck" `make` events so I got to investigate them. Seems like a side effect of having too open `SUFFIXES` defined in automake-parsed file (and source files that do not have an expected extension like `.txt` -- e.g. a `LICENSE` file name).
Also hoped to quiesce `a2x: WARNING: --destination-dir option is only applicable to HTML and manpage based outputs` but the current make files can actually use a dedicated `A2X_OUTDIR` for each document even with in-tree builds, so the solutions from other posters in https://web.archive.org/web/20201207082352/https://github.com/asciidoc/asciidoc/issues/44 (e.g. https://github.com/dfoxfranke/libaes_siv/commit/c0e282b218bb1a693dba25b96ecc866ccb27b857) do not seem …
=> Quieter docs builds

NEWS.adoc, docs/man/riello_ser.txt, docs/man/riello_usb.txt, drivers/riello_ser.c
Import from sibling (Riello/USB) driver the ability to guesstimate battery charge and runtime from voltage. Same caveats apply, including expected obsoletion in favor of `runtimecal` at some later point in time.
Closes: #2390 
Follows up from #1692
=> `riello_ser`: port `localcalculation` feature from `riello_usb`

NEWS.adoc, clients/upsmon.c, common/common.c, docs/nut.dict, drivers/main.c, drivers/upsdrvctl.c, include/common.h, server/upsd.c
Follows up from issue #1782 and PR #2383
CC @gdt (is this reasonably quieter?)
Avoid a few lines of text (when running without boosted debug verbosity) here and there, and default to avoid the infamous `fopen /var/state/ups/upsd.pid: No such file or directory` sort of messages that regularly raise questions/concerns from new NUT users.
* With debug, all is seen as before:
````
:; ./server/upsd -D
Network UPS Tools upsd 2.8.2-29-g422cffad9
0.000000     fopen /var/state/ups/upsd.pid: No such file or directory
0.000032     Could not find PID file '/var/state/ups/upsd.pid' to see if previous upsd instance is already running!
0.000100     stat /home/jim/nut/tmp/etc/nut/upsd.conf: No such file or directory
````
* Default is a little bit quiet(er) but importantly less confusing:
````
:; …
```
=> Quieter start-up of `upsmon`, `upsd` and driver daemons (avoid "scary" `fopen()` failure messages)

NEWS.adoc, drivers/libusb0.c, drivers/libusb1.c
Closes: #2399
The message may be due to `0` meaning either `LIBUSB_SUCCESS` or a zero byte count in returned string (man page says a positive value means a successful return). Core problem is likely a libusb or device issue, but this PR can help discern that.
NOTE: Not sure if an actual empty-string return is one byte long (the `\0` byte), so a zero-value reply is always a problem?
=> drivers/libusb{0,1}.c, NEWS.adoc: avoid spurious syslog of `(nut_)libusb_get_string: Success`

NEWS.adoc, data/cmdvartab, docs/man/nutupsdrv.txt, docs/man/upsdrvctl.txt, drivers/main.c, drivers/main.h, drivers/upsdrvctl.c, drivers/upsdrvquery.c, drivers/upsdrvquery.h
When a NUT driver starts, by default it checks the PID file (if present) to kill off its earlier running instance, if any, to have the device connection available and no logical conflicts at run-time.
Problems can arise when the PID file is not available (e.g. not saved due to service unit set-up). Technically we have a fallback capability of checking for the old driver instance via Unix socket made for driver-server communications, and since #1903 and numerous later issues and PRs we can have driver instances (and `upsdrvctl`) interact over this channel.
This PR adds a new Unix socket protocol command, `driver.exit` which can be used similar to `SIGTERM` and so cleanly exit the NUT driver program (with the goal of a new instance being able to start). Note that if the deceased instance …
=> Implement an `INSTCMD driver.exit` as alternative to PID files and signals

NEWS.adoc, data/driver.list.in, docs/nut.dict, drivers/nutdrv_qx.c
Closes: #2395
Given that this uses a serial port connection, not sure there is much more to "fix" on NUT code base side.
=> [HCL] `data/driver.list.in`: Note known support for Visench C1K UPS

NEWS.adoc, clients/upsmon.c, clients/upsmon.h, conf/upsmon.conf.sample.in, docs/man/upsmon.conf.txt, docs/nut.dict
Largely follows in the footsteps of #2104 which introduced the `OFFDURATION` toggle.
This PR adds an `OBLBDURATION` toggle to delay issuing FSD (primary) or commencing a shutdown after `HOSTSYNC` (secondary without a seen FSD alert), for users that deem this desirable (some use-cases suggested in issue #321 discussion - primarily to survive short hiccups that happen at the wrong moment) at their discretion and risk of an ungraceful shutdown.
Closes: #321
CC @desertwitch @dark-penguin @clepple @aquette 
Testing in practice would be as welcome as code review :)
=> upsmon: introduce `OBLBDURATION` config toggle

NEWS.adoc, drivers/main.c, drivers/snmp-ups.c
Fallout of #2259 / PR #2260 (regression in NUT v2.8.2 release, not a default code path and can be worked around with explicit `-F`/`-B` CLI options, though - so not extremely critical)
Thanks to @ericclappier-eaton @arnaudquette-eaton @FrancoisRegisDegott-eaton and 42ITy team.
=> drivers/main.c: move "-d" CLI option handling also to start of program

NEWS.adoc, clients/upsmon.c, common/common.c, common/nutipc.cpp, common/nutstream.cpp, drivers/main.c, drivers/upsdrvctl.c, include/common.h, include/nutipc.hpp, include/nutstream.hpp, include/nutwriter.hpp, server/upsd.c, tests/NIT/nit.sh, tests/cpputest-client.cpp, tests/cpputest.cpp, tests/example.cpp, tests/nutclienttest.cpp, tests/nutconf_parser_ut.cpp, tests/nutipc_ut.cpp, tests/nutstream_ut.cpp
Also update the NIT script regarding `upsmon.conf` generation and friendliness to run NUT programs against the prepared testbed, and improve the ability to generate variants of upsmon configuration and to launch the daemon in tests (no particular tests added so far).
And bump (C) on C++ code, due to a few changes there and noticing some staleness in the file headings.
Also introduced value caching for this and other path-getting methods - so that subsequent calls return the same value quickly (less work, more reproducibility. Checked that no NUT C programs use `setenv` along the way (at all, and notably not for path-related envvars in particular), which could potentially impact this logic change.
Regarding the `rootpidpath()` - an envvar is now honoured:
````
:; ./clients/upsmon -DDDDDD …
```
=> Introduce a `rootpidpath()` method instead of direct use of `PIDPATH` macro (e.g. in `upsmon`)

docs/nut.dict
Probably the last bit to complete #2402 as of now. Local `make spellcheck` passes in both this NUT source iteration and in the NUT-WEBSITE told to use it.
NOTE: Simple `grep` checks suggested removing `configureaza` which is originally still mentioned in a Spanish(?) article reference with `configurează` in the title (with diacritics). Also the name `Christoph` (starting with upper-case) was amended.
=> docs/nut.dict: drop key words absent in both current NUT and NUT-WEBSITE sources

NEWS.adoc, scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
Per investigation in #2410, not limited to systemd but a core issue and a fallout of #682. Breakage limited to NUT v2.8.2 release.
Closes: #2410
CC @ericclappier-eaton @FrancoisRegisDegott-eaton @arnaudquette-eaton 
CC @bigon @svarshavchik - would you please review and perhaps add a patch to Linux packaging of NUT v2.8.2?
=> NDE: `nut-driver@devicename` unit instances do not auto-reload with NUT v2.8.2 when `ups.conf` is edited

NEWS.adoc, common/nutconf.cpp, common/nutwriter.cpp, conf/nut.conf.sample, docs/man/nut.conf.txt, docs/nut.dict, drivers/blazer.c, drivers/blazer_ser.c, drivers/blazer_usb.c, drivers/nut-ipmipsu.c, include/nutconf.hpp, include/nutwriter.hpp, scripts/augeas/Makefile.am, scripts/augeas/gen-nutupsconf-aug.py.in, scripts/augeas/nutnutconf.aug.in, scripts/augeas/nutupsconf.aug.tpl, scripts/augeas/nutupsdconf.aug.in, scripts/augeas/nutupsdusers.aug.in, scripts/augeas/nutupsmonconf.aug.in, scripts/augeas/tests/test_nut.aug, scripts/augeas/tests/test_nut_fixme.aug, scripts/augeas/tests/test_nut_flaky.aug, tests/nutconf_parser_ut.cpp, tests/nutconf_ut.cpp, tools/nutconf/nutconf-cli.cpp
Closes: #2294
Note: per #657 there is more work to improve flexibility of augeas lenses - simple cases should work, but not all combos that NUT own parser supports.
Note: It seems that per initial codebase import (from 2013-ish branch to NUT v2.8.2) the sprawl of C++ header/class/test code  is an internal detail of `nutconf` CLI tool - not a library delivered for external consumer linking. As such, there are no concerns currently about API versioning, backwards compatibility, variable/method name changes, etc. which would impact any code not visible from NUT repo itself and its regular builds. This frees up hands for refactoring like this, but eventually it could be useful to document and release the library for NUT configuration management... maybe? Or would the CLI suffice for external …
=> Update `nutconf` and `augeas` lenses with support for NUT keywords added between releases 2.6.5 and 2.8.2

drivers/gamatronic.c
case.
(several vendors do use same interface chips for unrelated protocols).
`scripts/upower/95-upower-hid.hwdb` file
file. If the …
=> drivers/gamatronic.c: Replace strcpy() on overlapping strings, and ensure UPS-provided data length cannot overflow string buffer

Makefile.am, docs/Makefile.am
This should allow for some faster development cycles (not causing `ChangeLog` re-generation for every call that resolves to `make ChangeLog`, and subsequently taking a minutes or two for the HTML/PDF variants of the huge file).
Goes into guts of Git a bit too much, maybe, but this particular recipe is about being intimate with it anyway, and at worst we would keep generating the file when maybe we should not (if git repo filesystem backend design changes).
Should also help with https://github.com/networkupstools/nut-website/issues/52 tangentially (at least regarding development cycles to fix that).
Example results in a `nut-website` build area (where `nut` is a submodule):
````
~/nut-website/nut$ ls -la .git
-rw-r--r-- 1 jim jim 28 Sep 12  2022 .git
~/nut-website/nut$ cat .git
gitdir: …
```
=> Regenerate `ChangeLog` file only if git metadata got updated

NEWS.adoc, drivers/usbhid-ups.c
Follows-up from: #2215 / #2216
Closes: #2423
CC @desertwitch : you seem to be great at testing strange corner cases with shutdown criteria and logging settings like this, may I ask for a bit of your time to look at this feature? Seems to have been touted for NUT v2.8.2, but not actually completed by the earlier PR - at least as far as end-user ability to practically configure it is concerned. So probably not well tested either :\
As a reminder, this started for UPSes which normally only charge up to a 100% level and then let their battery seep away until it hits a threshold (90-95%) so it is boosted back to 100% again. With this setting, if in such case the UPS reports OL+DISCHRG state, we can throttle logging of the situation and avoid the needless log spam.
=> `usbhid-ups.c`: complete the support of `onlinedischarge_log_throttle_hovercharge` setting

NEWS.adoc, drivers/mge-hid.c
Closes: #2380
Testing needed, CC @jstallard @lemeshovich
Confirmation that the added device names/models are what should be expected from hardware would be very welcome - CC @arnaudquette-eaton
Here so far I've added the basic VA numbers from model lists for 5PX and 5SC, but there are many models marketed for some of the same power ratings - no idea if they identify differently via USB.
* https://www.eaton.com/gb/en-gb/site-search.html.searchTerm$5sc.tabs$all.html
* https://www.eaton.com/gb/en-gb/catalog/backup-power-ups-surge-it-power-distribution/eaton-5px-ups-emea.html
Also note that original 5PX is discontinued; not sure if 5PX Gen2 should identify differently (and/or if it needs another "type" enum value).
=> `mge-hid.c`: extend `mge_model_names[]` for Eaton 5SC and 5PX series

NEWS.adoc, docs/man/Makefile.am, docs/man/nut.exe.txt, scripts/Windows/wininit.c
* added `help()` method
* added CLI options to handle version, help, debug level
* improved error-reporting when running it in a terminal: seeing nothing with no error reporting is not fun (gotta dig in code to find out to go to Event Log for the error message)
* added a man page (see also #2445 about delivering it nicely)
Closes: #2432
=> WIN32: Document `nut.exe` wrapper and improve its usability

Makefile.am, NEWS.adoc, UPGRADING.adoc, configure.ac, docs/Makefile.am, docs/man/Makefile.am, docs/nut.dict, scripts/Windows/build-mingw-nut.sh, scripts/augeas/Makefile.am
Previously these advanced documentation formats were only built, but I found no examples of them being installed by `make`.
=> Enable installation of built HTML and PDF documents

NEWS.adoc, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c
It seems that commit 3eb96fe98f9bd75813fa243832732e61ac614726 (PR #2246 for issue #2242) released in NUT v2.8.2 broke detection that `libupsclient.so` is not available (not a really practical situation breaking end-user setups, outside of some weird packaging choices on constrained systems, or builds on systems where NUT is not installed into common paths - it did fire up in test cases investigated for another issue #2431).
Also this PR takes a moment to clarify what "old nut" is about in `nut-scanner` context (as opposed to "new" avahi-based detection where available) so `help()` and codebase reading is more comprehensible.
Finally, this PR changes all flags about detected scanning methods to be zeroed initially, only set to `1` (even if always) in the `nutscan_init()` method, to be …
=> `nut-scanner`: Fix "Old NUT" detection and clarify some log messages

NEWS.adoc, data/driver.list.in, docs/man/Makefile.am, docs/man/bicker_ser.txt, docs/nut.dict, drivers/Makefile.am, drivers/bicker_ser.c
This driver supports some interesting supercap DC UPSes manufactured by [Bicker](https://www.bicker.de/en/products/ups-systems/dc-ups). I'm planning to use them in the near future on small Linux-based industrial PC (mainly amd64 or arm64).
AFAICS, there are two main issues:
1. the code does not work on big-endian platforms (see the [relevant comment](https://github.com/ntd/nut/blob/bicker/drivers/bicker_ser.c#L183-L184))
2. the way I'm using `ups.delay.shutdown` stinks: most drivers defines it in `upsdrv_initinfo` but then my `upsdrv_shutdown` function crashes when trying to access it. I followed the `usbhid-ups.c` example and put it inside `upsdrv_initups`.
=> WIP: Bicker serial driver

docs/man/nut.exe.txt, docs/nut.dict, scripts/Windows/wininit.c
Follow-up to: #2446
Closes: #2455
=> Add `net start/stop` docs and practical support to `nut.exe`

docs/man/bicker_ser.txt, drivers/bicker_ser.c
I exposed all parameters and mapped them 1:1 to NUT names. I used `nut-names.txt` whenever possible and mapped the rest to other (hopefully logical) names. I then added the possibility to change everything with `upsrw` and added documentation. I don't know the policy on driver versioning, so I bumped the version in a separate commit: if not needed it can be easily dropped.
My Bicker UPS is still broken but it funnily responds to any request "almost" properly, so (apart from the disabling of parameters with an empty value) I tested everything. With "almost" I mean the returned parameter always has 0xFFFF as min/max and 0xFF as enabled.
One thing that could be a source of problems is parameter `0x01`, mapped to NUT `output.current.low`, is expressed in mA. Not sure if I need to convert it …
=> bicker_ser: allow changing of non-volatile variables with `upsrw`

NEWS.adoc, common/common.c, conf/nut.conf.sample, docs/man/nut.conf.txt, include/common.h, tests/NIT/nit.sh
This was tested with NIT (log messages indeed disappear from OS text console).
This feature is expected to help with systemd log line duplication (see issue #2394) but was not tested that way yet.
=> Introduce `NUT_DEBUG_SYSLOG` envvar to completely disable `syslog` (e.g. in NIT)

NEWS.adoc, UPGRADING.adoc, clients/upsmon.c, common/Makefile.am, common/common.c, configure.ac, docs/nut.dict, drivers/main.c, drivers/upsdrvctl.c, include/common.h, server/upsd.c
Closes: #2463
Per discussion in the issue above, blind PID signalling is a problem on embedded platforms which do not differentiate user accounts, so a NUT driver can kill some unrelated program assuming it is a stuck driver (just by PID file matching) and not be stopped by permissions to send a signal to a program not owned by a `nut` account.
This is a platform-dependent solution, so by default if we can not determine a program name - we do not forbid signal-sending. Likewise, if a name is detected and seems to match expectations (modulo directory prefix, or on some platforms - case-sensitivity or `.exe` suffix) we also consider it a match. Finally, only if we detect a name of the running process with the specified PID and it is not anything like our expectation, the check is failed. …
=> Hardening: verify that we send signals by PID to programs with expected name

NEWS.adoc, clients/upsmon.c
Addresses #2454
Commit 2647f026f7f0 from #2108 updated `is_ups_critical()` such that a communication failure (`commstate == 0`) while on battery (`linestate == 0`) would be treated as immediately entering critical state.
There was no way to disable that behavior or add any grace period.  As such, that change made `DEADTIME` parameter ineffective as `lastpoll` being stuck should be equivalent to `commstate == 0` because any `lastpoll` update would set `commstate` to 1.
Also, that change in how a communication failure affects OB state was no explicitly communicated in the commit message or the pull request. They talked only about OFF, BYPASS and CAL states.
This change removes special handling of that condition from `is_ups_critical()` and reverts to the prior behavior where `recalc()` …
=> clients/upsmon: restore handling of comm failure while on battery

NEWS.adoc, UPGRADING.adoc, clients/upsmon.c, common/common.c, conf/nut.conf.sample, docs/man/nut.conf.txt, docs/nut.dict, drivers/main.c, drivers/upsdrvctl.c, include/common.h, scripts/Windows/wininit.c, server/upsd.c
Follow-up to issue #2463 and PR #2464
Earlier work introduced a way to check that a running PID's process name (if we can detect it) matches our expectations (`upsmon`, `upsd`, driver name) before we send signals - as we did, blindly and naively.
This PR adds a way to disable this feature if it causes problems (e.g. embedded builds tend to have undecipherable NUT version strings to match a firmware name, and I can imagine someone tweaking program names or using symlinks as well... some `snmp-ups-dmf` comes to mind). 
It also adds a fallback ability to optionally check the other PID's process name against the current PID's process name (not requested from `upsdrvctl` which manages variously-named driver programs, but is requested from drivers, `upsd` and `upsmon`) to hopefully alleviate …
=> Hardening: Fall-back double-`checkprocname()` vs. current daemon program name (and add `NUT_IGNORE_CHECKPROCNAME=true` toggle)

Makefile.am, NEWS.adoc, common/Makefile.am, configure.ac, docs/configure.txt, docs/nut.dict, drivers/Makefile.am, m4/ax_c_pragmas.m4, tools/nut-scanner/Makefile.am
To merge in one operation and update the docs:
* #2473
* #2477
* #2478
* #2479
=> Combine several small PRs for issue #1316 and their NEWS entries

Makefile.am, NEWS.adoc, configure.ac, docs/configure.txt
Address part of #1316 regarding a couple of features:
* `make distcheck-light-man` allows to automate `distcheck`-style tests with a requirement to re-build MAN pages in the dist'ed directory (make sure we have enough files in the tarball to do so);
* `./confgure --with-doc=man=dist-auto` allows to use pre-distributed MAN pages if present (should be in tarballs; should not be in git; may be left over from earlier builds in same workspace) or build those if we can (the `auto` part)
* Nominally this adds generic `./confgure --with-doc=dist-auto` as well, but is implemented in detail only for `man` as we do not `dist` HTML and PDF products; is a placeholder for those.
The FTY branch further uses the `--with-doc=man=dist-auto` feature in reference DEB/RPM packaging recipes (not upstreamed …
=> Upstream from FTY branch: `make distcheck-light-man` and `./confgure --with-doc=man=dist-auto` features

common/Makefile.am, tools/nut-scanner/Makefile.am
Address part of #1316
A smaller helper library than `libcommonclient.la` which is sometimes an overkill, e.g. in `nut-scanner` where the `libupsclient.so/.dll` is loaded dynamically for "Old NUT" scans and there is no specific use for object files included into `libcommonclient.la`.
More use-cases with DMF codebase (currently not yet upstreamed).
Combined from a series of commits like
* 3ba6b576cd2248484eaad41a9e2a480cbd2aa6a6
* c418728e6ed7879f4a569ca0e3fd6f38fcb27eae
* 5f16b7b7c89fa341090e886e7ca5cf8d981430eb
* bc4cd957280c67778a36b49b524092dc15d1aa8b
=> common/Makefile.am, tools/nut-scanner/Makefile.am: Introduce `libcommonstr.la`

m4/ax_c_pragmas.m4
Address a part of #1316
Use-cases will appear in DMF codebase merge eventually; upstreaming this part early would help avoid reinventing these wheels if we would need them elsewhere.
=> m4/ax_c_pragmas.m4: introduce HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ADDRESS and HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_PEDANTIC

drivers/Makefile.am, tools/nut-scanner/Makefile.am
=> Port recipe for `libserial-nutscan.la` from DMF/FTY branch and clean up nut-scanner makefile

common/Makefile.am, drivers/Makefile.am, tools/nut-scanner/Makefile.am
A piece of #1316 and follow-up to #2478
=> Revise `libwincompat.la` vs. `libcommonstr.la` helpers in `libnutscan` build recipe

clients/upsclient.h
Include `sys/types.h` to avoid the following uclibc build failure with collectd raised since version 2.8.0 and
https://github.com/networkupstools/nut/commit/3f3851eab0d51e029f67e7db359860cc983557f4:
```
configure:109633: checking int type of port argument for NUT upscli_splitname
configure:109665: /home/buildroot/instance-0/output-1/host/bin/x86_64-linux-gcc -c -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2 -g0   -Wall -Werror -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  conftest.c >&5
In file included from conftest.c:172:
/home/buildroot/instance-0/output-1/host/x86_64-buildroot-linux-uclibc/sysroot/usr/include/upsclient.h:114:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
114 | ssize_t upscli_sendline_timeout(UPSCONN_t *ups, …
```
=> clients/upsclient.h: include sys/types.h

NEWS.adoc, ci_build.sh, configure.ac, docs/nut.dict, scripts/python/Makefile.am, scripts/python/README.adoc, scripts/python/module/Makefile.am, scripts/python/module/PyNUT.py.in, scripts/python/module/nut_telnetlib.py, scripts/python/module/setup.py.in, scripts/python/module/test_nutclient.py.in
Addresses: #2183
Not a perfect solution (that would be rewriting the socket communications for the client), but a feasible stop-gap suggested by deprecation docs -- and should address the acute problem for the module.
Checked by renaming a `/usr/lib/pythonX.YY/telnetlib.py` file away, and running `DEBUG=true make check-NIT` to see that the fallback `nut_telnetlib` "implementation" is imported and tests still pass.
=> Provide a private copy of `telnetlib` for `PyNUTClient`

NEWS.adoc, UPGRADING.adoc, common/common.c, docs/nut.dict, m4/ax_realpath_lib.m4, m4/nut_check_libavahi.m4, m4/nut_check_libfreeipmi.m4, m4/nut_check_libneon.m4, m4/nut_check_libnetsnmp.m4, m4/nut_check_libusb.m4, m4/nut_compiler_family.m4, tools/nut-scanner/nutscan-init.c
This change allows to remember string values of library names (and full paths) seen during build, and prefer them over bland `libsomething.so` symlinks which may be not even available in non-dev packages on some systems. Addresses most of issue #2431
One remaining bit is the name of our own `libupsclient.so/dll/...`
Maybe the logic put into `m4` now should become a standalone shell script, to generate a `#define` one-line header after we build our library?..
This should also be applied to DMF branch (loads more libs in other code paths).
=> Remember shared-object file names seen during build for later run-time `dlopen()` preference

COPYING, configure.ac, docs/nut.dict, m4/nut_check_python.m4, scripts/python/module/nut_telnetlib.py
Follow-up to issue #2183 and PR #2501
Thanks to @opoplawski for reviews there
````
:; PYTHON=python3.11 ./ci_build.sh
...
checking python interpeter to call... /usr/bin/python3.11 (sys.version_info(major=3, minor=11, micro=0, releaselevel='candidate', serial=1))
checking python site-packages location... /usr/local/lib/python3.11/dist-packages
checking for python2... python2
checking python2 interpeter to call... /usr/bin/python2 (sys.version_info(major=2, minor=7, micro=18, releaselevel='final', serial=0))
checking python2 site-packages location... /usr/local/lib/python2.7/dist-packages
configure: WARNING: A python3 program name was not specified during configuration, will default to '/usr/bin/python3.11' (derived from --with-python setting which has a suitable version)
checking python3 …
```
=> Follow-up for `nut_telnetlib.py` stashed copy, and some more recipe refactoring around Python deliverables

.circleci/config.yml, ci_build.sh, docs/developers.txt
Follows up from #2506 and earlier work.
One notable change here is about preference of `CPP="$CC -E"` in `ci_build.sh` detection, to avoid the pitfalls of "traditional" parsers. Due to this the PR is tested separately from earlier completed iteration.
=> Revise recipes for MacOS builds and general portability some more, and update docs

NEWS.adoc, docs/man/nut-scanner.txt, docs/nut.dict, drivers/libshut.c, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Now the `-m cidr` and `-s`/`-e` option groups can be repeated on command line, and cause several IP address ranges to be scanned for SNMP, NetXML, IPMI and old NUT buses.
Preparation for #2244 (`-m auto` which would likely find several connected subnets on a typical server). That step would likely need something like:
* https://stackoverflow.com/questions/4139405/how-can-i-get-to-know-the-ip-address-for-interfaces-in-c
* https://dev.to/fmtweisszwerg/cc-how-to-get-all-interface-addresses-on-the-local-device-3pki
* https://stackoverflow.com/questions/2655544/solaris-programmatic-interface-to-ifconfig (if someone would want this on Solaris before 2011 - older than Solaris 11 or OpenSolaris/illumos)
* https://stackoverflow.com/questions/20469857/is-there-any-getifaddrs-alternative-on-hp-ux-sol …
=> Teach `nut-scanner` to handle several IP address ranges

NEWS.adoc, docs/man/Makefile.am, docs/man/nut-scanner.txt, docs/man/nutscan.txt, docs/man/nutscan_add_ip_range.txt, docs/man/nutscan_free_ip_ranges.txt, docs/man/nutscan_init_ip_ranges.txt, docs/man/nutscan_ip_ranges_iter_inc.txt, docs/man/nutscan_ip_ranges_iter_init.txt, docs/man/nutscan_scan_ipmi.txt, docs/man/nutscan_scan_nut.txt, docs/man/nutscan_scan_snmp.txt, docs/man/nutscan_scan_xml_http_range.txt, docs/man/nutscan_stringify_ip_ranges.txt, docs/nut.dict, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/nutscan-ip.h, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Since work on issue #2244 began, `nut-scanner` learned to request scans for many individual IP addresses or ranges in one call. That was functional, but slow (as described in issue #2511) due to each range being scanned independently, until its timeout was hit.
This PR adds a way to iterate the IP address range collections, and extends the iterated multiple-IP methods for "Old NUT", SNMP, NetXML and IPMI (not parallelized yet!) to iterate not over a single set of `start_ip .. end_ip` but over all requested addresses in the same thread pool (per bus). For a small series of single-IP ranges this yields a very quick scan (not constrained by a sum of timeouts times the amount of such ranges).
=> Teach `nut-scanner` to parallelize scans across many IP address ranges

NEWS.adoc, docs/man/Makefile.am, docs/man/nut-scanner.txt, docs/man/nutscan.txt, docs/man/nutscan_add_ip_range.txt, docs/man/nutscan_free_ip_ranges.txt, docs/man/nutscan_init_ip_ranges.txt, docs/nut.dict, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/nutscan-ip.h
Follow-up for PRs #2509 and #2513, of issue #2244.
This PR adds a way to constrain the scan amounts in discovered subnets by specifying the bit-width of the host address part (e.g. in a typical IPv4 `/24` subnet, that part of the option value would be `32-24 = 8` => `-m auto4/8`).
Also it now reports detailed reasons why this or that discovered subnet was ignored (too large, loopback, not up and running...)
Detailed "screenshot" from a test run:
````
:; make -ks -j && LD_LIBRARY_PATH=`pwd`/clients/.libs ./tools/nut-scanner/nut-scanner -DDDDDD -O -m auto4/4
...
0.080064     [D5] Discovering getifaddrs(): Interface: lo    Address: 127.0.0.1      Mask: 255.0.0.0 (subnet: 8, hosts: 24)  Flags: 00010049 IFF_LOOPBACK IFF_UP IFF_RUNNING
0.080106     [D6] Subnet ignored: address range too large: …
```
=> Teach `nut-scanner -m auto*/ADDRLEN` modes

NEWS.adoc, common/common.c, configure.ac, m4/nut_check_headers_windows.m4, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Found two ways to skin the cat. Apparently on older systems (~Vista and before) some structures may be different, something someone would address if encountered.
Checked both APIs in WSL builds, but had problems actually connecting to a NUT data server on another system (when calling NUT programs from WSL and having Windows intercept them to execute). The `upsc.exe` also had such problems; so maybe firewall.
Same binaries executed straight from Windows did walk the data server and discover its devices:
````
C:\Temp\nut_install\bin>./nut-scanner.exe -m auto
Scanning NUT bus (old libupsclient connect method).
Scanning NUT simulation devices.
Failed to open //etc, skip NUT simulation scan
[nutdev-nut1]
driver = "dummy-ups"
port = "dummy@xxx.yyy.zzz.99"
[nutdev-nut2]
driver = "dummy-ups"
port …
```
=> Implement `nut-scanner -m auto*` modes on WIN32

NEWS.adoc, clients/upsc.c, clients/upsclient.c, docs/man/nut-scanner.txt, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_xml_http.c
Closes: #2512
As found in that issue (in turn stemming from work on PRs for #2244), we had a problem with IPv6 address passing to `nut-scanner`. The culprit was about lack of square brackets (as required by our `upscli_tryconnect()` and `device@host:port` parser methods, to differentiate components of colon-separated IPv6 address from an optional colon-separated port number). Use of square brackets around IP address strings is common practice to suppress DNS resolution or separate host identifiers from port numbers, etc.
On the other hand, `nut-scanner` also rejected addresses wrapped by the brackets, so they could not be passed to the tool.
This PR fixes both the input side (accept and strip brackets from addresses in `-s` and `-e` for start/end of a range, and `-m` for CIDR), and the …
=> Fix `nut-scanner` IPv6 support

UPGRADING.adoc, clients/upsclient.h, drivers/nut-libfreeipmi.c, drivers/usb-common.c, drivers/usb-common.h, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nutscan-device.c, tools/nut-scanner/nutscan-device.h, tools/nut-scanner/nutscan-display.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-ip.h, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_usb.c, tools/nut-scanner/scan_xml_http.c
Stressed in `UPGRADING.adoc` that we updated `libnutscan` version due to new methods and a structure change (latter pending), so new exported symbols.
Fixed code style for nested preprocessor code vs. pedantic preprocessor implementations, and to satisfy related recent updates to NUT developer style guide.
A few small changes to comments and code layout here and there.
=> Assorted codebase cleanup while preparing work for issue #2523

Makefile.am, NEWS.adoc, UPGRADING.adoc, common/common.c, docs/developers.txt, docs/nut.dict, scripts/Makefile.am, scripts/valgrind/.valgrind.supp, scripts/valgrind/README.adoc, scripts/valgrind/valgrind.sh, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-display.c, tools/nut-scanner/nutscan-init.c, tools/nut-scanner/nutscan-ip.c, tools/nut-scanner/nutscan-serial.c, tools/nut-scanner/scan_avahi.c, tools/nut-scanner/scan_eaton_serial.c, tools/nut-scanner/scan_ipmi.c, tools/nut-scanner/scan_nut.c, tools/nut-scanner/scan_nut_simulation.c, tools/nut-scanner/scan_snmp.c, tools/nut-scanner/scan_usb.c, tools/nut-scanner/scan_xml_http.c
Addresses part of #2511
Closes: #2523
=> Implement parallel IPMI scanning in `nut-scanner`, and address some `valgrind` complaints

.gitignore, ci_build.sh, docs/Makefile.am, scripts/Windows/build-mingw-nut.sh
Outcome of part of investigation for issue #2510
Apparently we can end up with valid-looking but contentually wrong documents. Possibly `asciidoc` or `a2x` gives up generating the XML intermediate file (the prepared asciidoc text source is huge, several megabytes and thousands of sections) and we get just a beginning part of the change log, or we still have some clashes from parallel runs corrupting each other's files (should have been solved earlier in the year, but...)
Anyhow, we can try to catch and prevent delivery of generated pretty documents (starting with the simplest case of single HTML) which do not mention first, second and last section titles present in the `ChangeLog` (generated from git) exactly twice (table of contents and section itself).
=> CI: Sanity-check generated `ChangeLog.html` with more attention to detail

NEWS.adoc, README.adoc, clients/.gitignore, clients/Makefile.am, clients/upsclient.c, clients/upsclient.h, clients/upsmon.c, common/nutwriter.cpp, docs/Makefile.am, docs/config-prereqs.txt, docs/man/hwmon_ina219.txt, docs/nut.dict, drivers/apc-mib.c, drivers/hwmon_ina219.c, drivers/libhid.c, drivers/libhid.h, drivers/masterguard.c, drivers/mge-utalk.h, drivers/microdowell.c, drivers/nutdrv_qx.c, drivers/usbhid-ups.c, include/nut_platform.h, include/parseconf.h, m4/ax_realpath_lib.m4, server/netssl.c, server/nut_ctype.h, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scan.h, tools/nut-scanner/nut-scanner.c, tools/nut-scanner/nutscan-init.c
Follow-ups for #2244, #2431, #2450, #2467 et al
=> Detect `libupsclient` SO filename, revise shared object extensions

Makefile.am, NEWS.adoc, UPGRADING.adoc, docs/Makefile.am, tools/gitlog2changelog.py.in
Closes: #2510
Also actually enables `make ChangeLog.html-contentchecked` to fail when needed.
This should finally nail it! :D
=> Fix `ChangeLog` content ordering (avoid interleaved dates) and build ordering (avoid potential conflicts and CPU resource waste in parallel builds)

NEWS.adoc, docs/Makefile.am, m4/nut_check_libusb.m4, m4/nut_check_pkgconfig.m4
Some fallout collected and lessons learned from #2536 build failures.
=> Fix `ChangeLog.html-contentchecked` logic to survive several mentions of date+author; fix host `pkg-config` vs. cross-builds

Makefile.am, NEWS.adoc, ci_build.sh, scripts/Makefile.am, scripts/augeas/Makefile.am, scripts/udev/Makefile.am
Closes: #2541
Also addresses a few more small issues noted on MacOS builds.
=> Fix `make distcheck*` builds to use passed `DISTCHECK_FLAGS` to sub-`configure` script

Makefile.am, docs/maintainer-guide.txt, drivers/snmp-ups.h, tools/nut-scanner/scan_snmp.c
Follow-up to PR #2554 for issue #1949. Headers from libnetsnmp declare their autoconf macro values directly, conflicting with ones we define ourselves for NUT, so historically we `undef`ed them before SNMP code builds. Now that we deliver `PACKAGE_URL`, gotta handle it similarly.
=> Neuter our `PACKAGE_URL` in SNMP code builds

NEWS.adoc, UPGRADING.adoc, clients/upslog.c, clients/upsmon.c, common/common.c, conf/nut.conf.sample, docs/maintainer-guide.txt, docs/man/nut.conf.txt, docs/man/upsdrvctl.txt, docs/man/upsdrvsvcctl.txt, docs/nut.dict, docs/sock-protocol.txt, drivers/dstate.c, drivers/main.c, drivers/upsdrvctl.c, drivers/upsdrvquery.c, include/common.h, scripts/upsdrvsvcctl/upsdrvsvcctl.in, server/netget.c, server/netmisc.c, server/upsd.c, tests/NIT/nit.sh, tools/gitlog2version.sh
Also update some docs for recently added tweaking envvars, and use `PACKAGE_URL` value in networked queries (`upsd` `GET` and `GET VAR <upsname> server.info`).
Touches on several issues/PRs:
* #2567
* #1789
* #316
* #1949
* #2118
* #2136
* #1662
UPDATE: With `status` (also in `upsdrvsvcctl`, albeit rudimentary -- just calling `upsdrvctl` but not drilling into service unit info) it actually...
Closes: #2567
=> Teach `upsdrvctl` to list device config names and show run-time `status`, and to optionally hide the start-up banner

NEWS.adoc, common/common.c, docs/man/upsdrvctl.txt, docs/man/upsdrvsvcctl.txt, docs/sock-protocol.txt, drivers/dstate.c, drivers/dstate.h, drivers/upsdrvctl.c, drivers/upsdrvquery.c, scripts/upsdrvsvcctl/upsdrvsvcctl.in, server/netmisc.c, tools/gitlog2version.sh
Address lack of signals, properly close connections, add `LOGOUT` to dstate (local socket protocol).
Follows up primarily from issue #2567 / PR #2568 but also touches on some other recent work like #1949 
UPDATE: Also completes `upsdrvsvcctl status`, tested with Debian Linux systemd and OpenIndiana SMF
=> Follow-up to `upsdrvctl status` on Windows, add `LOGOUT` to local socket protocol

NEWS.adoc, clients/upsc.c, clients/upscmd.c, clients/upslog.c, clients/upsmon.c, clients/upsrw.c, common/common.c, configure.ac, docs/nut.dict, drivers/apc_modbus.c, drivers/huawei-ups2000.c, drivers/main.c, drivers/upsdrvctl.c, include/common.h, include/timehead.h, scripts/Windows/build-mingw-nut.sh, scripts/Windows/wininit.c, server/upsd.c, tools/nut-scanner/Makefile.am, tools/nut-scanner/nut-scanner.c, tools/nutconf/nutconf-cli.cpp
Closes: #2573
Follows up from #2568 and #2554 recent efforts.
Adding the banner to C++ tool `nutconf` had some impact on detection of time headers and methods, which failed on Linux+mingw builds of NUT for Windows. Apparently its visibility was different from plain C builds, and never tried for C++ before.
Notable changes include patterns printed by the driver startup - now it would be NUT version info description first, then driver name and info. Previously it was driver name+version and short NUT version in parentheses afterwards (so could have double parentheses with development builds). Also the `-V` request for version would not report `upsnotify` (mis-)configuration concerns.
Also `nut-scanner` now shows its name in the banner, and `upsdrvctl` remains a bit special to clarify that …
=> Fix uses of `banner_is_disabled()` to not preclude `-V` printouts; common formation of the banner string; better detection of `time.h` methods

NEWS.adoc, data/driver.list.in, drivers/mge-hid.c
Also handle "unknown 2000" assuming it is a mis-read "Eaton 9E 2000(i?)" which refused to tell libusb its vendor/product/serial strings. Although note that if we were not able to read basic identification data, chances of really interacting with the device are... sketchy.
This may be the answer to such issues as #1925, #2380 (re-opened), #2492
To recap, reported issues were (at least):
* "unknown 2000" as the `device.model` and `ups.model`
* missing serial number info
* ...which may be due to inability to get identification data from `nut_libusb_open()`, even when NUT runs as `root` (but maybe is somehow restricted being in a container?)
* ...which is discovered by `lsusb` on the same box, by `udevadm info`, and by `apcupsd` it seems
* `battery.type` is present but has no value
* not sure …
=> drivers/mge-hid.c, NEWS.adoc: try to recognize Eaton 9E model and info

scripts/fuse/README.adoc, scripts/fuse/execfuse-nut/getattr, scripts/fuse/execfuse-nut/read_file, scripts/fuse/execfuse-nut/readdir
Also separate "client-location" from "client-version", and update the README with some nuances.
Follows-up from issue #2591 and PoC PR #2592
=> Follow-up for the FUSE PoC: integrate with `make check-NIT` prepared sandboxes

NEWS.adoc, scripts/systemd/Makefile.am, scripts/systemd/nut-driver-enumerator-daemon-activator.service.in, scripts/systemd/nut-driver-enumerator-daemon.service.in, scripts/systemd/nut-driver-enumerator.path.in, scripts/systemd/nut-driver-enumerator.service.in, scripts/systemd/nut-driver.target, scripts/systemd/nut-driver@.service.in, scripts/systemd/nut-monitor.service.in, scripts/systemd/nut-server.service.in, scripts/systemd/nut-sleep.service, scripts/systemd/nut.target, scripts/systemd/nutshutdown.in
> Introduced a `nut-sleep.service` unit which stops `nut.target` when a system sleep was requested, and starts it when the sleep is finished.
> This helps avoid NUT shutting down a woken-up system just because its power state was critical before the sleep (called as a `SHUTDOWNCMD` implementation by the end-user), and a next-read timestamp was not seen (deemed to be a stale UPS, meaning lost communications during critical state, so must go down ASAP). While not as elegant as native systemd "inhibitor interface" support, this approach does work.
Follows up on issues:
* #1833 - thanks to @Ropid for posting their unit file in a comment, which served as the basis for this PR
* #1070
Also bumps (C) years for unit files in the directory.
=> Introduce `scripts/systemd/nut-sleep.service` unit

drivers/main.c
only apply the defaults for `driver.flag.allow_killpower` when `allow_killpower` flag was not already set.
current state applies defaults regardless of this, overwriting a previously set `allow_killpower` flag with `0`.
fixes #2605 , tested and working with APC device using `usbhid-ups` on Slackware 15.0 w/ gcc 11.2.0.
=> drivers/main.c: do not overwrite set allow_killpower flag with defaults

NEWS.adoc, tests/NIT/nit.sh
While on the road, it is fun to build and test NUT in the TermUX (Debian-like userland) app on a phone.
But there are some caveats to pass the `make check-NIT` due to (in-)visibility of open ports...
=> CI: pass NIT on android

NEWS.adoc, drivers/usb-common.c, m4/ax_realpath_lib.m4, tools/nut-scanner/scan_usb.c
Partially addresses #2615 (the part for `nut-scanner` scope), follows-up from PR #2604.
Beside porting the method proposed by @tormodvolden in #2604 for `usb-common.c`, there were some other methods used by it that needed porting from libusb headers (inline, not dynamic symbols).
Checked with libusb-0.1 and libusb-1.0 builds on a physical machine, that the resulting `nut-scanner -U` still finds an Eaton USB UPS (although with model not impacted by the issue from #1925 / #2604).
Also found and fixed a problem with stashing of SOPATH and SONAME for libraries seen during build (so `libnutscan` would search for those exact filenames first), as this did not play well with the few "GNU ld script" files instead of binary dynamic libraries, as found on the tested system. Probably can be seen as a …
=> Port and use a variant of `nut_usb_get_string()` for `nut-scanner`

docs/man/nut_usb_addvars.txt
First shot at issue #2616, but not "closing" it because a more consistent solution would involve programmatic (run-time) debugging setting for the libusb context instance used, and probably a `driver.debug.libusb` run-time variable. Sometime in the future...
=> docs/man/nut_usb_addvars.txt: make a NOTE of LibUSB specific debugging

Makefile.am
Follow-up to: #1936
Avoid occasional AppVeyor CI hiccup with:
````
...
CHECKING if any executable files were installed to locations other than those covered by this recipe, so might not have needed DLLs bundled near them
./mingw64/libexec/sockdebug.exe
make[1]: *** [Makefile:1644: install-win-bundle-thirdparty] Error 1
make: *** [Makefile:1638: install-win-bundle] Error 2
````
=> `Makefile.am`: `install-win-bundle-thirdparty` DLL check: cover `libexecdir`

NEWS.adoc, docs/nut.dict, drivers/libusb0.c, drivers/libusb1.c
With an Arduino Leonardo compatible board attached alongside a CyberPower CP1500PFCLCD, usbhid-ups would incorrectly conclude that there was no kernel driver attached to the UPS and then fail subsequent steps accordingly.
The cause is the global usb_communication_subdriver_t struct; when a subdriver (e.g. arduino-hid) sets different values during the enumeration loop, they're not set back to defaults afterwards, causing issues with other subdrivers (e.g. cps-hid).
So, if a subdriver doesn't match, set a selection of fields back to their default values using the newly added nut_usb_subdriver_defaults() before the next attempt.
a functional change. …
=> drivers/libusb{0,1}.c: reset driver parameters while enumerating

docs/man/usbhid-ups.txt
passed `make spellcheck`, took me longer than i wanted to find this pretty useful setting and its related issue 😆 
fixes #2356 , also checked for other missing `usbhid-ups` arguments while at it - looks like none are missing.
=> docs/man/usbhid-ups.txt: add missing lowbatt argument

NEWS.adoc, data/driver.list.in, docs/man/Makefile.am, docs/man/liebert-gxe.txt, docs/nut.dict, drivers/Makefile.am, drivers/liebert-gxe.c, drivers/ydn23.h
Product Breif: https://www.vertiv.com/4a3d25/globalassets/products/critical-power/uninterruptible-power-supplies-ups/vertiv-liebert-gxe-1000-3000va-racktower-230v-single-phase-ups/vertiv-liebert-gxe-datasheet-en-emea---mka4l0ukvlg.pdf
This UPS has a RS232 port and a USB port. The USB port has an ACM interface which functions as a serial port. Both ports can be used managing the device.
(`nutdrv_qx`, `usbhid-ups`...) or …
=> Support for Liebert GXE 1-3KVA series

NEWS.adoc, conf/ups.conf.sample, docs/man/nut_usb_addvars.txt, docs/man/ups.conf.txt, drivers/main.c, include/nutconf.hpp
Addresses part of #2616
A quick hack for that issue, to `setenv()` the envvar during configuration parsing, so hopefully the library would see it:
````
:; ./drivers/usbhid-ups -a eco650 -x LIBUSB_DEBUG=qqq -d 1
Network UPS Tools 2.8.2.1082.2-1084-g0520091ac (development iteration after 2.8.2) - Generic HID driver 0.57
USB communication driver (libusb 1.0) 0.49
WARNING : Invalid LIBUSB_DEBUG value found in ups.conf for the driver, defaulting to 4
Enabling LIBUSB_DEBUG=4 from ups.conf
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000011] [001a9956] libusb: debug [libusb_init] created default context
[ 0.000019] [001a9956] libusb: debug [libusb_init] libusb v1.0.24.11584
... …
```
=> Support `LIBUSB_DEBUG=NUM` setting in `ups.conf`

NEWS.adoc, docs/nut.dict, drivers/mge-hid.c
As explained here:
https://github.com/networkupstools/nut/issues/2661#issue-2593677212
This is a request to add suport for ups.beeper.status feature for Masterpower MF-UPS650VA
The only change is to find it in a different path from the already two paths supported.
Thanks
Best Regards,
yonesmit
=> Update mge-hid.c: Added ups.beeper.status support for Masterpower MF-UPS650VA

drivers/ydn23.h
Fix a bad checksum in length field. However, `liebert-gxe' was not affected because the frame never exceeds 2^4-1.
case.
(several …
=> drivers/ydn23.h: fix bad lchksum

NEWS.adoc, UPGRADING.adoc, configure.ac, docs/config-prereqs.txt, docs/configure.txt, drivers/apc_modbus.c, m4/nut_check_libmodbus.m4, m4/nut_report_feature.m4
...and allow users to require `configure --with-modbus+usb` to avoid surprises with a wrong choice of the library.
Should help with investigation for #2666 and fixes a bug detected in that discussion.
Also revise configuration script report.
Closes: #2676
Example runs with failsafe firing (where the OS has a packaged standard shared libmodbus; a custom static build with USB support is installed into `--prefix=/tmp`)
NEGATIVE CASES
* Use new options and cause use of OS-provided library (by default):
````
:: ./autogen.sh && ./configure --with-modbus+usb
````
* Legacy common case: explicitly request `apc_modbus` and `libusb` among `configure` options (and still use OS-provided library):
````
:; ./configure --with-drivers=apc_modbus --with-usb
````
* Legacy common case: explicitly request …
=> Fix (re-)detection of libmodbus RTU USB support with static libmodbus builds

NEWS.adoc, docs/man/usbhid-ups.txt, drivers/usbhid-ups.c, include/nutconf.hpp
Now users of devices that can be caught hanging out and slacking off by a continuous stream of "Got 0 HID Objects" from interrupts can configure a toggle to say how much is enough, and reconnect the driver. Legacy default is to not bother, and assume the device just has nothing to urgently report.
Closes: #2681
Follow-up to: #2671
CC for testing: @desertwitch @masterwishx @michal4132
=> Fix fallout of #2671 and complete the feature with optional `interrupt_pipe_no_events_tolerance` setting

NEWS.adoc, common/common.c, docs/nut.dict, include/common.h
Follow-up for PRs #1590, #2136
* introduce `str_upsnotify_state()` for meaningful debug log messages;
* suggest to `export NUT_QUIET_INIT_UPSNOTIFY=true` where we "will not spam more about it" for systems that do not currently expect to have notification support or need
=> common/common.c, include/common.h: follow-up for `upsnotify()`

drivers/mge-hid.c
As add-on for https://github.com/networkupstools/nut/pull/2637 ECO/Bypass for Eaton Models
we can leave as is now only check range by r/w values or set also check range for eco/bypass by commands .
Also we can add ESS Mode staff (check range and set ups status) like in ECO mode
if it needed .
But only Eaton Models like `93PM G2` and `9395P` use ESS , not sure if they use NUT :)
=> Work247-ecomode_addon

drivers/libusb1.c
cf github #2401 
When global var 'interrupt_size' is not set, a transfer size of SMALLBUF (512) is requested when calling libusb_interrupt_transfer(). Our function nut_libusb_get_interrupt() should return the actual transferred size. Otherwise, the caller will attempt to parse any uninitialized data in the buffer after the response.
In libusb0.c this was done correctly by using the return value of usb_interrupt_read(). With libusb1, the transferred size is written to tmpbufsize, and should therefore be used as the return val.
***************
can we trust libusb to not return a value outside the range of `usb_ctrl_charbufsize` ? I did not add a check for this and simply cast the int. [edit - as noted in the review comments, this condition is already checked... 4 lines above)
=> drivers/libusb1.c: fix wrong return value of nut_libusb_get_interrupt()

docs/developers.txt, docs/nut.dict
Inspired by question in #2689
Follows up from #823 et al
=> docs/developers.txt: clarify pragmas in switch/case/default vs. enum

NEWS.adoc, drivers/dstate.c, drivers/libusb0.c, drivers/libusb1.c
The original message was misleading in some cases, as seen in https://github.com/networkupstools/nut/issues/2661#issuecomment-2505942832 - a device was accessible and attempted, but did not match. The logged message that the users see without bumping debug is however that nothing was accessible.
=> `drivers/libusb{0,1}.c`: Revise "insufficient permissions on everything" messages

drivers/mge-hid.c
Eaton 9SX/9PX Fix for battery.voltage and battery.voltage.nominal by adding 9SX/9PX model to mge_model_names []
Fix #2685
=> Eaton 9SX/9PX Fix for battery.voltage

scripts/python/app/NUT-Monitor, scripts/python/app/NUT-Monitor-py2gtk2.in, scripts/python/app/NUT-Monitor-py3qt5.in
Primarily an aid in portability for development (to run directly the UI script like `$PYTHON3 ./NUT-Monitor-py3qt5.in`) and also can help final deployments. Maintains and improves preference for an accompanying version of `PyNUT.py` (over an installed module, if any) if one is in a sibling directory near the application.
Side note: tested with a Linux-configured build directory on Windows, the UI client works and talks to a NUT server on Linux.
=> NUT-Monitor UI and PyNUT: better support for relative path to module, better detect usable interpreter

drivers/mge-hid.c
follow-up for #2660 
as explained in https://github.com/networkupstools/nut/pull/2660/files#r1838070677
The current state suggests we're sure about the principle and values of `UPS.BatterySystem.Charger.ChargerType` and that ABM-enabledness deductions could (theoretically) also be made from this HID path in the future. I've amended that in this PR, so that the current state of investigations is reflected in a separate in-depth comment, as to avoid future development going down a possibly wrong path due to what were perhaps premature assumptions on our part. 😉
=> drivers/mge-hid.c: comment regarding ChargerType

NEWS.adoc, drivers/phoenixcontact_modbus.c
Updated Phoenix Contact modbus driver for newer models which are using different modbus addresses. Choice is made basing on the UPS firmware version and the model information have been changed in order to have a quick feedback over the new/old model detection.
=> Updated Phoenix Contact modbus driver for newer models

tests/nutipc_ut.cpp
POSIX does not require 1:1 delivery per kill() call.  Adjust the test to not require behavior that 1) POSIX does not require and 2) is only probabilistically observed to happen, even if "most of the time".
The test previously sent signals as rapidly as possible, observed to be on the order of 100 us via ktrace.   Sometimes, a signal sent twice was delivered once.  This is legal, and it is an error to rely on this.
This commit adds comments discussing signal semantics.  It adds a delay between some signals, to allow time for delivery.   We consider a system which does not deliver signals within 1 s to be deficient.
=> tests: Do not expect signals to be messages

NEWS.adoc, drivers/cps-hid.c
Kudos to Cyber Energy (affiliate of CPS) per https://alioth-lists.debian.net/pipermail/nut-upsdev/2024-December/008069.html
=> drivers/cps-hid.c, NEWS.adoc: add ups.temperature [#2711]

data/cmdvartab, docs/nut-names.txt, docs/nut.dict
Adding some missing description for cmdvartab and nut-names.txt.
After @desertwitch (nut plugin for Unraid developer) kindly added new future (show description form cmdvartab on hover for nut variables) asked by me, found some of them missing description.
=> add-missing-vars-desc

docs/new-drivers.txt, docs/nut-names.txt, drivers/nhs_ser.c
Follows up from #2692
CC @Challado - testing on HW would be welcome, to make sure nothing got broken by this reshuffle
Is my understanding correct that in your code, the first call to `upsdrv_updateinfo()` would read nothing good from the wire and have no good checksums in "last" packet structs, so it would issue calls at the end of the method ("pkt_hwinfo loss -- Requesting") to get the HW info (and you mentioned there may be a couple of seconds before it replies - so the next cycle via `main.c` picks up that bit-stream)? Does this also trigger appearance of Data packet readings, or does the UPS just regularly send those?
Here the primary change was moving the code around for conformance to NUT driver design and general maintainability - primarily reduced indention level and improved …
=> Refactor `nhs_ser` driver

NEWS.adoc, drivers/cps-hid.c, drivers/hidparser.c, drivers/hidtypes.h, drivers/usbhid-ups.c
…interruptsize and interruptonly before comm_driver->open_dev() [#1512, #1575]
Follows up from PR #1245 that addressed #439 and a ton of related issues.
=> `usbhid-ups` generally: apply disable_fix_report_desc…; `cps-hid`: fix mismatched LogMax between input/output voltages (bad encoding)

NEWS.adoc, data/driver.list.in, docs/nut.dict, drivers/mge-hid.c, scripts/upower/95-upower-hid.hwdb
Closes: #2661
Note: previously same model names also manufactured by KSTAR were using MGE USB VendorID (0x0463).
Also note that per #230 some devices with this ID could use Megatec Qx protocol family instead.
=> usbhid-ups: added support for 0x09d6:0x0001 (KSTAR) UPSes using MGE HID

m4/nut_check_libavahi.m4, m4/nut_check_libfreeipmi.m4, m4/nut_check_libgd.m4, m4/nut_check_libgpiod.m4, m4/nut_check_libmodbus.m4, m4/nut_check_libneon.m4, m4/nut_check_libnetsnmp.m4, m4/nut_check_libnss.m4, m4/nut_check_libopenssl.m4, m4/nut_check_libpowerman.m4, m4/nut_check_libregex.m4, m4/nut_check_libsystemd.m4, m4/nut_check_libusb.m4
Part of investigation for #2289
=> m4: revise libmodbus detection

scripts/Windows/README.adoc
Follows up from proposed PR #2736 and earlier discussion in #2724
=> Windows cross build documentation cleaned

drivers/liebert-gxe.c
It seems `battery.runtime` should be used for battery backup time instead of `.low` one. Also the division was also faulty probably because I copied and pasted the code from previous lines but the manual says it shouldn't be there.
The commit should give correct backup time readings and corrected variable name.
Follow-up from: #2629 and #2669
=> drivers/liebert-gxe.c: fix bad backup time report

NEWS.adoc, UPGRADING.adoc, clients/Makefile.am, clients/upslog.c, docs/man/upslog.txt, scripts/systemd/nut-logger.service.in, tests/NIT/nit.sh
=> Revise `upslog` service integration, allow to limit loop count, use it in NIT

NEWS.adoc, drivers/cps-hid.c
Closes: #2717
Some CPS devices report frequency off by a factor of 10 (also in the vendor's own `pwrstat` tool) as e.g. `499.0`. This PR should try to detect the scaling range and adjust the reading.
EDUCATED GUESS: Probably the underlying problem is a yet another mis-use of USB HID report format, with an interim change to reporting in 0.1HZ units in some firmwares, but not updating the exponent in the report.
=> drivers/cps-hid.c, NEWS.adoc: try to fix frequency scaling dynamically

NEWS.adoc, drivers/main.c
=> When starting a driver program to force UPS shutdown, kill off running siblings

NEWS.adoc, docs/nut.dict, m4/nut_check_libnetsnmp.m4, scripts/Windows/.gitignore, scripts/Windows/README.adoc, scripts/Windows/build-mingw-nut.sh
* Added docs on custom-building cppunit (questionable usefulness though specifically for Windows cross-builds from Linux, but can help other platforms where it is lacking from packaging)
* Found that earlier work broke discovery of libnetsnmp (where static variant was needed) with mingw
* Extended build and install areas to be named with their `$ARCH` in mind, so 32/64-bit builds are easier to compare during investigations
=> Fix NUT for Windows build

INSTALL.nut.adoc, Makefile.am, NEWS.adoc, configure.ac, docs/config-notes.txt, docs/config-prereqs.txt, scripts/Solaris/Makefile.am
Addresses: #1298
More or less follows documentation for manual NUT installation, wiki suggestions and what some existing packaging scripts do. Should help in-place upgrades of various nature; maybe initial installations too (user/group should be pre-made)...
After doing the work and some thinking, I believe this is a step in direction of providing reference packaging recipes for NUT in the codebase (see #1209 etc.) and the code added to `Makefile.am` now is better pushed out into scripts like `scripts/Solaris/postinstall` eventually - with better guaranteed availability of tooling, use of correct commands, etc. especially as this gets routine ported to various distributions.
=> Makefile.am, configure.ac, NEWS.adoc: implement `make install-as-root` [#1298]

appveyor.yml, scripts/Windows/build-mingw-prereqs.sh
The MSYS2 repo seems confused about versions of GDB it can install right now, and we do not really care about it there, so pre-remove it for now.
=> Fix Appveyor CI builds

NEWS.adoc, UPGRADING.adoc, scripts/python/README.adoc, scripts/python/module/Makefile.am, scripts/python/module/README.adoc, scripts/python/module/setup.py.in
Closes: #2773
Example upload with these changes in place: https://test.pypi.org/project/pynutclient/2.8.2.1915.3/
CC @mtelka
=> Fix PEP-0625 naming for PyNUTClient tarball

Makefile.am, ci_build.sh, configure.ac, docs/config-prereqs.txt, docs/nut.dict, m4/nut_check_libltdl.m4, tests/Makefile.am, tools/gitlog2version.sh
Previously there was a lot of smart guesswork applied to `PKG_CONFIG_PATH` on illumos/Solaris, and various tuning around `HOMEBREW_PREFIX` with MacOS, done in `BUILD_TYPE=default*` test cases, but not in developer-oriented build with an empty `BUILD_TYPE` or in-place builds for end users.
This PR moves into methods and revises that guesswork logic, allowing its re-use in both major use-cases.
As a practical benefit, builds on OmniOS where most of the non-core software is in "Extra" package repository installed under `/opt/ooce`, dependencies such as `libusb-1` are much easier to find and actually use. Similar approach might apply to pkgsrc or similar popular alternative ecosystems.
UPDATE: Notes below are off-loaded into issue #2782 to address separately.
Note this does not at the moment …
=> Fix `ci_build.sh` auto-detection of paths and flags for trickier distros

common/nutstream.cpp, configure.ac, drivers/generic_gpio_common.c, drivers/generic_gpio_common.h, scripts/valgrind/.gitignore, scripts/valgrind/.valgrind.supp, scripts/valgrind/README.adoc, scripts/valgrind/valgrind.sh, scripts/valgrind/valgrind.sh.in, tests/Makefile.am, tests/generic_gpio_utest.c, tests/nutconf_ut.cpp
Follows up from #2781 
Some fixes are for valgrind suppression rules to not complain about CPPUNIT per se, others are actual bugs found in code.
=> Fix `make memcheck`

NEWS.adoc, docs/nut.dict, drivers/Makefile.am, drivers/baytech-rpc3nc-mib.c, drivers/baytech-rpc3nc-mib.h, drivers/snmp-ups.c
Some models of Baytech RPC3-NC PDUs do not have a value at ".1.3.6.1.4.1.4779.1.3.5.2.1.24.1", causing the sysOID match to fail. Added a 2nd MIB that looks at ".1.3.6.1.4.1.4779.1.3.5.5.1.3.2.1" instead.
This patch would fall under the "various RPC" entry in the hardware compatibility list, thus the list does not need updating.
I was unable to run `make distcheck`, it appears to require quite a few dependencies that are not on my system.
=> feat: add SNMP support for Baytech RPC3-NC PDUs

Jenkinsfile-dynamatrix, ci_build.sh, configure.ac, docs/config-prereqs.txt, drivers/libusb1.c, drivers/nut-libfreeipmi.c, drivers/optiups.c, drivers/powerman-pdu.c, m4/nut_check_libopenssl.m4, m4/nut_compiler_family.m4, scripts/Windows/build-mingw-prereqs.sh, tools/nut-scanner/scan_ipmi.c
Updated more platform builders to clang-19...
#823 never stops :)
=> Various small CI fixes

NEWS.adoc, docs/Makefile.am, docs/man/sms_ser.txt, docs/sms-brazil-protocol.txt, drivers/main.c
Also test updates of CI farm :)
=> Fix sms-brazil-protocol and sms_ser docs markup; quiesce driver service framework notifications when exiting due to bad CLI args

Makefile.am, ci_build.sh, configure.ac, docs/Makefile.am, docs/man/Makefile.am, docs/man/nut_usb_addvars.txt, docs/man/ups.conf.txt
* Follow-up to PRs for #722 : adjust man-page URL for "NUT home page" in release snapshots (use historic sub-site as `NUT_WEBSITE_BASE`)
* Improve `ci_build.sh` to help iterate with docs and their recipes
* Fix the general build routine to complete all requested doc types as part of build (previously some were not built until `make dist` or `make check`, effectively because `make man` in `docs` directory was satisfied that `man` subdir exists)
* Revise recipes to pass asciidoc/a2x CLI arguments in the same style (also done in nut-website recipes)
=> More fixes to docs markup, recipes, scripting

NEWS.adoc, appveyor.yml, docs/new-drivers.txt, drivers/bestfortress.c, drivers/dstate.c, drivers/liebert-gxe.c, drivers/main.c, tests/.gitignore, tests/Makefile.am, tests/driver_methods_utest.c, tests/generic_gpio_utest.c
Addresses part of issue #2708: cleans up some drivers to not use spaces, and for those where not easily avoidable (e.g. `snmp-ups` where strings come from mapping tables) tolerates them better by recursing into self for each found token (avoid duplicates).
Also fixes one bug with `status_get` checks added in #2565 (and maybe there's another, see below).
TODO: this is a relatively hot code path, some optimization may be useful:
* optimize recursion to not `strcmp` for space again when we know it is not there, maybe use a public wrapper method vs. implem with more args, or moving this logic into a new method for use-cases where we do not pass known-clean verbatim strings
* for `status_get` checks, avoid long repetitive string walks (keep an array of offsets to starts/ends of tokens in one …
=> Fix handling of spaces in driver `status_set()` args

drivers/nutdrv_qx.c, drivers/nutdrv_qx.h, drivers/nutdrv_qx_q2.c
New Q2 and Q6 protocols work like a charm - just tested thoroughly on my Innova RT 3/1 and all looks good! However, I've figured out that my translation/interpretation of original Santak's documentation was wrong at least in one place - Q2 request tells estimated battery runtime in minutes rather than seconds. This PR is for fixing this mistake
=> Fix battery runtime calculation for Q2 protocol

NEWS.adoc, UPGRADING.adoc, docs/nut.dict, drivers/netvision-mib.c
Hello
We have servers powered from two MASTERYS 3/3 SYSTEM 60 kVA UPSes, with some of them with redondant power supplies from both UPSes.
After a power failure, the batteries went low and the UPSes cut outputs. Everything worked as expected for hosts with a single
power source, but not for those with redondant power. After the first UPS went down, upsmon started reporting this UPS
as being at the same time OL and OB (and not LB any more):
Feb 11 08:52:27 localhost upsmon[2175]: UPS ups-1@localhost battery is low
Feb 11 08:56:23 localhost upsmon[2175]: Giving up on the primary for UPS [ups-1@localhost] after 241 sec since last comms
Feb 11 08:56:28 localhost upsmon[2175]: Giving up on the primary for UPS [ups-1@localhost] after 246 sec since last comms
Feb 11 08:56:33 localhost …
=> netvision-mib: sync netvision_output_info with SOCOMECUPS-MIB.txt

Makefile.am, NEWS.adoc, ci_build.sh, clients/Makefile.am, common/Makefile.am, common/setenv.c, configure.ac, docs/Makefile.am, docs/configure.txt, docs/nut.dict, drivers/Makefile.am, include/Makefile.am, lib/.gitignore, lib/Makefile.am, lib/libnutconf.pc.in, scripts/Windows/build-mingw-nut.sh, server/Makefile.am, tests/Makefile.am
This PR follows up from #2825 to complete a feature originally tried there but excised due to added complexity/instability of original PoC builds. Also updates bits of documentation and general Makefile markup here and there, and presumably fixes a presumably broken delivery of some source files into "dist" archives in certain build circumstances.
The `libnutconf` library was until now treated in recipes as an internal detail of the `nutconf` tool, added to main codebase in PR #2283 and refined later on. However for third-party integrations it may be (or not be) interesting to experiment with use of the library as such, rather than calling the command-line tool (which allegedly provides a more stable API for integrations). IMHO there's too much placed into the header files for it to be …
=> CI: Fix configure.ac and Makefiles to deliver libnutconf (optionally)

NEWS.adoc, configure.ac, docs/nut.dict, drivers/generic_gpio_libgpiod.c, drivers/generic_gpio_libgpiod.h, m4/nut_check_libgpiod.m4, tests/Makefile.am, tests/generic_gpio_liblocal.c, tests/generic_gpio_utest.c
Closes: #2833
API of the library has massively changed between 1.6.x available in older distros, and 2.x in newer ones (and matching Linux kernel functionality changed a lot as well). The driver was not buildable in newer/upcoming distribution releases because of that.
Great thanks to @modrisb for initial driver development, and for this subsequent fix (on short notice at that). And to @tomeko12 for raising the alarm :)
For my part, it should now be easy to identify which API (1 or 2) the program got built against:
```
:; ./drivers/generic_gpio_libgpiod -V
Network UPS Tools 2.8.2.2324.5-2329-g03947d319 (development iteration after 2.8.2) - GPIO UPS driver (API 0x00020000) 1.03
:; ./drivers/generic_gpio_libgpiod -V
Network UPS Tools 2.8.2.2327.5-2332-g4940ab008 (development iteration after …
```
=> Fix `generic_gpio_libgpiod` driver builds with libgpio 2.x API changes

NEWS.adoc, UPGRADING.adoc, data/driver.list.in, docs/nut.dict, drivers/nutdrv_qx.c
As I found, in **hunnox_protocol** on step 3 and `asking_for = x0c` it tried to read some string (vendor data by protocol), but ups didn't provide this data and because empty value on next step it cause crash of ups logic and it are stops response.
As I found, it should be solved by use **novendor**, that was used in **blazer_usb**, I added use it in **nutdrv_qx**, but not sure if it will not broke other working setup. Please suggest better solution for it.
=> use novendor param as flag for don't read vendro name, need for dexp ups

data/driver.list.in, drivers/nutdrv_qx_gtec.c
A few small fixes of the GTEC driver: only letters for online/offline/bypass status are mutually exclusive, other states like low battery can be reported in addition to them. Also add alarm when battery is disconnected and set _replace battery_ status when battery test had failed.
Follow-up to: #2818
=> drivers/nutdrv_qx_gtec.c: multiple status letters can be reported at once

NEWS.adoc, configure.ac, lib/libnutclient.pc.in, lib/libnutclientstub.pc.in, lib/libnutconf.pc.in, lib/libnutscan.pc.in, lib/libupsclient-config.in, lib/libupsclient.pc.in, m4/ax_realpath_lib.m4
Another side of the coin raised by issue #2782 : when we install NUT itself, especially its libraries into uncommon paths like `/usr/local/ups/lib`, third-party progs linked against them can not find them at run-time: the RPATH or RUNPATH has to be embedded (which is what this PR helps with), or LD_LIBRARY_PATH or equivalent frowned-upon tricks should be done.
=> Optionally suggest rpath for NUT libraries for third parties

.gitignore, Makefile.am, NEWS.adoc, docs/Makefile.am, docs/man/Makefile.am
* Benefit from more-parallelized runs in `make spellcheck` too by default, following up from work done in #2825
* Some mode bits were planned but misfired, delayed for further commits
=> Optimize parallel spellcheck some more

scripts/external_apis/enphase/enphase-monitor.in, scripts/external_apis/enphase/enphase-monitor@.service.in
Floats <1.0 were being handled as octal, corrected to use decimal. This resulted in incorrect calculations, and could result in "value too great for base" bash errors.
Corrected path substitution in enphase-monitor service file.
=> scripts/external_apis/enphase - correct number conversion, service file

docs/config-prereqs.txt, drivers/asem.c, drivers/generic_gpio_libgpiod.c, drivers/hwmon_ina219.c, tests/generic_gpio_liblocal.c, tests/generic_gpio_utest.c, tools/nutconf/nutconf-cli.cpp
Added a Debian 13 build agent (LXC container) to the NUT CI farm. The system has a few differences from Debian 12, notably mis-detection of systemd directories (new prereq package needed), and more complaints from its brew of clang-19 static analysis.
CC @axet
=> Fix build on Debian 13

scripts/external_apis/enphase/enphase-monitor.in
Negative floats, and floats 0.08/0.09 were resulting in invalid octal numbers (Hopefully this handles the last edge cases for converting floats->int in bash :)
The envoy API occasionally stalls; extended timeout to 10s and added a single retry to avoid spurious "nocomms" state.  My envoy seems to stall out at least once a day, probably when the API query coincides with it "reporting in" or querying all the micro-inverters...  Using a 10s timeout seems to be in sync with the other client timeouts...
=> scripts/external_apis/enphase: correct neg number conversion, retry api

drivers/hwmon_ina219.c, drivers/nutdrv_qx.c
There should have been a message since v2.8.0 or so, but this one clarifies the situation even further (see the now-two WARNING entries below):
````
:; NUT_STATEPATH=/tmp ./drivers/nutdrv_qx -s test -x vendorid=1234 -x port=/dev/ttyUSB0
Network UPS Tools 2.8.3.85-85+g5d3ff46f9 (development iteration after 2.8.3) -
Generic Q* USB/Serial driver 0.42
USB communication driver (libusb 1.0) 0.50
WARNING: port='/dev/ttyUSB0' would be ignored, since other options indicate USB mode
WARNING: warn_if_bad_usb_port_filename(): port argument specified to
the driver is "/dev/ttyUSB0" but USB drivers do not use it and rely on
libusb walking all devices and matching their identification metadata.
NUT documentation recommends port="auto" for USB devices to avoid confusion.
libusb1: Could not open any HID …
```
=> Clarify message for `nutdrv_qx` mismatch of `port!="auto"` and presence of USB settings

NEWS.adoc, server/upsd.c
Fix issue #2914: malformed warning message and possible buffer overflow in upsd.
=> Fix issue #2914: upsd misprint/buffer overflow.

NEWS.adoc, drivers/cps-hid.c
fix #2917 
Findings in the linked issue suggest that at least one model in the `cps_fix_report_desc` model range suffers also from a broken descriptor for reporting the UPS nominal power (`ConfigActivePower`). The value seemingly gets correctly sent by the UPS, but is then clipped by a too low `LogMax` of that affected descriptor:  [nut-issue-2917.log](https://github.com/user-attachments/files/19923182/nut-issue-2917.log)
```
Apr 26 08:43:04 Tower rc.nut:    0.035598#011[D3:181672] Report[get]: (3 bytes) => 18 fe 01
Apr 26 08:43:04 Tower rc.nut:    0.035600#011[D5:181672] PhyMax = 0, PhyMin = 0, LogMax = 450, LogMin = -1
Apr 26 08:43:04 Tower rc.nut:    0.035601#011[D5:181672] Unit = 0000d121, UnitExp = 7
Apr 26 08:43:04 Tower rc.nut:    0.035602#011[D5:181672] Exponent = 0
Apr 26 …
```
=> drivers/cps-hid.c: add report descriptor fix for ConfigActivePower

configure.ac, scripts/Windows/dllldd.sh, tools/gitlog2version.sh
grep/sed on illumos dislikes `(|token)`
=> Fix shell regexes with empty (part of) expectation for portability

NEWS.adoc, configure.ac
Fixes: #2927
Fallout-of: #2825
* Introduce recursive evaluation of `Makefile.am` variables while we search the driver lists for program names - so now we do not get a dollar-token (sans the dollar) in the output, and then a driver name unknown for the build request.
* Ignore the `$(EXEEXT)` that was tacked to `dummy-ups` specifically to solve the problems PR #2825 addressed.
=> Fix `configure --with-drivers=dummy-ups`

NEWS.adoc, UPGRADING.adoc, data/driver.list.in, docs/man/usbhid-ups.txt, docs/nut.dict, drivers/usbhid-ups.c
PR #2565 addresses issue #2347 wherein APC BXnnnnMI devices are logging LOWBATT/REPLACEBATT messages.
BVK750M2 (which appears to have been released 2021/2022) appears to be affected by this, at least the one that I purchased 1Q 2025 in the US.
Other models in this lineup per APC's product brochure are BVK950M2 and BVK1200M2.
This PR does the following:
- addresses #2942 
- updates `upshid-ups.c` to add APC BVKnnnnM2 to the detection code and also increments the driver version number 
- updates `NEWS.adoc` to note the update
- updates `UPGRADING.adoc` to note the update
- updates `driver.list.in` to add the model
- updates `usbhid-ups.txt` to add the model
Comments, suggestions, corrections, testers?  Apologies if I missed anything as I'm relatively a novice at this.  Thank you, and a big …
=> Add APC BVKnnnnM2 to list of devices affected by spurious LB/RB messages

AUTHORS, NEWS.adoc, data/cmdvartab, data/driver.list.in, docs/Makefile.am, docs/man/Makefile.am, docs/man/nutdrv_hashx.txt, docs/nut-names.txt, docs/nut.dict, drivers/Makefile.am, drivers/nutdrv_hashx.c, drivers/skel.c
From the main commit:
```
Add an initial driver for the "#*" protocol support that is used by many
UPS out there that rely on the proprietary software suites PowerMaster+,
PowerMaster, PowerGuide and so on...
The naming of the driver has been chosen since all the UPS replies start
with an "#", while there's not a definitive common pattern for the queries
or commands.
Apparently the same protocol is used by various UPS devices, both online
and line-interactive (given that many producers advertise to use the
said programs), and only in serial mode (AFAIK). Although this driver has
solely been tested with the Atlantis Land S1200 line-interactive UPS.
So there may be missing features (such as the bypass mode) or lack of
information. However most of the decoding has been done and the driver
is …
```
=> drivers/nutdrv_hashx: Add new driver for PowerManager+ serial supported devices

Makefile.am, data/.gitignore, data/Makefile.am, data/driver.list.in, tools/Makefile.am, tools/driver-list-format.sh
We already had the `tools/driver-list-format.sh` script since 2016 ed7a2ded00 (ported from 2015's f77974cc13 origins in `configure.ac`) that "ensured" the format of `data/drivers.list(.in)` files to have TAB-separated fields, by editing the files (and always succeeding). This was only called as part of `make dist` and adjusted the published files (with no enforcement that original git sources changes should get committed if the script edits anything).
This PR revises the script to also have a `--check` mode, so developers can see any added discrepancies as part of `make check`, and are told how to ensure and commit fixes.
It also adds and revises the checks, such as avoiding mix of spaces and tabs (or multiple tabs) as a separator, ensuring the optional comment is also tab-separated from …
=> HCL automation: Driver list markup check

NEWS.adoc, docs/nut.dict, drivers/usbhid-ups.c, drivers/usbhid-ups.h
As raised in https://alioth-lists.debian.net/pipermail/nut-upsuser/2025-May/013964.html mailing list discussion, NUT v2.8.3 refused to command an UPS to shut down, while v2.8.2 was successful (to an extent - a command was at least sent, but the UPS was just beeping). This is a regression due to PR #2860, apparently.
* v2.8.3
````
Hi, my UPS Model Powercom BNT400AP ( made 2017.12 ) on Linux Devuan
Daedalus and NUT v2.8.3 (install from source tarball with "configure
--with-usb --with-user=nut --with-group=nut --with-libusb=1.0
--with-statepath=/run/nut --with-pidpath=/run/nut" options) didn't
shutdown itself after OS is shutting down by signal of UPS battery is low.
...
0.184242     Initiating UPS [UPS] shutdown
0.184257     [D1] loop_shutdown_commands: call
do_loop_shutdown_commands() with …
```
=> Fix `usbhid-ups` instant commands that could work without non-trivial args before NUT v2.8.3

NEWS.adoc, drivers/dstate.c
As recently noted in the mailing list discussion, it is possible to shoot oneself in the foot by pre-creating the state files (e.g. local unix socket) just because driver logs mention that one is absent. This PR should help the users fix their foot back :)
````
:; mkdir /tmp/dummy-ups-test
:; NUT_STATEPATH=/tmp ./drivers/dummy-ups -s test -x port= -DDDDDD
...
1.001350     [D5] send_to_all: SETINFO driver.state "init.quiet"
Fatal error: unable to create listener socket
bind /tmp/dummy-ups-test failed: Address already in use
Things to try:
- ps -ef | grep 'dummy-ups'    (Linux, GNU userland)
- ps -xawwu | grep 'dummy-ups' (BSD, Solaris, embedded)
To check if another copy of the driver is running; if not:
- ls -la /tmp/dummy-ups-test
To check if a (non-socket) filesystem object already …
```
=> Help users address bad state files

Jenkinsfile-dynamatrix, drivers/hwmon_ina219.c, drivers/mge-hid.c, m4/nut_check_libnss.m4, tools/nut-scanner/nut-scanner.c
Some code markup (comment style) issues for C89/ANSI builds were found during a spin-off from #2963 discussion.
This PR started by fixing those, and continued by exploring why our expansive pipeline did not catch that earlier. So the pipeline definition is revised, with some matrix variants dropped from default consideration and others added.
=> Fix source markup for C89 compatibility, revise Jenkinsfile-dynamatrix

drivers/dummy-ups.c, drivers/main.c
I ran into these with a failed `dummy-ups` startup, was not sure if warranting a bumped driver subversion:
- `drivers/main.c`: `splitxarg()` did not free an allocated temporary buffer after either early or normal return from func.
- `drivers/dummy-ups.c`: `upsdrv_cleanup()` mode conditional logic prevented `ctx` to be freed on early stage `fatalx`, before it could be freed in the regular updating loop due to idleness, should be freed regardless of mode if not `NULL`.
```
==2634263== Memcheck, a memory error detector
==2634263== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==2634263== Using Valgrind-3.25.0 and LibVEX; rerun with -h for copyright info
==2634263== Command: /usr/bin/dummy-ups -s abc -x port=auto
==2634263== 
Network UPS Tools 2.8.3.1 (development iteration …
```
=> drivers/main.c, drivers/dummy-ups.c: fix memory issues

Makefile.am, NEWS.adoc, ci_build.sh, conf/upsmon.conf.sample.in, configure.ac, docs/man/index.txt, docs/man/nut.txt, docs/man/upsmon.conf.txt, docs/man/usbhid-ups.txt
The `BUILD_TYPE=default-all-errors ci_build.sh` script handling was revised to simplify code, and to default in CI builds to a quicker mode which randomly mixes the selected SSL, USB and UNMAPPED variants (and relies on the dozens of NUT CI farm runs per iteration to likely cover all possible combinations), which should roughly halve the CI build times. Default activity for developer builds should remain as it was -- to try each such "axis" sequentially.
Also address some older docs deficiencies.
=> Propose a `ci_build.sh` quicker matrix for `BUILD_TYPE=default-all-errors` scenarios

NEWS.adoc, drivers/apc_modbus.c
The delay is supposed to be from *end* of a frame to *start* of the next. Also fix the type used for timestamp calculations (useconds_t is not big enough and overflows).
Fixes one aspect of issue #2609
=> drivers/apc_modbus.c: Fix interframe delay

NEWS.adoc, drivers/bcmxcp.c
=> drivers/bcmxcp.c: fix latched on to RB alarm

NEWS.adoc, drivers/apc-mib.c, drivers/snmp-ups.c
Closes: #3011 
Wondering if `upsdebugx(1, ...)` verbosity level used to report activity on other entry flags would be too "loud" with skipped statics?..
@sirmeili: would you have a chance to test this fix? See e.g. https://github.com/networkupstools/nut/wiki/Building-NUT-for-in%E2%80%90place-upgrades-or-non%E2%80%90disruptive-tests about building custom NUT from sources (using this PR's source branch in my fork, if it is not merged by then). You would probably need to leave the driver running, get a last `ups.test.date` at that time, initiate a test and wait for up to `semistaticfreq` (default 10) update cycles or so to see if the new date value gets reported.
=> `snmp-ups`: debug when static entries are skipped; fix `ups.test.date` in `apc-mib` to be semi-static

Makefile.am
Do not overly trust in `systemctl preset-all`, it fails on systemd 252 (known issue which impacts e.g. whole Debian-based releases stuck with that version):
Failed to preset all units: Unit /run/systemd/transient/session-156053.scope is transient or generated.
See also:
* https://serverfault.com/questions/1054662/systemd-failing-enable-with-service-is-transient-or-generated-whats-wrong-wi
* https://github.com/systemd/systemd/issues/34676
Unfortunately, while those generated units are not related to NUT activities (e.g. auto-mount points), the tool failure does impact this BYOD scenario.
=> Fix `make install-as-root` vs. systemd 252 bug

NEWS.adoc, common/common.c
Follow-up to #2450, raised in discussion for #2956
=> `minimize_formatting_string()`: do not loudly log complaints about known cosmetic formatting chars

NEWS.adoc, docs/nut.dict, drivers/nutdrv_qx.c, drivers/snmp-ups.c, drivers/upshandler.h, drivers/usbhid-ups.c
Note that `errno=EINVAL` means unsupported parameter value for us here.
Inspired by discussion and fixes for PR #2956; follows up from PR #2957.
Updates `usbhid-ups`, `snmp-ups` and to an extent `nutdrv_qx` to have similar functionality with their mappings handling.
=> Allow mapping functions to return EINVAL for setvar/instcmd to abort consistently

NEWS.adoc, configure.ac, docs/.gitignore, docs/Makefile.am, docs/asciidoc.conf.in, docs/configure.txt, docs/man/.gitignore, docs/man/Makefile.am, docs/man/asciidoc.conf, docs/man/asciidoc.conf.in, docs/nut.dict
HTML rendering of NUT docs (including man pages) after PR #2797 included references to online versions of system-provided man pages (for standard commands). This was initially based on https://linux.die.net resource.
This PR fixes the man page rendering from `ulink` (docbook xml) to `a href` (direct html) tags, and extends the man page referencing macros to allow building packaged references to custom distro-dependent resources.
Man page sections involved in these references may also be rewritten; more work is however needed to create correct URLs because different distros might place system commands into various places (there may not be one transformation pattern to cover everything). And, of course, any such remote URL is subject to availability of an online resource not managed by …
=> Fix external man page links

.circleci/config.yml, .github/workflows/codeql.yml, Makefile.am, NEWS.adoc, clients/Makefile.am, data/driver.list.in, docs/nut-versioning.adoc, drivers/Makefile.am, drivers/snmp-ups.c, server/Makefile.am, tests/Makefile.am, tools/gitlog2version.sh, tools/nut-scanner/Makefile.am, tools/nutconf/Makefile.am
Make sure (parallel) builds started from scratch in NUT subdirs with code are viable recipe-wise, and add a way to keep making sure in the future :)
Not attached to NUT CI farm runs currently, but added to other CI hosting pipelines (GHA/CodeQL, CircleCI).
Piggy-back a few small fixes elsewhere.
=> [CI] Introduce a `make check-parallel-builds` recipe

NEWS.adoc, appveyor.yml, docs/config-prereqs.txt
Appveyor CI builds tend to forget the caches saved earlier, if a build fails (e.g. due to timeout). A series of recent commits fiddles with this recipe, aiming to have it complete the build for the master branch, and cache at least some pieces it would use in later runs.
Builds of changes pushed directly to master did not generate a cache: they completed "green" and... there goes nothing:
```
...
Discovering tests...OK
Collecting artifacts...
Found artifact 'config.log' matching 'config.log' path
Found artifact 'config.nut_report_feature.log' matching 'config.nut_report_feature.log' path
Uploading artifacts...
[1/2] config.log (1,710,584 bytes)...100%
[2/2] config.nut_report_feature.log (5,813 bytes)...100%
Build cache is not configured for the build environment.
Build success
```
Maybe a …
=> Re-enable actual builds in Appveyor CI

docs/download.txt, docs/nut.dict
Apple shortened the name to "OS X" in 2011 and then changed it to "macOS" in 2016 to align with the branding of Apple's other operating systems.
https://en.wikipedia.org/w/index.php?title=MacOS&oldid=1304698699
case.
or …
=> Include macOS with Mac OS X

docs/download.txt
TIL nut has been in Homebrew since 2014.
case.
(several vendors do use same interface chips for unrelated protocols). …
=> Update download.txt with link to Homebrew formula for macOS

drivers/apc_modbus.c
As requested in #2289. Only compile tested, but hopefully it should be a fairly obvious fix.
=> apc_modbus: Fix invalid memory access for USB vendor/product/serial

ci_build.sh, configure.ac, scripts/Makefile.am, scripts/Solaris/postinstall.in, scripts/Solaris/preremove.in, scripts/Solaris/reset-ups-usb-solaris.sh.sample, scripts/misc/.gitignore, scripts/misc/nut.bash_completion, scripts/misc/nut.bash_completion.in, scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
=> scripts: Avoid `tail -n +/-NUM` syntax as less portable than `tail +/-NUM`
