networkupstools/nut

- INSTALL.nut
Spelling fixes and capitalization of SUSE
> Spelling fixes

- drivers/bcmxcp.h
- drivers/bcmxcp_usb.c
Without this patch current driver unable to establish communication with Eaton 9125-5000g UPS.
> Fix Powerware usb driver

- clients/nutclient.h
> nutclient compilation warning #269

- clients/nutclient.cpp
- tests/Makefile.am
- tests/nutclienttest.cpp
> Fix bug #232

- configure.ac
This should take care of issue https://github.com/networkupstools/nut/issues/311
> Fix docgen ability (verify we actually CAN generate chosen doc types with our tools)

- scripts/augeas/gen-nutupsconf-aug.py
- tools/gitlog2changelog.py
This makes the script work with Python 2.6+.
Fixes #345.
cc @zman0900
> Make gen-nutupsconf-aug.py work with Python 3

- configure.ac
- docs/Makefile.am
While setting up a local farm to build the code in different modes and OSes, stumbled upon a few complaints in the configure/make logs. These commits should fix them.
> Fix docgen ability - small fixes

- common/common.c
- configure.ac
- include/common.h
- tools/nut-scanner/nutscan-init.c
Port of an improvement from the DMF branch, prompted by issue #361 .
> Improved ltdl support, applied for libusb and libneon alternates

- drivers/Makefile.am
- drivers/eaton-ats30-mib.c
- drivers/eaton-ats30-mib.h
- drivers/snmp-ups.c
ATS30 MIB differs from previously integrated EATON ATS driver.
> snmp-ups: support Eaton Automatic Transfer Switch ATS30

- conf/ups.conf.sample
Upstreaming fixes applied to our project at work
By: ???
> Document and pre-set the "maxretry" option in ups.conf.sample

- conf/ups.conf.sample
- data/driver.list.in
- drivers/Makefile.am
- drivers/apc-pdu-mib.c
- drivers/apc-pdu-mib.h
- drivers/snmp-ups.c
> DMF remerge 20170131

- scripts/DMF/dmfnutscan/dmfnutscan-snmp.dmf
- scripts/DMF/dmfsnmp/apc-pdu-mib.dmf
> DMF updated to know APC-PDU-MIB

- docs/FAQ.txt
- docs/config-notes.txt
- docs/nut.dict
- docs/scheduling.txt
- docs/security.txt
> Doc paths - revised a bit

- docs/nut.dict
Strange whitespace embedded in original PR
> nut.dict header line

- docs/Makefile.am
- docs/man/upsd.conf.txt
- docs/nut.dict
> Fix the recent typing/spellchecking fixes :)

- docs/nut-names.txt
- docs/nut.dict
> Make spellchecker happy about "dephasing"

- drivers/eaton-pdu-marlin-mib.c
- scripts/DMF/dmfsnmp/eaton-pdu-marlin-mib.dmf
> Fix typo in OID, noticed by aquette

- INSTALL.nut
- docs/nut.dict
Details usb device permissions. Also pkg and new port config style.
> doc: Update installation instructions for FreeBSD

- tools/nut-usbinfo.pl
to reduce code duplication and solve an associated FIXME
> Cleanup usbinfo code

- m4/nut_check_libavahi.m4
- m4/nut_check_libneon.m4
This should take care of issue #593
> Use a fallback setup for libneon if pkg-config failed

- configure.ac
- drivers/libshut.c
- drivers/libusb.c
- drivers/usbhid-ups.c
Help figure out faster which codepath to debug :)
> libusb tracing debug text

- drivers/cyberpower-mib.c
voltage, MIB mappings to cyberpower-mib.c
Tested with an RM202 card.
> Added UPS load, battery charge, input voltage/frequency, and output 

- scripts/systemd/nutshutdown.in
Follows up for #382 and #384
CC @bigon
> Systemd nutshutdown sanity checks

- tools/Makefile.am
- tools/nut-scanner/Makefile.am
This adds some better organization into the nut-scanner makefile, and makes it easier for us to develop and reconcile the DMF branch :)
> tools/ Makefiles : refactor with clarifications from DMF branch

- Makefile.am
- common/common.c
- common/dmfsnmp.c
- scripts/DMF/dmf-test.c
- scripts/DMF/dmfify-mib.sh
- scripts/DMF/jsonify-mib.py
- scripts/DMF/nut_cpp
- scripts/DMF/xmlify-mib.py
Subsequent development of DMF-related codebase exposed some situations that complicate building and testing it on today's CI and workstation setups. These commits should improve the situation for those.
> DMF fix builds

- clients/Makefile.am
- configure.ac
- tests/Makefile.am
Hopefully would rectify http://buildbot.networkupstools.org/public/nut/builders/OpenBSD-x64/builds
CC : @boricj
> Fix builds against older GCC (no C++11 in the system)

- drivers/solis.c
- drivers/solis.h
@aquette suggested in https://github.com/networkupstools/nut/pull/511 that I added myself as author. No changes were made to source code.
> Added author info for previous merge https://github.com/networkupstools/nut/pull/511

- drivers/eaton-pdu-marlin-mib.c
- drivers/snmp-ups.c
Avoid segfaults while iterating an Eaton G3 ePDU with daisy chain.
> [DNMY] Fix snmp templates

- docs/Makefile.am
- docs/documentation.txt
- docs/nut.dict
- docs/solaris-usb.txt
- scripts/Solaris/README
@aquette : I remember you also had some blog or documentation on this but could not find it quickly while reviewing my and barbz's notes. Remember if you had some more nuances to keep in mind?
> Add docs/solaris-usb.txt for posterity

- docs/acknowledgements.txt
Another potential bike-shedding moment, so posting the small change as a separate PR.
> docs/acknowledgements.txt: revise the last paragraph for listing corporate contributors

- drivers/main.c
Closes: https://github.com/networkupstools/nut/issues/835
> Fix dstate init call WRT data dump

- configure.ac
Follows up from #833 discussion.
CC @cschuber and @clepple
> Revise termios.h and detection of ability to build serial drivers

- docs/nut-names.txt
- drivers/eaton-pdu-marlin-mib.c
This includes:
* improved visibility on whole-unit and per-outlet switchability visibility
* fix on outlet identifier
> snmp-ups: Eaton ePDU outlet management improvements

- drivers/isbmex.c
> Fightwarn fallthrough questionable - isbmex

- .travis.yml
- ci_build.sh
- clients/upsset.c
- docs/developers.txt
- docs/nut.dict
- drivers/nutdrv_qx.h
- drivers/rhino.c
- tests/Makefile.am
The primary issue which remains unsolved now is #850 - so some more builds which are not too pedantic have better chances of survival in CI. A superset of this PR was tested to pass green on Travis, so this one will merge when its test passes, just to avoid typos or spellchecker grumpiness.
> Fightwarn - a few more unclassified fixes, and enable more test cases as supported

- .travis.yml
- configure.ac
Fixes issue #873 found with investigations for #823 / #844 effort.
> Fightwarn - mess-up about explicit standards and picking cxx11

- .gitignore
- .travis.yml
- common/common.c
- configure.ac
- drivers/apcupsd-ups.c
- include/attribute.h
- include/parseconf.h
- m4/nut_stash_warnings.m4
Follows up from #823 and #844 to address some system-dependent CI matrix issues, and apply a few "cosmetic fixes" to codebase.
> Fightwarn - some more groundwork

- clients/upslog.c
- clients/upsstats.c
- drivers/mge-hid.c
- drivers/microdowell.c
- drivers/rhino.c
- drivers/solis.c
Fixes part of LGTM.com suggestions per https://github.com/networkupstools/nut/issues/823#issuecomment-724135948
> Fightwarn - lgtm.com - localtime_r (thread-safe)

- common/common.c
- common/parseconf.c
- common/state.c
- drivers/dstate.c
- drivers/dstate.h
- drivers/powercom.c
- drivers/riello.c
- include/state.h
- server/netget.c
- server/upsd.c
Fixes part of LGTM.com suggestions per https://github.com/networkupstools/nut/issues/823#issuecomment-724135948  and MacOS llvm complaints about type mismatches.
> Fightwarn - lgtm.com - smallstuff

- drivers/bestfcom.c
- drivers/dstate.c
- drivers/libshut.c
- drivers/nutdrv_atcl_usb.c
- drivers/snmp-ups.c
- drivers/snmp-ups.h
- m4/ax_c_pragmas.m4
- tools/nut-scanner/nutscan-ip.c
> Fightwarn - a few cases of casting and alignments

- configure.ac
- drivers/blazer.c
- drivers/cps-hid.c
- drivers/metasys.c
- drivers/mge-hid.c
- drivers/nutdrv_qx.c
- drivers/nutdrv_qx_bestups.c
- drivers/nutdrv_qx_voltronic.c
- drivers/rhino.c
- drivers/snmp-ups.c
- drivers/solis.c
- drivers/upscode2.c
- include/Makefile.am
- include/nut_float.h
Follows up from #823 effort.
This PR has potential to somehow change interpretations of numbers in NUT calculations, so careful review is encouraged. Also I hope I did not mix up parenthesis grouping and negations, but it is late night here so everything is possible (caught some of those before posting)...
Would merge after someone LGTMs this :)
> Fightwarn - Introduce nut_float.h to compare floating-point numbers in a safer manner

- drivers/snmp-ups.c
- tools/nut-scanner/scan_snmp.c
> Fix incorrect fatal message for privProtocol

- tools/nut-snmpinfo.py
> nut-scanner: improve SNMP extractor script

- clients/upsmon.c
- conf/upsmon.conf.sample.in
- docs/config-notes.txt
- docs/man/upsmon.txt
- docs/net-protocol.txt
- docs/security.txt
While working on other subjects in documentation for #840 issue, found some points to improve that are not related directly to that work.
Note that some of these changes can include terminology being obsoleted - another PR will take care of than when we settle on new keywords.
> Docs update and clarification

- docs/security.txt
- docs/solaris-usb.txt
- drivers/asem.c
- drivers/nutdrv_qx.c
- drivers/phoenixcontact_modbus.c
- drivers/usbhid-ups.c
Replace some undesired words by others, or clarify their (vendor-dependent) context.
> Easy fixes for issue #840

- docs/nut-names.txt
> RFC: add new variable battery.packs.external

- docs/nut-names.txt
Add battery.status, battery.capacity.nominal and Li-ion battery cell min/max voltage / temperature
> Extend battery information collection

- tests/nutlogtest.c
Technically, I am surprised this was not complaining before, though.
> tests/nutlogtest.c: fix more fallout from #675

- docs/developers.txt
- docs/nut-qa.txt
- docs/nut.dict
> Replace docs references to defunct Travis CI with new NUT CI farm

- docs/ci-farm-lxc-setup.txt
- docs/config-prereqs.txt
- docs/nut.dict
How to not forget the magic for containers... to recover the farm or run things locally? :)
> docs/ci-farm-lxc-setup.txt: document container SSH tricks

- drivers/nut-libfreeipmi.c
- tools/nut-scanner/scan_ipmi.c
Follows up from #823 to fight warnings in NUT codebase
> Fightwarn: ipmi driver and nut-scanner

- drivers/snmp-ups.c
> Fix snmp-ups "Unknown mibs value" message, when it is misleading

- drivers/mge-xml.c
> Eaton XML/PDC: add External Battery Module count

- docs/FAQ.txt
subj, community comments welcome
> docs/FAQ.txt: update for use-cases of dummy-ups in relay mode

- docs/FAQ.txt
subj, community comments welcome
> docs/FAQ.txt: update for interactions via github (issues, PRs, ...)

- data/driver.list.in
- drivers/Makefile.am
- drivers/salicru-hid.c
- drivers/salicru-hid.h
- drivers/usbhid-ups.c
- scripts/upower/95-upower-hid.rules
Initial release for Salicru driver to help with #732
> Initial release for Salicru driver

- docs/FAQ.txt
Follows up in a way to #1196 so CC @tessus
> docs/FAQ.txt: extend Q&A on "NUT proxying" with mention of "clone" driver

- ci_build.sh
- common/Makefile.am
- drivers/microsol-common.c
- drivers/snmp-ups.c
- m4/nut_check_libnetsnmp.m4
- tools/nut-scanner/nut-scan.h
- tools/nut-scanner/nut-scanner.c
- tools/nut-scanner/nutscan-init.c
- tools/nut-scanner/scan_nut.c
- tools/nut-scanner/scan_snmp.c
- tools/nut-scanner/scan_xml_http.c
...about use-case of semaphore
> Fix a few warnings for recent nut-scanner backports from 42ITy

- drivers/apcsmart-old.c
- drivers/apcsmart-old.h
- drivers/apcsmart.c
- drivers/apcsmart.h
- drivers/blazer.h
- drivers/blazer_ser.c
- drivers/blazer_usb.c
- drivers/clone-outlet.c
- drivers/clone.c
- drivers/netxml-ups.c
- drivers/nutdrv_qx.c
- drivers/nutdrv_qx.h
- drivers/nutdrv_qx_bestups.c
- drivers/nutdrv_qx_blazer-common.c
- drivers/nutdrv_qx_masterguard.c
- drivers/nutdrv_qx_mecer.c
- drivers/nutdrv_qx_voltronic-qs-hex.c
- drivers/nutdrv_qx_voltronic.c
- drivers/snmp-ups.c
- drivers/solis.c
- drivers/solis.h
- drivers/tripplite_usb.c
- tools/nut-scanner/scan_snmp.c
Mostly mismatches in serial drivers
Follows up from #823 fightwarn effort
> Fightwarn: more alignment of ints sizes and signedness

- Makefile.am
- ci_build.sh
Catching up with imperfections of recent past
> Small recipe fixes

- ci_build.sh
- docs/developers.txt
Collecting battle scars from shells, spells and docs.
> CI: Improve ci_build.sh to help more in the Fightwarn cause

- data/driver.list.in
> Add Powerwalker VFI 3000 TG Online UPS to driver.list.in

- Jenkinsfile-dynamatrix
- ci_build.sh
- common/common.c
- conf/upsmon.conf.sample.in
- configure.ac
- data/driver.list.in
- docs/developers.txt
- docs/man/nut-scanner.txt
- docs/man/snmp-ups.txt
- docs/nut.dict
- drivers/blazer_usb.c
- drivers/hidparser.c
- drivers/hidparser.h
- drivers/libhid.c
- drivers/libhid.h
- drivers/libshut.h
- drivers/nut_libusb.h
- drivers/nutdrv_qx.c
- drivers/richcomm_usb.c
- drivers/riello_usb.c
- drivers/tripplite-hid.c
- drivers/usbhid-ups.c
- include/nut_stdint.h
- m4/ax_c_pragmas.m4
- m4/nut_check_libusb.m4
- scripts/upower/95-upower-hid.rules
- server/upsd.c
- tests/Makefile.am
- tests/getvaluetest.c
- tools/nut-scanner/scan_usb.c
Bringing libusb-1.0 and libusb-1.0+0.1 branches to another level of common baseline, to simplify subsequent PRs for eventual merge of the feature to master for #300.
Note: For finishing touches, https://github.com/networkupstools/nut/tree/fightwarn-libusb-1.0 will be merged into this target branch next.
> libusb-1.0 resync from master as of 2021-12-21

- configure.ac
- drivers/Makefile.am
- drivers/bcmxcp_usb.c
- drivers/blazer_usb.c
- drivers/libhid.h
- drivers/libshut.c
- drivers/libshut.h
- drivers/libusb1.c
- drivers/nut_libusb.h
- drivers/nutdrv_atcl_usb.c
- drivers/nutdrv_qx.c
- drivers/richcomm_usb.c
- drivers/riello.h
- drivers/riello_usb.c
- drivers/tripplite_usb.c
- drivers/usb-common.h
- drivers/usbhid-ups.c
- m4/nut_check_libusb.m4
- tools/nut-scanner/nutscan-init.c
- tools/nut-scanner/scan_usb.c
- tools/nut-usbinfo.pl
Helper "runner-up" commits for PR #1240 (rebasing that changeset over current target branch state, to minimise the noise in log and githubweb diff).
> Fightwarn libusb 1.0 rebased part1

- docs/packager-guide.txt
- scripts/subdriver/gen-usbhid-subdriver.sh
Thanks @smainz for noticing in #1189!
> Fix fallout from PR #1245 (missed gen-usbhid-subdrivers.sh)

- configure.ac
- docs/configure.txt
- docs/man/Makefile.am
Hopefully...
Closes: #1212
Closes: #1030
also:
* docs/man/Makefile.am: build and install nutdrv_siemens_sitop man pages
> configure.ac: refine delivery of systemd related files

- scripts/subdriver/gen-snmp-subdriver.sh
> SNMP subdriver generation script: fixes and improvements

- ci_build.sh
- configure.ac
- drivers/snmp-ups.h
- m4/ax_c_pragmas.m4
- m4/ax_run_or_link_ifelse.m4
- m4/nut_check_libnetsnmp.m4
- m4/nut_compiler_family.m4
> Fix cross builds

- drivers/salicru-hid.c
I have implemented and testes this descriptors on Salicru Twin Pro 2.
Is my first fork/pull request so please let me know if I didn't follow some rule or need to do something.
> Add tested descriptors for Salicru Twin Pro 2

- docs/config-prereqs.txt
- scripts/python/README
- scripts/python/module/PyNUT.py.in
Python one was a breaker from #1328
> Fix a few Typos

- NEWS
- docs/net-protocol.txt
- docs/nut.dict
- server/netcmds.h
> Add "PROTVER" as alias to "NETVER" for NUT v2.8.0

- data/driver.list.in
- docs/man/usbhid-ups.txt
> Update NUT HCL before 2.8.0 release

- data/driver.list.in
- drivers/salicru-hid.c
- scripts/upower/95-upower-hid.hwdb
First reported in #1416 - thanks!
> [HCL] Add known support for Salicru SPS 850 ADV T

- .circleci/config.yml
- ci_build.sh
- docs/config-prereqs.txt
- docs/nut.dict
- drivers/dummy-ups.c
- drivers/macosx-ups.c
https://app.circleci.com/pipelines/github/networkupstools/nut?filter=all
Closes: #1415 
Closes: #1419 
I'd say this is a "usable PoC quality", in that builds apparently pass, but implementation (detection instead of magic-passing of env vars for build settings) can be refined so it just works out of the box... later, and better done by someone with an actual Mac :)
CC @clepple : there were some fixes for macos driver, can you give those a second look please? and/or check on a live system, to make sure it still behaves well? :)
> CircleCI project setup and some fixes for MacOS

- .circleci/config.yml
- ci_build.sh
Follow-up for #1421 and #1419 to run more varied scenarios on MacOS while balancing the compute-time spent there.
> CircleCI project setup matrix

- drivers/cyberpower-mib.c
Closes: #1427
Introduced by  #1381 for addressing #1377 (raised in #590 discussion).
> Update cyberpower-mib.c C table ordering

- NEWS
- UPGRADING
- configure.ac
- drivers/Makefile.am
> Separate NUT software-only drivers from serial ones

- clients/upsmon.h
(Part of change for Windows branch, to minimize differences with master per #1524)
Also fixes NOTIFY_CAL to have same settings as everyone else.
> Define a NOTIFY_DEFAULT flag, use it to initialize upsmon.

- common/common.c
- configure.ac
Part of changes proposed in #1524
> common/common.c: refactor single get_libname_in_dir() from loop of get_libname()

- clients/upsclient.c
- clients/upsmon.c
- clients/upssched.c
- common/common.c
- common/snprintf.c
- docs/man/ups.conf.txt
- docs/nut.dict
- drivers/blazer_usb.c
- drivers/clone-outlet.c
- drivers/genericups.c
- drivers/isbmex.c
- drivers/libhid.h
- drivers/libshut.c
- drivers/snmp-ups.c
- drivers/usbhid-ups.c
- include/str.h
- server/upsd.c
- tools/nut-scanner/nutscan-serial.c
- tools/nut-scanner/scan_avahi.c
- tools/nut-scanner/scan_ipmi.c
- tools/nut-scanner/scan_nut.c
- tools/nut-scanner/scan_snmp.c
- tools/nut-scanner/scan_usb.c
- tools/nut-scanner/scan_xml_http.c
Another "noise removal" for parts of #1524
> Fix whitespace and some comments

- docs/config-prereqs.txt
- docs/nut.dict
Some updated notes about OpenBSD worker setup for NUT CI farm.
> OpenBSD CI worker comments

- NEWS
- common/common.c
- docs/nut.dict
- tools/nut-scanner/nutscan-init.c
Inspired by issue #805
Follows up from #1527
> Extend shared library-finding method and use-case to raise chances of success

- INSTALL.nut
- common/common.c
- configure.ac
- drivers/apcsmart.c
- drivers/belkinunv.c
- drivers/serial.c
- scripts/Windows/README
- server/sstate.c
- server/upsd.c
- tools/nut-scanner/nutscan-ip.h
- tools/nut-scanner/scan_eaton_serial.c
- tools/nut-scanner/scan_usb.c
- tools/nut-scanner/scan_xml_http.c
Also further reduce differences vs. master, follow-up from #1546 and #1525, aiming to make #5 reviewable eventually.
> Windows v2.8.0 branch clean-up

- drivers/ietf-mib.c
> snmp-ups: flag invalid negative values for IETF MIB

- clients/upssched.c
- clients/upssched.h
- common/common.c
- drivers/apcsmart.c
- drivers/belkinunv.c
- drivers/clone-outlet.c
- drivers/clone.c
- drivers/dstate.c
- drivers/dstate.h
- drivers/dummy-ups.c
- drivers/libhid.h
- drivers/libshut.c
- drivers/libshut.h
- drivers/main.c
- drivers/main.h
- drivers/serial.c
- drivers/serial.h
- include/common.h
- server/nut_ctype.h
- server/sstate.c
- server/sstate.h
- server/stype.h
- server/upsd.c
- server/upstype.h
- tools/nut-scanner/scan_eaton_serial.c
Issue #1556 - where POSIX has "int", Windows has all types of... types.
> Fix file-descriptor type mess

- UPGRADING
- clients/upssched.c
- drivers/dstate.c
- include/common.h
Follow-up to PR #1557 and issue #1556
> More cleanup after Fix TYPE_FD mess

- NEWS
- clients/nutclient.cpp
- clients/nutclient.h
- clients/nutclientmem.cpp
- clients/nutclientmem.h
- docs/net-protocol.txt
- docs/nut.dict
- scripts/python/module/PyNUT.py.in
- scripts/python/module/README
- scripts/python/module/test_nutclient.py.in
- tests/NIT/nit.sh
- tests/cpputest-client.cpp
> Fix PyNUT ListClients() and DeviceLogin(), and nutclient (C++) equivalents

- m4/nut_check_python.m4
Closes: #1583 (included in #1581)
> PY say NO!

- appveyor.yml
- clients/nutclient.cpp
- clients/upssched.c
- common/Makefile.am
- configure.ac
- drivers/apcupsd-ups.c
- drivers/dstate.c
- drivers/netxml-ups.c
- drivers/riello_ser.c
- m4/nut_check_libnetsnmp.m4
- server/conf.c
- tools/nut-scanner/Makefile.am
> Windows v2.8.0 branch cleanup

- drivers/blazer.c
Follow-up after #1524, #1525 and friends, and #1596 merged recently
> Update Windows branch from master, as of 2022-08-22

- ci_build.sh
- configure.ac
- tests/NIT/Makefile.am
- tests/NIT/nit.sh
Generic updates first made on Windows branch
> Bump CI and test scripts

- clients/Makefile.am
- clients/nutclientmem.cpp
- include/Makefile.am
- tools/nut-scanner/nut-scan.h
- tools/nut-scanner/nutscan-ip.c
- tools/nut-scanner/scan_eaton_serial.c
- tools/nut-scanner/scan_nut.c
- tools/nut-scanner/scan_snmp.c
Partially addresses concerns from issue #1593 and is the master-branch applicable part of PR #1615
> Revise publicly distributed NUT headers (were generally neglected)

- clients/Makefile.am
- clients/nutclientmem.cpp
- docs/new-drivers.txt
- docs/nut.dict
- drivers/serial.c
- drivers/serial.h
- include/Makefile.am
- scripts/Windows/build-mingw-nut.sh
- tools/nut-scanner/nut-scan.h
- tools/nut-scanner/nutscan-ip.c
- tools/nut-scanner/nutscan-ip.h
- tools/nut-scanner/scan_eaton_serial.c
- tools/nut-scanner/scan_nut.c
- tools/nut-scanner/scan_snmp.c
> Revise man pages (for Windows branch changes) and distributed headers (were generally neglected)

- NEWS
- docs/config-prereqs.txt
- include/Makefile.am
- scripts/Windows/README
- scripts/python/module/PyNUT.py.in
- scripts/python/module/README
- scripts/python/module/test_nutclient.py.in
- tests/NIT/nit.sh
Solve some merge conflicts to facilitate mergeability (again) of PR #1611
Notably add actual ability to fail if PyNUT self-tests find inconsistencies #1617
> Resync Windows v2.8.0 branch from master yet again

- docs/hid-subdrivers.txt
- docs/nut.dict
- scripts/subdriver/gen-usbhid-subdriver.sh
Slight bump to the venerable helper script, retracing the learnings from trying to make it run recently ;)
> Update gen-usbhid-subdriver.sh and docs/hid-subdrivers.txt

- NEWS
- drivers/nutdrv_qx_voltronic-qs.c
> drivers/nutdrv_qx_voltronic-qs.c: add support for "H protocol" [#1623]

- drivers/apc-epdu-mib.c
- drivers/snmp-ups.c
better handling of 1 and 3phases data, and outlet description
> snmp-ups: update APC ePDU subdriver for 1/3ph

- data/driver.list.in
- drivers/Makefile.am
- drivers/eaton-pdu-nlogic-mib.c
- drivers/eaton-pdu-nlogic-mib.h
- drivers/snmp-ups.c
Integrate nLogic pdu (with snmp driver).
No test done yet with real device (TBC).
> Integrate Eaton/nLogic pdu (snmp)

- NEWS
- configure.ac
- docs/configure.txt
- docs/hid-subdrivers.txt
- docs/snmp-subdrivers.txt
- drivers/apc-ats-mib.c
- drivers/apc-epdu-mib.c
- drivers/apc-mib.c
- drivers/apc-pdu-mib.c
- drivers/belkin-hid.c
- drivers/compaq-mib.c
- drivers/cps-hid.c
- drivers/delta_ups-mib.c
- drivers/eaton-ats16-nm2-mib.c
- drivers/eaton-ats16-nmc-mib.c
- drivers/eaton-ats30-mib.c
- drivers/eaton-pdu-marlin-mib.c
- drivers/eaton-pdu-nlogic-mib.c
- drivers/emerson-avocent-pdu-mib.c
- drivers/ever-hid.c
- drivers/hpe-pdu-mib.c
- drivers/hpe-pdu3-cis-mib.c
- drivers/huawei-mib.c
- drivers/idowell-hid.c
- drivers/liebert-hid.c
- drivers/powercom-hid.c
- drivers/raritan-px2-mib.c
- drivers/tripplite-hid.c
- scripts/subdriver/gen-snmp-subdriver.sh
- scripts/subdriver/gen-usbhid-subdriver.sh
Troubleshooting aid, to help developers help users.
Closes: #1699
> Introduce WITH_UNMAPPED_DATA_POINTS for USB-HID and SNMP subdrivers

- INSTALL.nut
- NEWS
- docs/man/upsmon.txt
- docs/nut.dict
Closes: #1750 
Closes: #1721
Relates-to: #1736
> Update docs wording and hints per user feedback

- docs/man/ups.conf.txt
- docs/man/upsdrvctl.txt
- docs/man/upsdrvsvcctl.txt
- drivers/upsdrvctl.c
- scripts/systemd/nut-driver@.service.in
drivers/upsdrvctl.c, scripts/systemd/nut-driver@.service.in: add support for NUT_IGNORE_NOWAIT
Closes: #1753
> upsdrvctl.c: optional NUT_IGNORE_NOWAIT

- docs/nut-names.txt
- drivers/libusb0.c
- drivers/libusb1.c
- drivers/usb-common.c
- drivers/usb-common.h
> Minor fixes to nut-names text and some source comments

- COPYING
- docs/nut.dict
Question to the gallery: is this the right thing to do, and the right way to do it? Please do reply :)
CC @bigon @bagder @kleink
> COPYING: update to acknowledge codebase picked up from BSD, curl and CC BY-SA sources over time

- MAINTAINERS
Note that I maintain the pkgsrc entry.
> MAINTAINERS: add pkgsrc

- conf/upsd.conf.sample
Explain firewall and listening on LAN only more clearly.
Fixes #550.
> upsd.conf.sample: Clarify LISTEN/firewall comments

- NEWS
- drivers/powercom.c
> powercom driver should try harder to refresh data from device [#356]

- scripts/systemd/nut-driver@.service.in
- scripts/systemd/nut-monitor.service.in
- scripts/systemd/nut-server.service.in
> nut-{server,monitor,driver@}.service: clarify network-online.target dependency

- drivers/libusb0.c
- drivers/libusb1.c
> drivers/libusb{0,1}.c: clarify expected/got byte amounts (and fix typo)

- Makefile.am
- ci_build.sh
- clients/Makefile.am
- common/Makefile.am
- configure.ac
- docs/Makefile.am
- docs/man/Makefile.am
- drivers/Makefile.am
- include/Makefile.am
- scripts/python/Makefile.am
- server/Makefile.am
- tests/Makefile.am
- tests/NIT/Makefile.am
- tools/nut-scanner/Makefile.am
At expense of more relevant messages (overly detailed in normal conditions)
> CI: quieter builds, easier log search

- drivers/huawei-ups2000.c
Occasionally, the UPS takes longer than 1 second to respond and finish transmitting a message. This causes a timeout in modbus_read_registers(), and the driver is supposed to retry the request and recover from the failure. Unfortunately, when the driver retries, instead of getting the result of the current request, the leftover bytes from the previous read is received from the serial buffer, creating invalid messages. It causes all following reads to also fail, often with an "Invalid CRC" error, and the driver can never recovery from the failure.
This commit fixes the bug (Issue #1846) by flushing the buffer using function modbus_flush() before invoking modbus_read_registers(). The libmodbus timeout value is also bumped to 2 seconds to avoid unnecessary timeouts and subsequent retries. …
> huawei-ups2000: fix broken timeout recovery behavior in Issue #1846.

- clients/upsc.c
- clients/upscmd.c
- clients/upslog.c
- clients/upsmon.c
- clients/upsrw.c
- clients/upssched.c
- docs/developers.txt
- server/upsd.c
- tools/nut-scanner/nut-scanner.c
This stems from #1858 discussion and may help troubleshoot it in-vivo.
Closes #1863 
...along the way
> Add debug verbosity setting for upssched, add `upsdebugx` for `parse_at()`, and add help lines for `-h/-V` in many tools

- ci_build.sh
- common/common.c
- drivers/libusb1.c
- tools/nut-scanner/nutscan-init.c
- tools/nut-scanner/scan_ipmi.c
- tools/nut-scanner/scan_snmp.c
- tools/nut-scanner/scan_usb.c
- tools/nut-scanner/scan_xml_http.c
Primarily nut-scanner library search. Also saw a bug with `become_user` self-logging.
> Fix some runtime issues seen on Windows

- ci_build.sh
- docs/developers.txt
- docs/nut.dict
Normally this chapter should grow, as I get to the systems it was experimented on. At the very least, seeding the idea that using IDEs to step through NUT code is feasible (also on Windows), is a milestone in its own right :)
> Docs: touch on IDE support

- NEWS
- docs/man/upsdrvctl.txt
- drivers/upsdrvctl.c
- tests/NIT/nit.sh
Follow-up from #1806 
Raised by #1874 discussion
> fix upsdrvctl behavior in foregrounding mode

- common/common.c
- configure.ac
- include/common.h
Address issues #1879 and #1881
> FDs 0,1,2 are not always STDIO

- data/driver.list.in
- drivers/salicru-hid.c
- scripts/upower/95-upower-hid.hwdb
I have added descriptors for the SPS 3000 ADV RT2
Is my first fork so please let me know if I didn't follow some rule or need to do something.
> salicru-hid.c: Add known support for Salicru SPS 3000 ADV RT2

- docs/new-drivers.txt
- docs/nut.dict
- drivers/main.c
- drivers/upsdrvctl.c
- drivers/upsdrvquery.c
- drivers/upsdrvquery.h
Address #1923, #1927, #1929 remainders after the work on #1922/#1914.
> Some follow-up to new driver commands

- docs/man/upslog.txt
- docs/new-drivers.txt
- docs/nut-names.txt
> Fix documentation references to `_status_data`

- Jenkinsfile-dynamatrix
Investigate/test-fixes for CI pipeline:
* https://github.com/networkupstools/jenkins-dynamatrix/issues/15
* https://github.com/networkupstools/jenkins-dynamatrix/issues/16
* https://github.com/networkupstools/jenkins-dynamatrix/pull/18
> CI: Dynamatrix issue 15

- COPYING
> Update COPYING about LICENSE-DCO file

- NEWS
- drivers/blazer.c
- drivers/main.c
- drivers/snmp-ups.c
Closes: #1891
What started as a research into the problem (and if it is one), ended up as a bunch of notes to keep the research results for posterity. And a few "cosmetic enhancements" collected along the way.
> Investigation for `VAR_SENSITIVE` override/default handling [issue #1891]

- docs/developers.txt
- docs/hid-subdrivers.txt
- docs/new-drivers.txt
- docs/nut.dict
> Docs: update USB explore notes

- NEWS.adoc
- docs/man/Makefile.am
- docs/man/sms_ser.txt
- docs/nut.dict
- docs/sms-brazil-protocol.txt
- drivers/Makefile.am
- drivers/sms_ser.c
- drivers/sms_ser.h
PR For support on SMS Brazil single phase.
Add on docs, instructions about the protocol.
This is for now the driver, maybe in a near future i will migrate it to nutdrv_qx.
> add support to SMS 1phase brazil from #1987

- NEWS.adoc
- scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
NUT scaffolding add-ons for `apc_modbus` driver introduced with #2063
CC @EchterAgo - LGTY?
> Follow-up for `apc_modbus` driver

- NEWS.adoc
- configure.ac
- docs/config-prereqs.txt
- docs/man/upsmon.txt
- docs/nut.dict
- lib/libnutclientstub.pc.in
> docs/config-prereqs.txt: small fixes to Slackware 15 chapter 

- NEWS.adoc
- drivers/powerp-bin.c
- drivers/powerp-txt.c
Having gotten fed up with trying to stabilize the `usbhid-ups` driver with my *CyberPower* UPS's (frequent disconnects or disappearing completely), I'm now just switching everything to serial.
* My OP1500 only uses the binary protocol and doesn't report output voltage, causing unnecessary debug warnings
* Actually parse the provided individual status fields from the UPS, instead of hard coding each UPS's format.
> Powerpanel

- tests/NIT/nit.sh
Improve chances of passing the test suite even on congested CI farm agents
> [CI] `tests/NIT/nit.sh`: introduce `upsd_start_loop()`

- include/nutstream.hpp
- tests/nutipc_ut.cpp
> tests/nutipc_ut.cpp: use unique PID filenames for each test run

- NEWS.adoc
- UPGRADING.adoc
- autogen.sh
- common/common.c
- docs/config-notes.txt
- docs/config-prereqs.txt
- docs/man/nut-scanner.txt
- drivers/dstate.c
- drivers/nut-libfreeipmi.c
- drivers/snmp-ups.c
- m4/ax_c_pragmas.m4
- scripts/systemd/.gitignore
- tools/nut-scanner/nut-scanner.c
- tools/nut-scanner/scan_snmp.c
- tools/nut-usbinfo.pl
Follow-up from #2275 - reconcile differences vs. FTY codebase, and import some of the smaller fixes made in the fork or inspired by work on that PR.
> Bump NUT `master` branch from FTY

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
> [CI] .github/workflows/codeql.yml: extend with python

- .github/workflows/codeql.yml
> .github/workflows/codeql.yml: fix stringification of "ubuntu-latest"

- common/nutconf.cpp
- common/nutwriter.cpp
- include/nutconf.hpp
- tests/nutconf_parser_ut.cpp
- tests/nutconf_ut.cpp
- tools/nutconf/nutconf-cli.cpp
Biting at a few glaring issues before release.
Partially addresses #2294
> Extend `nutconf` vocabulary

- NEWS.adoc
- server/upsd.c
Inspired by investigation for #2417
> server/upsd.c, NEWS.adoc: log-trace daemon exit and clarify other messages

- common/nutwriter.cpp
- include/nutconf.hpp
Follow-up to #2294 and #2425
Closes: #2433
Thanks to @desertwitch and Slackware for noticing what others have missed :)
> Refine nutconf-related code about exceptional situations

- NEWS.adoc
- autogen.sh
- include/nutipc.hpp
- tools/nut-scanner/nutscan-display.c
- tools/nut-usbinfo.pl
> error: template-id not allowed for destructor in C++20

- scripts/Solaris/Makefile.am
- scripts/python/Makefile.am
- tests/Makefile.am
> scripts/python/Makefile.am: revise *.po => *.mo generation [#2529]

- NEWS.adoc
- docs/nut-names.txt
- docs/nut.dict
> Import from FTY branch: "ambient" data point naming

- clients/upsclient.c
- common/common.c
- conf/hosts.conf.sample
- conf/nut.conf.sample
- conf/ups.conf.sample
- conf/upsd.conf.sample
- conf/upsd.users.sample
- conf/upsmon.conf.sample.in
- conf/upssched.conf.sample.in
- conf/upsset.conf.sample
- docs/man/hosts.conf.txt
- docs/man/nut.conf.txt
- docs/man/ups.conf.txt
- docs/man/upsd.conf.txt
- docs/man/upsmon.conf.txt
- docs/man/upssched.conf.txt
- docs/man/upsset.conf.txt
- include/common.h
Follows-up from #2463
Closes: #2543
* On this one, thought about adding some backlog of known bytes to report particularly UTF-8 sequence (suspicion), but that was too intrusive of a change
> Refactor and fix check for process name by PID; update docs for ASCII in config files

- common/state.c
- docs/net-protocol.txt
- docs/sock-protocol.txt
- drivers/dstate.c
- drivers/main.c
- server/netget.c
- server/netset.c
- server/sstate.c
Primer for work on #266, extracted from PR #2549 which may need more time to think about.
This PR picks the mostly-cosmetic bits of that change that can be applied today without functional risks (and reduce clutter for comparisons of heavier changes in that PR or its descendants which might go another way about this change).
> Update log messages and comments in "state" machinery

- NEWS.adoc
- docs/Makefile.am
- docs/man/Makefile.am
- docs/man/clone-outlet.txt
- docs/man/clone.txt
- docs/man/dummy-ups.txt
- docs/nut.dict
- drivers/clone-outlet.c
- drivers/clone.c
Closes: #1686
Also resyncs a bit of code style differences, to minimize comparison noise.
TODO:
> Add man page for `clone-outlet` driver

- data/driver.list.in
- docs/man/usbhid-ups.txt
One batch of HCL/DDL changes destined for NUT v2.8.3 release. A hundred more to go...
See also https://github.com/networkupstools/nut-ddl/pull/44 and https://github.com/networkupstools/nut-ddl/pull/40
> HCL/DDL bump 2024-10-01

- data/driver.list.in
> data/driver.list.in: add usbhid-ups supported Ippon models

- include/nutipc.hpp
In the IPC code, select is called, and the return value checked.  If it's -1, the program aborts.   However, it is legal under POSIX for system calls to be interrupted.   They can be restarted, or the caller can get -1 with `errno` `EINTR`.
This patch changes the code to continue the loop and thus re-enter select, on `EINTR`.
With it, tests get much further on NetBSD 10 amd64.
> core ipc: Handle select returning EINTR

- docs/nut.dict
- scripts/Windows/README.adoc
Follows up from discussion in issue #2724
> scripts/Windows/README.adoc: update dependency build instructions

- scripts/python/Makefile.am
- scripts/python/module/Makefile.am
- tools/gitlog2changelog.py.in
New deprecations noted and taken care of now.
> Fix MacOS CI hiccups with newer python 3.13

- .github/workflows/PyNUTClient.yml
- scripts/python/module/README.adoc
Follows-up from #2773 and #2774
> Run PyNUTClient workflow with interpreter v3.13

- NEWS.adoc
- docs/man/Makefile.am
- docs/man/NUT-Monitor.txt
- scripts/python/app/NUT-Monitor
- scripts/systemd/nut-driver-enumerator-daemon-activator.path.in
- scripts/systemd/nut-driver-enumerator-daemon-activator.service.in
- scripts/systemd/nut-driver-enumerator-daemon.service.in
- scripts/systemd/nut-driver-enumerator.path.in
- scripts/systemd/nut-driver-enumerator.service.in
- scripts/systemd/nut-driver.target.in
- scripts/systemd/nut-driver@.service.in
- scripts/systemd/nut-logger.service.in
- scripts/systemd/nut-monitor.service.in
- scripts/systemd/nut-server.service.in
- scripts/systemd/nut-sleep.service
- scripts/systemd/nut-systemd.preset
- scripts/systemd/nut.target.in
- scripts/systemd/nutshutdown.in
Also fix a few minor issues with docs and comments nearby.
> Fix docs: add man page for `NUT-Monitor` UI client

- README.adoc
- docs/Makefile.am
- docs/nut.dict
- docs/user-manual.txt
Suddenly realized we did not have it written down.
> Document the NUT support policy

- .gitignore
- INSTALL.nut.adoc
- Makefile.am
- NEWS.adoc
- README.adoc
- docs/FAQ.txt
- docs/Makefile.am
- docs/asciidoc-vars.conf
- docs/nut.dict
- docs/user-manual.txt
- lib/libnutconf.pc.in
- lib/libnutscan.pc.in
- server/upsd.c
Closes: #1899
Closes: #1900
Closes: #2665
Also revises several documentation related recipes, and retouches a few docs themselves.
> A few quick fixes before v2.8.3 release

- Jenkinsfile-dynamatrix
- ci_build.sh
- clients/cgilib.c
- clients/upssched.c
- clients/upsset.c
- clients/upsstats.c
- common/common.c
- common/nutstream.cpp
- common/upsconf.c
- common/wincompat.c
- docs/config-prereqs.txt
- docs/nut.dict
- drivers/dstate.c
- drivers/dummy-ups.c
- drivers/hwmon_ina219.c
- drivers/main.c
- drivers/mge-xml.c
- drivers/nhs_ser.c
- drivers/nutdrv_qx.c
- drivers/powerp-txt.c
- drivers/snmp-ups.c
- drivers/upsdrvctl.c
- drivers/upsdrvquery.c
- drivers/upsdrvquery.h
- include/nutconf.hpp
- m4/ax_c_pragmas.m4
- m4/nut_report_feature.m4
- scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
- tools/nut-scanner/Makefile.am
Also test added NUT CI farm worker with NetBSD
CC @gdt
> Fix warnings found by NetBSD

- clients/upssched-cmd
- docs/new-drivers.txt
- docs/nut-names.txt
- drivers/mge-hid.c
- m4/ax_realpath_lib.m4
> Small fixes before 2.8.3

- Jenkinsfile-dynamatrix
- Makefile.am
- ci_build.sh
- configure.ac
- docs/configure.txt
- include/Makefile.am
- m4/ax_c_pragmas.m4
- m4/nut_check_libgd.m4
- m4/nut_check_libgpiod.m4
- m4/nut_check_libusb.m4
- m4/nut_report_feature.m4
Follow-ups from recent fightwarn and FTY branch discoveries.
> Some more small fixes before 2.8.3

- drivers/mge-hid.c
Signed-off-by: DaRK AnGeL <28630321+masterwishx@users.noreply.github.com>
This should fix i hope exit by experimental.ecomode.stop.auto 
https://github.com/networkupstools/nut/issues/2685#issuecomment-2780632975
> ecomode cmd functions addon

- .github/workflows/codeql.yml
- Makefile.am
- NEWS.adoc
- UPGRADING.adoc
- appveyor.yml
- clients/.gitignore
- clients/Makefile.am
- docs/docinfo.xml.in
- include/Makefile.am
- tools/gitlog2version.sh
Previous attempt at a release had intermittent problems probably due to parallel build, popped up once in a few hundred runs though.
> Some recipe fixes for NUT v2.8.3 release

- docs/man/upscmd.txt
- docs/man/upsrw.txt
Follows up from issue #2900 and many before it,
and #659
> docs/man/upscmd.txt, docs/man/upsrw.txt: clarify "OK" vs. waiting for result

- tests/Makefile.am
One positive result of experiments in PR #2744 which otherwise did not lead far, yet...
> tests/Makefile.am: restructure and comment cppunittest_LDADD and cppnit_LDADD

- NEWS.adoc
- docs/man/nutdrv_qx.txt
- docs/nutdrv_qx-subdrivers.txt
- drivers/Makefile.am
- drivers/nutdrv_qx.c
- drivers/nutdrv_qx_blazer-common.c
- drivers/nutdrv_qx_blazer-common.h
- drivers/nutdrv_qx_innovart33.c
- drivers/nutdrv_qx_innovart33.h
I hope that someone with 3/3 topology could test it. Anyway, we can fix small issues later but now I think it's a good starting point for future development and device support
> Add support (experimental) for Ippon Innova RT 3/3

- NEWS.adoc
- docs/packager-guide.txt
- drivers/pijuice.c
- drivers/powervar_cx.c
Follow-up to issue #2565 and PR #2801 that updated most of the drivers that had imperfections in this area.
A few other minor cleanups tagging along.
> drivers/pijuice.c, NEWS.adoc: revise use of status_set() [#2708]

- NEWS.adoc
- clients/upsmon.c
- scripts/systemd/nutshutdown.in
> `upsmon`: Improve `SHUTDOWNCMD` and `NOTIFYCMD` troubleshooting

- NEWS.adoc
- UPGRADING.adoc
- docs/docinfo.xml.in
- tools/gitlog2version.sh
> Prepare dev 2.8.4.1

- docs/Makefile.am
Little typo, big consequences.
> docs/Makefile.am: Fix installation of the pdf files

- NEWS.adoc
- drivers/mge-hid.c
Proposed and tested in [#2380](https://github.com/networkupstools/nut/issues/2380#issuecomment-3263848849)
> mge-hid: Improved support for Eaton 5S1500LCD (US version)
